/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMDAppleServices.framework/IMDAppleServices
 */



@protocol MSSearchDelegate
@optional
-(void)search:(id)search didFinishWithError:(id)error;
-(BOOL)search:(id)search didFindResults:(id)results;
@end

