/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface IMAVHandler : XXUnknownSuperclass {
	NSMutableArray* _pendingChats;
	NSMutableArray* _pendingLookups;
}
+(void)ensureHandlerSetup;
+(void)initialize;
-(void)account:(id)account conference:(id)conference invitationSentSuccessfully:(BOOL)successfully;
-(void)account:(id)account relay:(id)relay handleCancel:(id)cancel fromPerson:(id)person;
-(void)account:(id)account relay:(id)relay handleUpdate:(id)update fromPerson:(id)person;
-(void)account:(id)account relay:(id)relay handleInitate:(id)initate fromPerson:(id)person;
-(void)account:(id)account postedError:(id)error;
-(void)persistentProperty:(id)property changedTo:(id)to from:(id)from;
-(void)property:(id)property changedTo:(id)to from:(id)from;
-(void)account:(id)account conference:(id)conference peerID:(id)anId propertiesUpdated:(id)updated;
-(void)setupComplete;
-(void)pendingVCRequestComplete;
-(void)vcCapabilitiesChanged:(unsigned long long)changed;
-(void)account:(id)account conference:(id)conference cancelRequestInvitationWithBuddy:(id)buddy;
-(void)account:(id)account conference:(id)conference notifyMissedInvitationWithBuddy:(id)buddy;
-(void)account:(id)account conference:(id)conference requestInvitationWithBuddy:(id)buddy;
-(void)_handleIncomingAVChatForNotification:(id)notification;
-(void)_enqueueIMAVChatForNetworkActivation:(id)networkActivation;
-(void)_notifyOfIncomingInvitationFor:(id)aFor notifyInvitationListeners:(BOOL)listeners;
-(void)_notifyInvitationFor:(id)aFor;
-(void)_notifyMissedInvitationFor:(id)aFor;
-(void)account:(id)account conference:(id)conference requestSendResponseWithResult:(int)result toPerson:(id)person;
-(void)account:(id)account conference:(id)conference changedToNewConferenceID:(id)newConferenceID;
-(void)account:(id)account conference:(id)conference peerIDChangedFromID:(id)anId toID:(id)anId4;
-(void)account:(id)account conference:(id)conference receivedAVMessage:(unsigned)message from:(id)from sessionID:(unsigned)anId userInfo:(id)info;
-(void)account:(id)account conference:(id)conference receivedUpdateFrom:(id)from data:(id)data;
-(void)account:(id)account conference:(id)conference receivedCancelInvitationFrom:(id)from properties:(id)properties;
-(void)account:(id)account conference:(id)conference receivedResponseToInvitationFrom:(id)from properties:(id)properties;
-(void)account:(id)account conference:(id)conference receivedCounterProposalFrom:(id)from properties:(id)properties;
-(void)account:(id)account conference:(id)conference receivedInvitationFrom:(id)from properties:(id)properties;
-(void)dealloc;
@end

