/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BBAssertion, NSString, NSArray;

@interface BBResponse : XXUnknownSuperclass <NSCoding> {
	BBAssertion* _lifeAssertion;
	id _sendBlock;
	NSString* _bulletinID;
	BOOL _deliverToPublisher;
	NSString* _actionKey;
	BOOL _sent;
	NSString* _replyText;
@private
	NSArray* _lifeAssertions;
}
@property(retain, nonatomic) NSString* actionKey;	// @synthesize=_actionKey
@property(assign, nonatomic) BOOL deliverToPublisher;	// @synthesize=_deliverToPublisher
@property(retain, nonatomic) NSString* bulletinID;	// @synthesize=_bulletinID
@property(copy, nonatomic) id sendBlock;	// @synthesize=_sendBlock
@property(copy, nonatomic) NSArray* lifeAssertions;	// @synthesize=_lifeAssertions
@property(copy, nonatomic) NSString* replyText;	// @synthesize=_replyText
// declared property setter: -(void)setReplyText:(id)text;
// declared property getter: -(id)replyText;
// declared property setter: -(void)setActionKey:(id)key;
// declared property getter: -(id)actionKey;
// declared property setter: -(void)setDeliverToPublisher:(BOOL)publisher;
// declared property getter: -(BOOL)deliverToPublisher;
// declared property setter: -(void)setBulletinID:(id)anId;
// declared property getter: -(id)bulletinID;
// declared property setter: -(void)setSendBlock:(id)block;
// declared property getter: -(id)sendBlock;
// declared property setter: -(void)setLifeAssertions:(id)assertions;
// declared property getter: -(id)lifeAssertions;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)send;
-(void)dealloc;
@end

