/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "XPCProxyTarget.h"


@interface BBSystemStateProvider : XXUnknownSuperclass <XPCProxyTarget> {
@private
	id _serverProxy;
}
-(id)proxy:(id)proxy detailedSignatureForSelector:(SEL)selector;
-(void)noteChangeOfState:(unsigned)state newValue:(BOOL)value;
-(void)noteOccurrenceOfEvent:(unsigned)event;
-(void)dealloc;
-(id)init;
@end

