/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import "VSRecognitionRecognizeAction.h"

@class NSString, NSMutableDictionary;

@interface VSRecognitionDisambiguateAction : VSRecognitionRecognizeAction {
	NSString* _repeatedSpokenFeedbackString;
	NSString* _sequenceTag;
	NSMutableDictionary* _knownValues;
	NSMutableDictionary* _knownPhoneticValues;
	NSMutableDictionary* _ambiguousValues;
	NSMutableDictionary* _ambiguousPhoneticValues;
	void* _context;
}
@property(retain) NSString* sequenceTag;	// converted property
@property(retain) NSString* repeatedSpokenFeedbackString;	// converted property
-(id)_actionForEmptyResults;
-(VSRecognitionRef)_createRecognitionInstanceWithCallbacks:(XXStruct__Vsh7C*)callbacks info:(void*)info;
-(VSRecognitionDisambiguationContextRef)_disambiguationContext;
-(void)setKeywords:(id)keywords;
-(BOOL)_keywordIndexChanged;
-(id)_keywords;
-(void)setAmbiguousValues:(id)values phoneticValues:(id)values2 forClassIdentifier:(id)classIdentifier;
-(id)ambiguousValuesForClassIdentifier:(id)classIdentifier;
-(void)setKnownValues:(id)values phoneticValues:(id)values2 forClassIdentifier:(id)classIdentifier;
-(id)knownValuesForClassIdentifier:(id)classIdentifier;
-(void)setKnownValue:(id)value phoneticValue:(id)value2 forClassIdentifier:(id)classIdentifier;
-(id)knownValueForClassIdentifier:(id)classIdentifier;
// converted property setter: -(void)setSequenceTag:(id)tag;
// converted property getter: -(id)sequenceTag;
// converted property getter: -(id)repeatedSpokenFeedbackString;
// converted property setter: -(void)setRepeatedSpokenFeedbackString:(id)string;
-(int)completionType;
-(void)dealloc;
@end

