/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BBBulletin;

@interface AFBulletin : XXUnknownSuperclass {
@private
	BBBulletin* _bulletin;
	BOOL _read;
}
@property(retain, nonatomic) BBBulletin* bulletin;	// @synthesize=_bulletin
@property(assign, nonatomic, getter=isRead) BOOL read;	// @synthesize=_read
// declared property setter: -(void)setRead:(BOOL)read;
// declared property getter: -(BOOL)isRead;
// declared property setter: -(void)setBulletin:(id)bulletin;
// declared property getter: -(id)bulletin;
-(void).cxx_destruct;
-(id)dictionaryRepresentation;
@end

