/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "Symbolication-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class VMUClassInfoMap, VMUNonOverlappingRangeArray, NSHashTable, NSMutableSet;

@interface VMUObjectIdentifier : XXUnknownSuperclass {
	unsigned _task;
	CSTypeRef _symbolicator;
	id _memoryReader;
	VMUClassInfoMap* _isaToClassInfo;
	VMUClassInfoMap* _cfTypeIDtoClassInfo;
	NSHashTable* _objcRuntimeMallocBlocksHash;
	NSMutableSet* _objcRuntimeMallocBlocks;
	unsigned _cfTypeCount;
	unsigned _objcClassCount;
	unsigned _cPlusPlusClassCount;
	NSHashTable* _invalidPointers;
	VMUNonOverlappingRangeArray* _targetProcessVMranges;
	int peeksAtRemoteObjectIsa;
}
@property(readonly, retain) NSHashTable* objcRuntimeMallocBlocksHash;	// converted property
@property(readonly, retain) NSMutableSet* objcRuntimeMallocBlocks;	// converted property
-(VMURange)vmRegionRangeForAddress:(unsigned long long)address;
-(void)findObjCclasses;
-(void)_addobjc_opt_ro_classesForOffsets:(objc_classheader_t*)offsets count:(unsigned)count classOptAddress:(unsigned long long)address;
-(void)findCFTypes;
-(id)classInfoForObjectWithRange:(VMURange)range;
-(id)nullClassInfo;
-(id)_classInfoForObject:(unsigned long long)object;
-(id)classInfoForObject:(unsigned long long)object;
-(id)classInfoForCFType:(CFRuntimeBase*)cftype;
-(id)classInfoForIsaPointer:(unsigned)isaPointer;
-(BOOL)isValidRemotePointer:(unsigned long long)pointer;
// converted property getter: -(id)objcRuntimeMallocBlocks;
// converted property getter: -(id)objcRuntimeMallocBlocksHash;
-(unsigned)CPlusPlusClassCount;
-(unsigned)ObjCclassCount;
-(unsigned)CFTypeCount;
-(void)dealloc;
-(id)initWithTask:(unsigned)task symbolicator:(id)symbolicator;
-(id)initWithTask:(unsigned)task;
@end

