/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, AVController, NSDictionary, NSString;
@protocol CNFAudioDeviceControllerProtocol;

@interface CNFAudioDeviceController : XXUnknownSuperclass {
	id<CNFAudioDeviceControllerProtocol> _delegate;
	AVController* _avController;
	NSDictionary* _pickedRoute;
	NSArray* _pickableRoutes;
	NSString* _currentAudioRoute;
}
@property(retain, nonatomic) NSString* currentAudioRoute;	// @synthesize=_currentAudioRoute
// declared property setter: -(void)setCurrentAudioRoute:(id)route;
// declared property getter: -(id)currentAudioRoute;
-(void)_registerForAVControllerNotifications;
-(void)_pickableRoutesChanged;
-(void)_mediaServerDied;
-(BOOL)_routeIsAirTunes:(id)tunes;
-(BOOL)_routeIsReceiver:(id)receiver;
-(BOOL)_routeIsHandset:(id)handset;
-(BOOL)_routeIsSpeaker:(id)speaker;
-(BOOL)_pickRoute:(id)route;
-(id)_pickableRoutes;
-(id)_pickedRoute;
-(BOOL)isUsingBlueToothLEA;
-(BOOL)isAirPlayMirroring;
-(void)pickRouteAtIndex:(unsigned)index;
-(id)routeNameAtIndex:(unsigned)index isPicked:(BOOL*)picked;
-(BOOL)audioCategoryIsTTY;
-(BOOL)receiverRouteIsPicked;
-(BOOL)speakerRouteIsPicked;
-(void)clearCachedRoutes;
-(void)restorePickedRoute;
-(BOOL)pickRouteWithUID:(id)uid;
-(BOOL)pickHandsetRoute;
-(BOOL)pickSpeakerRoute;
-(int)numberOfAudioRoutes;
-(BOOL)routeOtherThanHandsetAndSpeakerIsAvailable;
-(BOOL)routeOtherThanHandsetIsAvailable;
-(BOOL)auxiliaryAudioRoutesAvailable;
-(void)setDelegate:(id)delegate;
-(void)invalidateAVController;
-(void)setAVController:(id)controller;
-(void)dealloc;
@end

