/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CNFInternalSettingsUtilities : XXUnknownSuperclass {
}
+(void)setIDSEnvironment:(id)environment;
+(id)IDSEnvironment;
+(void)setCurrentInternalSettingsBundle:(id)bundle;
+(id)currentInternalSettingsBundle;
+(void)signOutAllAccounts;
+(void)nukeKeychain;
+(void)killEverything;
+(void)killMediaServerd;
+(void)syncImagentLogSettings;
+(void)killImavagent;
+(void)killImagent;
+(void)setViceroyLoggingEnabled:(BOOL)enabled;
+(BOOL)isViceroyLoggingEnabled;
@end

