/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "MCStateOperation.h"

@class NSString;

@interface MCStateOperationStringSet : MCStateOperation {
@private
	NSString* _string;
}
@property(copy) NSString* string;	// @synthesize=_string
+(id)stateOperationForTargetPlugObjectID:(id)targetPlugObjectID withStateKey:(id)stateKey andString:(id)string;
// declared property setter: -(void)setString:(id)string;
// declared property getter: -(id)string;
-(id)description;
-(void)_copySelfToSnapshot:(id)snapshot;
-(id)imprint;
-(void)demolish;
-(id)initWithImprint:(id)imprint;
@end

