/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "MCAction.h"

@class NSString;

@interface MCStateOperation : MCAction {
@private
	NSString* _stateKey;
}
@property(assign, nonatomic) BOOL recordsTime;
@property(assign, nonatomic) BOOL alwaysNotifies;
@property(copy) NSString* stateKey;	// @synthesize=_stateKey
+(id)stateOperationForTargetPlugObjectID:(id)targetPlugObjectID withStateKey:(id)stateKey;
// declared property setter: -(void)setStateKey:(id)key;
// declared property getter: -(id)stateKey;
-(id)description;
-(void)_copySelfToSnapshot:(id)snapshot;
// declared property setter: -(void)setRecordsTime:(BOOL)time;
// declared property getter: -(BOOL)recordsTime;
// declared property setter: -(void)setAlwaysNotifies:(BOOL)notifies;
// declared property getter: -(BOOL)alwaysNotifies;
-(id)imprint;
-(void)demolish;
-(id)initWithImprint:(id)imprint;
@end

