/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"
#import "NSCopying.h"
#import "iLifeSlideshow-Structs.h"

@class MCMontage, NSMutableDictionary, NSMutableArray, NSObject, MCPlug, MPPlaylistInternal, MCAudioPlaylist;
@protocol MPAudioSupport;

@interface MPAudioPlaylist : XXUnknownSuperclass <NSCopying, NSCoding> {
@private
	NSMutableArray* _songs;
	MCAudioPlaylist* _audioPlaylist;
	MCPlug* _plug;
	NSObject<MPAudioSupport>* _parentObject;
	MCMontage* _montage;
	NSMutableDictionary* _attributes;
	MPPlaylistInternal* _internal;
}
@property(assign) float duckLevel;	// @dynamic
@property(assign) double duckOutDuration;	// @dynamic
@property(assign) double duckInDuration;	// @dynamic
@property(assign) double fadeOutDuration;	// @dynamic
@property(assign) double fadeInDuration;	// @dynamic
@property(assign) double duration;	// converted property
@property(retain) id parentObject;	// converted property
@property(retain) MCAudioPlaylist* audioPlaylist;	// converted property
@property(retain) MCMontage* montage;	// converted property
@property(readonly, retain) NSMutableArray* songs;	// converted property
+(id)audioPlaylist;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
// declared property setter: -(void)setDuckLevel:(float)level;
// declared property getter: -(float)duckLevel;
// declared property setter: -(void)setDuckOutDuration:(double)duration;
// declared property getter: -(double)duckOutDuration;
// declared property setter: -(void)setDuckInDuration:(double)duration;
// declared property getter: -(double)duckInDuration;
// declared property setter: -(void)setFadeOutDuration:(double)duration;
// declared property getter: -(double)fadeOutDuration;
// declared property setter: -(void)setFadeInDuration:(double)duration;
// declared property getter: -(double)fadeInDuration;
// converted property getter: -(double)duration;
// converted property getter: -(id)parentObject;
-(void)moveSongsFromIndices:(id)indices toIndex:(int)index;
-(void)removeAllSongs;
-(void)removeSongsAtIndices:(id)indices;
-(void)insertSongs:(id)songs atIndex:(int)index;
-(void)addSongs:(id)songs;
-(void)addSong:(id)song;
// converted property getter: -(id)songs;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)finalize;
-(id)init;
// converted property getter: -(id)audioPlaylist;
-(id)parentDocument;
// converted property setter: -(void)setDuration:(double)duration;
// converted property setter: -(void)setParentObject:(id)object;
-(void)setPlug:(id)plug;
// converted property setter: -(void)setAudioPlaylist:(id)playlist;
// converted property setter: -(void)setMontage:(id)montage;
// converted property getter: -(id)montage;
-(void)cleanup;
-(void)copySongs:(id)songs;
-(void)copyStruct:(id)aStruct;
-(void)replaceObjectInSongsAtIndex:(int)index withObject:(id)object;
-(void)removeObjectFromSongsAtIndex:(int)index;
-(void)insertObject:(id)object inSongsAtIndex:(int)index;
-(id)objectInSongsAtIndex:(int)index;
-(int)countOfSongs;
@end

