/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MPPlaylistInternal : XXUnknownSuperclass {
	double duration;
	double fadeInDuration;
	double fadeOutDuration;
	double duckInDuration;
	double duckOutDuration;
	float duckLevel;
}
@property(assign, nonatomic) float duckLevel;	// @synthesize
@property(assign, nonatomic) double duckOutDuration;	// @synthesize
@property(assign, nonatomic) double duckInDuration;	// @synthesize
@property(assign, nonatomic) double fadeOutDuration;	// @synthesize
@property(assign, nonatomic) double fadeInDuration;	// @synthesize
@property(assign, nonatomic) double duration;	// @synthesize
// declared property setter: -(void)setDuckLevel:(float)level;
// declared property getter: -(float)duckLevel;
// declared property setter: -(void)setDuckOutDuration:(double)duration;
// declared property getter: -(double)duckOutDuration;
// declared property setter: -(void)setDuckInDuration:(double)duration;
// declared property getter: -(double)duckInDuration;
// declared property setter: -(void)setFadeOutDuration:(double)duration;
// declared property getter: -(double)fadeOutDuration;
// declared property setter: -(void)setFadeInDuration:(double)duration;
// declared property getter: -(double)fadeInDuration;
// declared property setter: -(void)setDuration:(double)duration;
// declared property getter: -(double)duration;
@end

