/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "MCAnimationPathPhysics.h"


@interface MRAnimationPathPhysics : MCAnimationPathPhysics {
	float mBaseValue;
	float mDeltaValue;
	float mVelocity;
	double mTime;
}
@property(assign, nonatomic) float velocity;	// @synthesize=mVelocity
@property(assign, nonatomic) float baseValue;	// @synthesize=mBaseValue
// declared property setter: -(void)setVelocity:(float)velocity;
// declared property getter: -(float)velocity;
// declared property setter: -(void)setBaseValue:(float)value;
// declared property getter: -(float)baseValue;
-(float)computeValueForTime:(double)time withContext:(id)context;
-(id)initWithMCAnimationPath:(id)mcanimationPath;
@end

