/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSDictionary, NSString;

@interface MRContextState : XXUnknownSuperclass {
	float modelViewMatrix[16];
	float textureMatrix[4][16];
	float normal[3];
	unsigned currentVBO;
	int currentVBOStride;
	int inSpriteCoordinatesStride;
	int textureCoordinatesStride[4];
	const float* vertex2DPointer;
	const float* vertex3DPointer;
	const float* colorsPointer;
	const float* normalsPointer;
	float* textureCoordinatesPointer[4];
	const float* inSpriteCoordinatesPointer;
	BOOL vertexArrayIsEnabled;
	BOOL foreColorArrayIsEnabled;
	BOOL normalArrayIsEnabled;
	BOOL textureCoordinatesArrayIsEnabled[4];
	BOOL inSpriteCoordinatesArrayIsEnabled;
	float foreColor[4];
	float backColor[4];
	unsigned textureTargetOnUnit[4];
	unsigned textureNameOnUnit[4];
	double textureTimestampOnUnit[4];
	BOOL blendingIsEnabled;
	int blendingType;
	BOOL cullingIsEnabled;
	BOOL cullFrontfacing;
	BOOL depthTestIsEnabled;
@private
	NSString* _shaderID;
	NSDictionary* _shaderArguments;
	NSMutableDictionary* _vertexAttributes;
	NSMutableDictionary* _temporaryUniforms;
}
@property(readonly, assign) NSMutableDictionary* temporaryUniforms;	// @synthesize=_temporaryUniforms
@property(readonly, assign) NSMutableDictionary* vertexAttributes;	// @synthesize=_vertexAttributes
@property(copy) NSDictionary* shaderArguments;	// @synthesize=_shaderArguments
@property(copy) NSString* shaderID;	// @synthesize=_shaderID
// declared property getter: -(id)temporaryUniforms;
// declared property getter: -(id)vertexAttributes;
// declared property setter: -(void)setShaderArguments:(id)arguments;
// declared property getter: -(id)shaderArguments;
// declared property setter: -(void)setShaderID:(id)anId;
// declared property getter: -(id)shaderID;
-(void)dealloc;
-(id)init;
@end

