/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MPText, MRTextRenderer, MRMarimbaLayer;

@interface MRMarimbaLayoutManager : XXUnknownSuperclass {
@private
	MRTextRenderer* _textRenderer;
	MRMarimbaLayer* _marimbaLayer;
	MPText* _text;
}
@property(retain, nonatomic) MPText* text;	// @synthesize=_text
@property(retain, nonatomic) MRMarimbaLayer* marimbaLayer;	// @synthesize=_marimbaLayer
@property(readonly, retain) MRTextRenderer* textRenderer;	// converted property
// declared property setter: -(void)setText:(id)text;
// declared property getter: -(id)text;
// declared property setter: -(void)setMarimbaLayer:(id)layer;
// declared property getter: -(id)marimbaLayer;
-(CGPoint)shadowOffset;
-(CGRect)currentRectForEditedText;
-(id)_renderer;
-(void)updateWithString:(id)string;
-(int)lineCount;
// converted property getter: -(id)textRenderer;
-(void)dealloc;
-(id)init;
@end

