/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

#import "AppStoreUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SSDownloadManagerObserver.h"

@class SUItem, UIImageView, SSDownloadManager, _UIReflectingView, SUItemOfferButton, SUUserRatingView, UIImage, NSString;

@interface ASApplicationPageHeaderView : XXUnknownSuperclass <SSDownloadManagerObserver> {
	SSDownloadManager* _downloadManager;
	SUItem* _item;
	UIImage* _image;
	NSString* _purchaseConfirmationTitle;
	UIImageView* _imageView;
	_UIReflectingView* _imageViewReflector;
	SUItemOfferButton* _offerButton;
	SUUserRatingView* _ratingsView;
	unsigned _style;
	BOOL _isPurchasing;
	float _titleFontSize;
	CGSize _titleSize;
	unsigned _titleWraps : 1;
}
+(id)placeholderImage;
+(id)backdropColor;
-(id)_subtitleColor;
-(void)_showPurchaseConfirmation;
-(BOOL)_shouldDisplayAsInstalled;
-(void)_reloadTitleSizeForBounds:(CGRect)bounds;
-(void)_reloadRatingsView;
-(void)_reloadOfferButton:(BOOL)button;
-(void)_reloadImageView;
-(CGRect)_ratingsViewFrame;
-(id)_purchaseConfirmationTitle;
-(CGRect)_offerButtonFrame;
-(id)_itemOffer;
-(BOOL)_isApplicationUpdate;
-(void)_hidePurchaseConfirmation;
-(void)_drawUpdateTitlesInBounds:(CGRect)bounds;
-(void)_softwareMapChangedNotification:(id)notification;
-(void)_purchasesChangedNotification:(id)notification;
-(void)_applicationWillEnterForegroundNotification:(id)_application;
-(void)_applicationDidEnterBackgroundNotification:(id)_application;
-(void)downloadManagerDownloadsDidChange:(id)downloadManagerDownloads;
-(void)_touchCaptureAction:(id)action;
-(void)_offerButtonAction:(id)action;
-(void)_delayedPurchaseItem;
-(void)willMoveToWindow:(id)window;
-(void)sizeToFit;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)setPurchaseConfirmationTitle:(id)title;
-(void)setStyle:(unsigned)style;
-(void)setItemImage:(id)image;
-(void)setItem:(id)item;
-(void)reloadView;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

