/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

#import "ISURLOperationDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ASUpdatePageView, SUStructuredPage;

@interface ASUpdatePageViewController : XXUnknownSuperclass <ISURLOperationDelegate> {
	SUStructuredPage* _page;
	ASUpdatePageView* _pageView;
}
-(void)_updatePageView;
-(id)_newApplicationIconOperationForItemImage:(id)itemImage;
-(id)_itemArtworkImage;
-(id)_applicationIconURL;
-(id)_applicationIcon;
-(id)_activeItem;
-(void)operation:(id)operation finishedWithOutput:(id)output;
-(void)viewDidAppear:(BOOL)view;
-(void)reloadWithStorePage:(id)storePage forURL:(id)url;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

