/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDKeyedObject.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class OADGraphicProperties, CHDTitle, EDResources;

__attribute__((visibility("hidden")))
@interface CHDAxis : XXUnknownSuperclass <EDKeyedObject> {
@private
	bool mReverseOrder;
	bool mSecondary;
	bool mDateTimeFormattingFlag;
	bool mLineVisible;
	bool mDeleted;
	bool mAutoMinimumValue;
	bool mAutoMaximumValue;
	bool mAutoCrossValue;
	bool mContentFormatDerived;
	int mAxisId;
	unsigned mContentFormatId;
	int mFontIndex;
	double mScalingMaximum;
	double mScalingMinimum;
	int mOrientation;
	double mCrossAxisId;
	double mCrossesAt;
	int mMajorTickMark;
	int mMinorTickMark;
	int mAxisPosition;
	int mAxisType;
	int mTickLabelPosition;
	CHDTitle* mTitle;
	OADGraphicProperties* mMinorGridLinesGraphicProperties;
	OADGraphicProperties* mMajorGridLinesGraphicProperties;
	OADGraphicProperties* mAxisGraphicProperties;
	int mCrossBetween;
	int mCrosses;
	double mTickLabelRotation;
	bool mIsAutoRotation;
	int mTickLabelColorIndex;
	EDResources* mResources;
}
@property(assign, getter=isTickLabelAutoRotation) bool tickLabelAutoRotation;	// converted property
@property(assign) double tickLabelRotationAngle;	// converted property
@property(assign, getter=isDateTimeFormattingFlag) bool dateTimeFormattingFlag;	// converted property
@property(assign) int crosses;	// converted property
@property(assign) int crossBetween;	// converted property
@property(retain) id axisGraphicProperties;	// converted property
@property(retain) id majorGridLinesGraphicProperties;	// converted property
@property(retain) id minorGridLinesGraphicProperties;	// converted property
@property(retain) id title;	// converted property
@property(assign) int tickLabelPosition;	// converted property
@property(assign) int axisType;	// converted property
@property(assign) int axisPosition;	// converted property
@property(assign) int minorTickMark;	// converted property
@property(assign) int majorTickMark;	// converted property
@property(assign) double crossesAt;	// converted property
@property(assign) double crossAxisId;	// converted property
@property(assign) int orientation;	// converted property
@property(assign) double scalingMinimum;	// converted property
@property(assign) double scalingMaximum;	// converted property
@property(assign) bool isContentFormatDerivedFromDataPoints;	// converted property
@property(retain) id contentFormat;	// converted property
@property(retain) id font;	// converted property
@property(assign, getter=isDeleted) bool deleted;	// converted property
@property(assign, getter=isLineVisible) bool lineVisible;	// converted property
@property(assign, getter=isSecondary) bool secondary;	// converted property
@property(assign, getter=isReverseOrder) bool reverseOrder;	// converted property
@property(assign) int axisId;	// converted property
@property(assign) int tickLabelColorIndex;	// converted property
@property(assign) int fontIndex;	// converted property
@property(assign) unsigned contentFormatId;	// converted property
-(void)adjustAxisPositionForHorizontalChart;
// converted property setter: -(void)setTickLabelAutoRotation:(bool)rotation;
// converted property getter: -(bool)isTickLabelAutoRotation;
// converted property setter: -(void)setTickLabelRotationAngle:(double)angle;
// converted property getter: -(double)tickLabelRotationAngle;
// converted property setter: -(void)setDateTimeFormattingFlag:(bool)flag;
// converted property getter: -(bool)isDateTimeFormattingFlag;
-(bool)isDate;
-(int)key;
// converted property setter: -(void)setCrosses:(int)crosses;
// converted property getter: -(int)crosses;
// converted property setter: -(void)setCrossBetween:(int)between;
// converted property getter: -(int)crossBetween;
// converted property setter: -(void)setAxisGraphicProperties:(id)properties;
// converted property getter: -(id)axisGraphicProperties;
// converted property setter: -(void)setMajorGridLinesGraphicProperties:(id)properties;
// converted property getter: -(id)majorGridLinesGraphicProperties;
// converted property setter: -(void)setMinorGridLinesGraphicProperties:(id)properties;
// converted property getter: -(id)minorGridLinesGraphicProperties;
// converted property setter: -(void)setTitle:(id)title;
// converted property getter: -(id)title;
-(bool)isTickLabelVisible;
// converted property setter: -(void)setTickLabelPosition:(int)position;
// converted property getter: -(int)tickLabelPosition;
// converted property setter: -(void)setAxisType:(int)type;
// converted property getter: -(int)axisType;
// converted property setter: -(void)setAxisPosition:(int)position;
// converted property getter: -(int)axisPosition;
// converted property setter: -(void)setMinorTickMark:(int)mark;
// converted property getter: -(int)minorTickMark;
// converted property setter: -(void)setMajorTickMark:(int)mark;
// converted property getter: -(int)majorTickMark;
// converted property setter: -(void)setCrossesAt:(double)at;
// converted property getter: -(double)crossesAt;
// converted property setter: -(void)setCrossAxisId:(double)anId;
// converted property getter: -(double)crossAxisId;
// converted property setter: -(void)setOrientation:(int)orientation;
// converted property getter: -(int)orientation;
// converted property setter: -(void)setScalingMinimum:(double)minimum;
// converted property getter: -(double)scalingMinimum;
// converted property setter: -(void)setScalingMaximum:(double)maximum;
// converted property getter: -(double)scalingMaximum;
// converted property setter: -(void)setIsContentFormatDerivedFromDataPoints:(bool)dataPoints;
// converted property getter: -(bool)isContentFormatDerivedFromDataPoints;
// converted property setter: -(void)setContentFormat:(id)format;
-(id)defaultDateTimeContentFormat;
// converted property getter: -(id)contentFormat;
// converted property setter: -(void)setFont:(id)font;
// converted property getter: -(id)font;
-(bool)isHorizontalPosition;
-(bool)isAutoCrossValue;
-(bool)isAutoMaximumValue;
-(bool)isAutoMinimumValue;
// converted property setter: -(void)setDeleted:(bool)deleted;
// converted property getter: -(bool)isDeleted;
// converted property setter: -(void)setLineVisible:(bool)visible;
// converted property getter: -(bool)isLineVisible;
// converted property setter: -(void)setSecondary:(bool)secondary;
// converted property getter: -(bool)isSecondary;
// converted property setter: -(void)setReverseOrder:(bool)order;
// converted property getter: -(bool)isReverseOrder;
// converted property setter: -(void)setAxisId:(int)anId;
// converted property getter: -(int)axisId;
-(void)dealloc;
-(id)initWithResources:(id)resources;
-(id)tickLabelColor;
// converted property setter: -(void)setTickLabelColorIndex:(int)index;
// converted property getter: -(int)tickLabelColorIndex;
// converted property setter: -(void)setFontIndex:(int)index;
// converted property getter: -(int)fontIndex;
// converted property setter: -(void)setContentFormatId:(unsigned)anId;
// converted property getter: -(unsigned)contentFormatId;
@end

