/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDProcessor.h"


__attribute__((visibility("hidden")))
@interface CHPChangeDirection : EDProcessor {
}
-(void)changeChartDirection:(id)direction sheet:(id)sheet;
-(void)applyProcessorToObject:(id)object sheet:(id)sheet;
-(bool)isObjectSupported:(id)supported;
-(void)cleanUpOldSeriesCollection:(id)collection;
-(void)addDataValue:(id)value to:(id)to withIndex:(int)index;
-(id)getGraphicPropertiesForSeriesWithIndex:(int)index fromCollection:(id)collection isVaryColors:(bool)colors forChart:(id)chart;
-(void)mapSeriesValues:(id)values to:(id)to forIndex:(unsigned)index byRow:(bool)row forChart:(id)chart;
-(void)mapSeriesCollection:(id)collection from:(id)from forChart:(id)chart;
-(id)getSeriesCollectionForOrthogonalDirection:(id)orthogonalDirection forChart:(id)chart;
-(id)createNewSeriesCollectionForOrthogonalDirection:(id)orthogonalDirection forChart:(id)chart;
@end

