/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CHXCategoryAxis : XXUnknownSuperclass {
}
+(id)chdAxisFromXmlAxisElement:(xmlNode*)xmlAxisElement state:(id)state;
+(int)chdLabelAlignFromXmlLabelAlignElement:(xmlNode*)xmlLabelAlignElement;
@end

