/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSData;

__attribute__((visibility("hidden")))
@interface CPNamedData : XXUnknownSuperclass {
@private
	NSData* mData;
	NSString* mName;
}
@property(readonly, assign, nonatomic) NSString* name;	// @synthesize=mName
@property(readonly, assign, nonatomic) NSData* data;	// @synthesize=mData
+(id)namedDataWithData:(id)data named:(id)named;
// declared property getter: -(id)name;
// declared property getter: -(id)data;
-(void)dealloc;
-(id)initWithData:(id)data named:(id)named;
@end

