/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "EBState.h"

@class OABReaderState, ECColumnWidthConvertor;

__attribute__((visibility("hidden")))
@interface EBReaderState : EBState {
@private
	XlBinaryReader* mXlReader;
	XlSheetInfoTable* mXlSheetInfoTable;
	ECColumnWidthConvertor* mColumnWidthConvertor;
	unsigned mTotalCellsWithContentCount;
	unsigned mTotalCellsWithFormulaCount;
	XlEshObjectFactory* mXlEshObjectFactory;
	OABReaderState* mOAState;
	BOOL mImportCSV;
}
@property(assign, nonatomic) BOOL importCSV;	// @synthesize=mImportCSV
// declared property setter: -(void)setImportCSV:(BOOL)csv;
// declared property getter: -(BOOL)importCSV;
-(void)reportWarning:(CPTaggedMessageStructure*)warning;
-(id)oaState;
-(void)incrementCellsWithFormulaCount;
-(void)incrementCellsWithContentCount;
-(unsigned)cellsWithContentCount;
-(id)columnWidthConvertor;
-(XlSheetInfoTable*)xlSheetInfoTable;
-(void)readGlobalXlObjects;
-(XlBinaryReader*)xlReader;
-(void)resumeReading;
-(void)pauseReading;
-(void)dealloc;
-(id)initWithXlReader:(XlBinaryReader*)xlReader cancelDelegate:(id)delegate tracing:(id)tracing;
@end

