/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EBReaderState, EDSheet;

__attribute__((visibility("hidden")))
@interface EBReaderSheetState : XXUnknownSuperclass {
@private
	EBReaderState* mReaderState;
	EDSheet* mEDSheet;
	CFDictionaryRef mSharedFormulas;
	unsigned mChartIndex;
}
-(void)reportWorksheetWarning:(CPTaggedMessageStructure*)warning;
-(unsigned)nextChartIndex;
-(void)setSharedFormulaIndex:(unsigned)index forRowCol:(int)rowCol;
-(unsigned)sharedFormulaIndexForRowCol:(int)rowCol;
-(void)setEDSheet:(id)sheet;
-(id)edSheet;
-(id)resources;
-(id)workbook;
-(XlBinaryReader*)xlReader;
-(id)readerState;
-(void)dealloc;
-(id)initWithReaderState:(id)readerState;
@end

