/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "EDSheet.h"

@class CHDChart;

__attribute__((visibility("hidden")))
@interface EDChartSheet : EDSheet {
@private
	CHDChart* mMainChart;
	bool mIsBoundsSet;
	CGRect mBounds;
}
@property(assign) CGRect bounds;	// converted property
@property(retain) id mainChart;	// converted property
-(id).cxx_construct;
-(void)addDrawable:(id)drawable;
// converted property setter: -(void)setBounds:(CGRect)bounds;
// converted property getter: -(CGRect)bounds;
-(bool)areBoundsSet;
// converted property setter: -(void)setMainChart:(id)chart;
// converted property getter: -(id)mainChart;
-(void)teardown;
@end

