/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDKeyedCollection.h"


__attribute__((visibility("hidden")))
@interface EDContentFormatsCollection : EDKeyedCollection {
@private
	unsigned mNextContentFormatId;
}
-(unsigned)addOrEquivalentObject:(id)object;
-(unsigned)addObject:(id)object;
-(id)init;
-(bool)isOverwritingKeyOK;
-(void)addDefaultWithNSString:(id)nsstring formatId:(unsigned)anId;
-(void)setupDefaults;
@end

