/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDKeyedObject.h"
#import "NSCopying.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EDString;

__attribute__((visibility("hidden")))
@interface EDContentFormat : XXUnknownSuperclass <EDKeyedObject, NSCopying> {
@private
	EDString* mFormatString;
	unsigned mFormatId;
	bool mBuiltIn;
	bool mReferenced;
}
@property(assign) bool referenced;	// converted property
@property(assign) unsigned formatId;	// converted property
+(id)contentFormatWithFormatString:(id)formatString;
+(id)contentFormatWithFormatString:(id)formatString formatId:(unsigned)anId;
+(id)contentFormatWithNSString:(id)nsstring formatId:(unsigned)anId builtIn:(bool)anIn;
// converted property getter: -(bool)referenced;
-(bool)builtIn;
// converted property getter: -(unsigned)formatId;
-(id)formatString;
-(int)key;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(BOOL)isEqualToContentFormat:(id)contentFormat;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)init;
// converted property setter: -(void)setReferenced:(bool)referenced;
// converted property setter: -(void)setFormatId:(unsigned)anId;
@end

