/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDImmutableObject.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EDResources, EDCollection, NSString;

__attribute__((visibility("hidden")))
@interface EDPhoneticInfo : XXUnknownSuperclass <EDImmutableObject> {
@private
	EDResources* mResources;
	unsigned mFontIndex;
	NSString* mString;
	int mType;
	int mAlign;
	EDCollection* mRuns;
	bool mDoNotModify;
}
@property(retain) id font;	// converted property
@property(retain) id string;	// converted property
@property(assign) int align;	// converted property
@property(assign) int type;	// converted property
@property(assign) unsigned fontIndex;	// converted property
+(id)phoneticInfoWithResources:(id)resources;
-(void)setDoNotModify:(bool)modify;
-(id)runs;
// converted property setter: -(void)setFont:(id)font;
// converted property getter: -(id)font;
// converted property setter: -(void)setString:(id)string;
// converted property getter: -(id)string;
// converted property setter: -(void)setAlign:(int)align;
// converted property getter: -(int)align;
// converted property setter: -(void)setType:(int)type;
// converted property getter: -(int)type;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(BOOL)isEqualToEDPhoneticInfo:(id)edphoneticInfo;
-(void)dealloc;
-(id)initWithResources:(id)resources;
// converted property setter: -(void)setFontIndex:(unsigned)index;
// converted property getter: -(unsigned)fontIndex;
@end

