/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface EDPivotDataField : XXUnknownSuperclass {
@private
	int mBaseField;
	unsigned mBaseItem;
	unsigned mFieldId;
	unsigned mNumFmtId;
	NSString* mName;
	int mFormat;
}
@property(assign) int showDataAs;	// converted property
@property(retain) id name;	// converted property
@property(assign) unsigned numFmtId;	// converted property
@property(assign) unsigned fieldId;	// converted property
@property(assign) unsigned baseItem;	// converted property
@property(assign) int baseField;	// converted property
+(id)pivotDataField;
// converted property setter: -(void)setShowDataAs:(int)as;
// converted property getter: -(int)showDataAs;
// converted property setter: -(void)setName:(id)name;
// converted property getter: -(id)name;
// converted property setter: -(void)setNumFmtId:(unsigned)anId;
// converted property getter: -(unsigned)numFmtId;
// converted property setter: -(void)setFieldId:(unsigned)anId;
// converted property getter: -(unsigned)fieldId;
// converted property setter: -(void)setBaseItem:(unsigned)item;
// converted property getter: -(unsigned)baseItem;
// converted property setter: -(void)setBaseField:(int)field;
// converted property getter: -(int)baseField;
-(void)dealloc;
-(id)init;
@end

