/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDCollection.h"


__attribute__((visibility("hidden")))
@interface EDReferenceCollection : EDCollection {
@private
	bool mCoalesce;
}
+(id)coalesceCollection;
+(id)noCoalesceCollection;
-(id)reverseReferencesByRow:(bool)row;
-(id)referenceToCellWithIndex:(unsigned)index byRow:(bool)row;
-(unsigned)countOfCellsBeingReferenced;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(unsigned)addObject:(id)object;
-(id)initWihNoCoalesce;
-(id)init;
-(bool)coalesceReferenceAtIndex1:(int)index1 index2:(int)a2;
-(void)coalesce;
@end

