/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "TSUFlushable.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EDWorksheet, NSRecursiveLock, EDCollection, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface EDRowBlocks : XXUnknownSuperclass <TSUFlushable> {
@private
	EDWorksheet* mWorksheet;
	NSMutableArray* mRowBlocks;
	EDCollection* mFormulas;
	unsigned mMaxPopulatedRow;
	unsigned mMaxPopulatedColumn;
	NSString* mFileName;
	int mLockCount;
	NSRecursiveLock* mSaveLoadLock;
}
-(id)formulas;
-(unsigned)maxPopulatedColumn;
-(unsigned)maxPopulatedRow;
-(EDCellHeader*)cellWithRowNumber:(unsigned)rowNumber columnNumber:(int)number;
-(id)rowBlockForRowNumber:(unsigned)rowNumber currentRowBlock:(id)block createIfNil:(bool)aNil;
-(id)rowBlockForRowNumber:(unsigned)rowNumber currentRowBlock:(id)block;
-(unsigned)indexOfRowBlockForRowNumber:(unsigned)rowNumber;
-(unsigned)expectedIndexOfRowBlockForRowNumber:(unsigned)rowNumber;
-(void)removeRowBlockAtIndex:(unsigned)index;
-(id)rowBlockAtIndex:(unsigned)index;
-(unsigned)rowBlockCount;
-(void)dealloc;
-(id)initWithWorksheet:(id)worksheet;
-(id)fileNameForPersistingRowBlocks;
-(bool)spaceForRowNumber:(unsigned)rowNumber rowBlock:(id)block;
-(void)flush;
-(void)save;
-(void)load;
-(void)unlock;
-(void)lock;
-(Class)classForFormulaType:(unsigned char)formulaType;
-(unsigned char)formulaTypeForFormula:(id)formula;
-(void)updateMaxPopulatedRow:(unsigned)row column:(unsigned)column;
@end

