/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "MFPEffect.h"


__attribute__((visibility("hidden")))
@interface MFPBrightnessContrastEffect : MFPEffect {
@private
	long mBrightness;
	long mContrast;
}
+(id)GUID;
-(id)initWithBrightness:(long)brightness contrast:(long)contrast;
@end

