/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSBezierPathStub : XXUnknownSuperclass <NSCopying> {
@private
	int _segmentCount;
	int _segmentMax;
	PATHSEGMENT* _head;
	int _lastSubpathIndex;
	int _elementCount;
	float _lineWidth;
	CGRect _controlPointBounds;
	float _miterLimit;
	float _flatness;
	float* _dashedLinePattern;
	unsigned _dashedLineCount;
	float _dashedLinePhase;
	void* _path;
	id _private[4];
	struct {
		unsigned _flags : 8;
		unsigned _pathState : 2;
		unsigned _unused : 22;
	} _bpFlags;
}
@property(assign) BOOL cachesBezierPath;	// converted property
@property(assign) float flatness;	// converted property
@property(assign) float miterLimit;	// converted property
@property(assign) unsigned windingRule;	// converted property
@property(assign) unsigned lineJoinStyle;	// converted property
@property(assign) unsigned lineCapStyle;	// converted property
@property(assign) float lineWidth;	// converted property
@property(readonly, assign) int elementCount;	// converted property
@property(readonly, assign) CGRect controlPointBounds;	// converted property
+(void)drawString:(id)string atPoint:(CGPoint)point withFontName:(id)fontName andHeight:(float)height color:(id)color alignToTop:(BOOL)top currentTransformStruct:(CGAffineTransform)aStruct;
+(float)defaultLineWidth;
+(void)setDefaultLineWidth:(float)width;
+(unsigned)defaultLineJoinStyle;
+(void)setDefaultLineJoinStyle:(unsigned)style;
+(unsigned)defaultLineCapStyle;
+(void)setDefaultLineCapStyle:(unsigned)style;
+(unsigned)defaultWindingRule;
+(void)setDefaultWindingRule:(unsigned)rule;
+(float)defaultFlatness;
+(void)setDefaultFlatness:(float)flatness;
+(float)defaultMiterLimit;
+(void)setDefaultMiterLimit:(float)limit;
+(void)drawPackedGlyphs:(const char*)glyphs atPoint:(CGPoint)point;
+(void)strokeLineFromPoint:(CGPoint)point toPoint:(CGPoint)point2;
+(void)clipRect:(CGRect)rect;
+(void)strokeRect:(CGRect)rect;
+(void)fillRect:(CGRect)rect;
+(id)bezierPathWithRoundedRect:(CGRect)roundedRect xRadius:(float)radius yRadius:(float)radius3;
+(id)bezierPathWithOvalInRect:(CGRect)rect;
+(id)bezierPathWithRect:(CGRect)rect;
+(id)bezierPath;
+(CGContextRef)currentCGContext;
+(void)setCurrentCGContext:(CGContextRef)context;
+(void)initialize;
+(float)lineWidth;
+(void)setLineWidth:(float)width;
+(unsigned)lineJoinStyle;
+(void)setLineJoinStyle:(unsigned)style;
+(unsigned)lineCapStyle;
+(void)setLineCapStyle:(unsigned)style;
+(unsigned)windingRule;
+(void)setWindingRule:(unsigned)rule;
+(float)flatness;
+(void)setFlatness:(float)flatness;
+(float)miterLimit;
+(void)setMiterLimit:(float)limit;
-(id).cxx_construct;
// converted property setter: -(void)setCachesBezierPath:(BOOL)path;
// converted property getter: -(BOOL)cachesBezierPath;
-(BOOL)isStrokeHitByPath:(id)path;
-(BOOL)isStrokeHitByRect:(CGRect)rect;
-(BOOL)isStrokeHitByPoint:(CGPoint)point;
-(BOOL)isHitByPath:(id)path;
-(BOOL)isHitByRect:(CGRect)rect;
-(BOOL)isHitByPoint:(CGPoint)point;
-(BOOL)containsPoint:(CGPoint)point;
-(int)_locationOfPoint:(CGPoint)point;
-(void)appendBezierPathWithRoundedRect:(CGRect)roundedRect xRadius:(float)radius yRadius:(float)radius3;
-(void)appendBezierPathWithArcFromPoint:(CGPoint)point toPoint:(CGPoint)point2 radius:(float)radius;
-(void)appendBezierPathWithArcWithCenter:(CGPoint)center radius:(float)radius startAngle:(float)angle endAngle:(float)angle4;
-(void)appendBezierPathWithArcWithCenter:(CGPoint)center radius:(float)radius startAngle:(float)angle endAngle:(float)angle4 clockwise:(BOOL)clockwise;
-(void)_appendArcSegmentWithCenter:(CGPoint)center radius:(double)radius angle1:(double)a1 angle2:(double)a2;
-(void)appendBezierPathWithOvalInRect:(CGRect)rect;
-(void)appendBezierPathWithPoints:(CGPoint*)points count:(int)count;
-(void)appendBezierPathWithRect:(CGRect)rect;
-(void)appendBezierPath:(id)path;
-(void)setAssociatedPoints:(CGPoint*)points atIndex:(int)index;
-(unsigned)elementAtIndex:(int)index associatedPoints:(CGPoint*)points;
-(int)_segmentIndexForElementIndex:(int)elementIndex;
-(unsigned)elementAtIndex:(int)index;
// converted property getter: -(int)elementCount;
-(CGRect)bounds;
// converted property getter: -(CGRect)controlPointBounds;
-(CGPoint)currentPoint;
-(BOOL)isEmpty;
-(void)transformUsingAffineTransform:(id)transform;
-(id)bezierPathByReversingPath;
-(id)_copyFlattenedPath;
-(id)bezierPathByFlatteningPath;
-(void)flattenIntoPath:(id)path;
-(void)subdivideBezierWithFlatness:(float)flatness startPoint:(CGPoint)point controlPoint1:(CGPoint)a1 controlPoint2:(CGPoint)a2 endPoint:(CGPoint)point5;
-(void)setClip;
-(void)addClip;
-(void)fill;
-(void)stroke;
-(void)_doPath;
-(void)getLineDash:(float*)dash count:(int*)count phase:(float*)phase;
-(void)setLineDash:(const float*)dash count:(int)count phase:(float)phase;
// converted property setter: -(void)setFlatness:(float)flatness;
// converted property getter: -(float)flatness;
// converted property setter: -(void)setMiterLimit:(float)limit;
// converted property getter: -(float)miterLimit;
// converted property setter: -(void)setWindingRule:(unsigned)rule;
// converted property getter: -(unsigned)windingRule;
// converted property setter: -(void)setLineJoinStyle:(unsigned)style;
// converted property getter: -(unsigned)lineJoinStyle;
// converted property setter: -(void)setLineCapStyle:(unsigned)style;
// converted property getter: -(unsigned)lineCapStyle;
// converted property setter: -(void)setLineWidth:(float)width;
// converted property getter: -(float)lineWidth;
-(void)relativeCurveToPoint:(CGPoint)point controlPoint1:(CGPoint)a1 controlPoint2:(CGPoint)a2;
-(void)relativeLineToPoint:(CGPoint)point;
-(void)relativeMoveToPoint:(CGPoint)point;
-(void)removeAllPoints;
-(void)closePath;
-(void)curveToPoint:(CGPoint)point controlPoint1:(CGPoint)a1 controlPoint2:(CGPoint)a2;
-(void)lineToPoint:(CGPoint)point;
-(void)moveToPoint:(CGPoint)point;
-(id)copyWithZone:(NSZone*)zone;
-(void)finalize;
-(void)dealloc;
-(id)init;
-(void)_doUserPathWithOp:(unsigned char)op inContext:(CGContextRef)context;
-(void)_deviceClosePath;
-(void)_deviceCurveToPoint:(CGPoint)point controlPoint1:(CGPoint)a1 controlPoint2:(CGPoint)a2;
-(void)_deviceLineToPoint:(CGPoint)point;
-(void)_deviceMoveToPoint:(CGPoint)point;
-(void)_addPathSegment:(int)segment point:(CGPoint)point;
-(id)description;
@end

