/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"
#import "OABPropertiesManager.h"


__attribute__((visibility("hidden")))
@interface OABDefaultsManager : XXUnknownSuperclass <OABPropertiesManager> {
}
-(BOOL)hidden;
-(BOOL)textPathStrikethrough;
-(BOOL)textPathSmallcaps;
-(BOOL)textPathUnderline;
-(BOOL)textPathItalic;
-(BOOL)textPathBold;
-(id)textPathFontFamily;
-(long)textPathFontSize;
-(int)textPathTextAlignment;
-(id)textPathUnicodeString;
-(BOOL)isTextPath;
-(BOOL)isShadowOK;
-(BOOL)isStrokeOK;
-(BOOL)isFillOK;
-(long)shadowSoftness;
-(long)shadowOffsetY;
-(long)shadowOffsetX;
-(long)shadowAlpha;
-(int)shadowType;
-(BOOL)isShadowed;
-(int)strokeEndArrowLength;
-(int)strokeEndArrowWidth;
-(int)strokeEndArrowType;
-(int)strokeStartArrowLength;
-(int)strokeStartArrowWidth;
-(int)strokeStartArrowType;
-(int)strokeJoinStyle;
-(int)strokeCapStyle;
-(const EshTablePropVal<long>*)strokeCustomDash;
-(int)strokePresetDash;
-(int)strokeCompoundType;
-(long)strokeMiterLimit;
-(long)strokeWidth;
-(long)strokeFgAlpha;
-(id)strokeFillBlipName;
-(unsigned long)strokeFillBlipID;
-(int)strokeFillType;
-(id)fillBlipName;
-(EshBlip*)fillBlipDataReference;
-(unsigned long)fillBlipID;
-(const EshTablePropVal<EshGradientStop>*)fillGradientColors;
-(long)fillFocusBottom;
-(long)fillFocusRight;
-(long)fillFocusTop;
-(long)fillFocusLeft;
-(long)fillFocus;
-(long)fillAngle;
-(long)fillBgAlpha;
-(long)fillFgAlpha;
-(int)fillType;
-(EshColor)shadowColor;
-(EshColor)strokeBgColor;
-(EshColor)strokeFgColor;
-(BOOL)isStroked;
-(EshColor)fillBgColor;
-(EshColor)fillFgColor;
-(BOOL)isFilled;
@end

