/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"
#import "OABColorPropertiesManager.h"
#import "OABFillPropertiesManager.h"

@protocol OABPropertiesManager;

@protocol OABFillPropertiesManager <OABColorPropertiesManager>
-(id)fillBlipName;
-(unsigned long)fillBlipID;
-(const EshTablePropVal<EshGradientStop>*)fillGradientColors;
-(long)fillFocusBottom;
-(long)fillFocusRight;
-(long)fillFocusTop;
-(long)fillFocusLeft;
-(long)fillFocus;
-(long)fillAngle;
-(long)fillBgAlpha;
-(long)fillFgAlpha;
-(int)fillType;
@end

__attribute__((visibility("hidden")))
@interface OABFillPropertiesManager : XXUnknownSuperclass <OABFillPropertiesManager> {
@private
	const EshFill* mFill;
	int mShapeType;
	id<OABPropertiesManager> mMasterManager;
}
-(id)fillBlipName;
-(EshBlip*)fillBlipDataReference;
-(unsigned long)fillBlipID;
-(const EshTablePropVal<EshGradientStop>*)fillGradientColors;
-(long)fillFocusBottom;
-(long)fillFocusRight;
-(long)fillFocusTop;
-(long)fillFocusLeft;
-(long)fillFocus;
-(long)fillAngle;
-(long)fillBgAlpha;
-(long)fillFgAlpha;
-(int)fillType;
-(EshColor)shadowColor;
-(EshColor)strokeBgColor;
-(EshColor)strokeFgColor;
-(BOOL)isStroked;
-(EshColor)fillBgColor;
-(EshColor)fillFgColor;
-(BOOL)isFilled;
-(void)dealloc;
-(id)initWithFill:(const EshFill*)fill shapeType:(int)type masterShape:(EshShape*)shape;
@end

