/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADFill.h"
#import "OfficeImport-Structs.h"


__attribute__((visibility("hidden")))
@interface OADNullFill : OADFill {
}
+(id)nullFill;
+(id)defaultProperties;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)setStyleColor:(id)color;
-(id)initWithDefaults;
-(id)copyWithZone:(NSZone*)zone;
@end

