/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface OADOle : XXUnknownSuperclass {
@private
	BOOL mIconic;
	NSString* mCLSID;
	NSString* mAnsiUserType;
	NSString* mAnsiClipboardFormatName;
	unsigned long mWinClipboardFormat;
	NSString* mMacClipboardFormat;
	NSString* mAnsiProgID;
	NSString* mUnicodeUserType;
	NSString* mUnicodeClipboardFormatName;
	NSString* mUnicodeProgID;
	id mObject;
}
@property(retain) id object;	// converted property
@property(retain) id unicodeProgID;	// converted property
@property(retain) id unicodeClipboardFormatName;	// converted property
@property(retain) id unicodeUserType;	// converted property
@property(retain) id ansiProgID;	// converted property
@property(retain) id macClipboardFormat;	// converted property
@property(assign) unsigned long winClipboardFormat;	// converted property
@property(retain) id ansiClipboardFormatName;	// converted property
@property(retain) id ansiUserType;	// converted property
@property(retain) id CLSID;	// converted property
@property(assign) BOOL iconic;	// converted property
+(BOOL)isCLSIDSupported:(id)supported;
+(BOOL)isProgIDSupported:(id)supported;
// converted property setter: -(void)setObject:(id)object;
// converted property getter: -(id)object;
// converted property setter: -(void)setUnicodeProgID:(id)anId;
// converted property getter: -(id)unicodeProgID;
// converted property setter: -(void)setUnicodeClipboardFormatName:(id)name;
// converted property getter: -(id)unicodeClipboardFormatName;
// converted property setter: -(void)setUnicodeUserType:(id)type;
// converted property getter: -(id)unicodeUserType;
// converted property setter: -(void)setAnsiProgID:(id)anId;
// converted property getter: -(id)ansiProgID;
// converted property setter: -(void)setMacClipboardFormat:(id)format;
// converted property getter: -(id)macClipboardFormat;
// converted property setter: -(void)setWinClipboardFormat:(unsigned long)format;
// converted property getter: -(unsigned long)winClipboardFormat;
// converted property setter: -(void)setAnsiClipboardFormatName:(id)name;
// converted property getter: -(id)ansiClipboardFormatName;
// converted property setter: -(void)setAnsiUserType:(id)type;
// converted property getter: -(id)ansiUserType;
// converted property setter: -(void)setCLSID:(id)clsid;
// converted property getter: -(id)CLSID;
// converted property setter: -(void)setIconic:(BOOL)iconic;
// converted property getter: -(BOOL)iconic;
-(void)dealloc;
-(id)init;
@end

