/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADDrawableProperties.h"
#import "OADEffectsParent.h"

@class OADTableStyle, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface OADTableProperties : OADDrawableProperties <OADEffectsParent> {
@private
	NSString* mStyleId;
	OADTableStyle* mStyle;
	BOOL mRightToLeft;
	BOOL mFirstRow;
	BOOL mFirstColumn;
	BOOL mLastRow;
	BOOL mLastColumn;
	BOOL mBandRow;
	BOOL mBandColumn;
	NSArray* mEffects;
}
@property(retain) id effects;	// converted property
@property(assign) BOOL bandColumn;	// converted property
@property(assign) BOOL bandRow;	// converted property
@property(assign) BOOL lastColumn;	// converted property
@property(assign) BOOL lastRow;	// converted property
@property(assign) BOOL firstColumn;	// converted property
@property(assign) BOOL firstRow;	// converted property
@property(assign) BOOL rightToLeft;	// converted property
@property(retain) id style;	// converted property
@property(retain) id styleId;	// converted property
+(id)defaultProperties;
-(BOOL)hasEffects;
// converted property setter: -(void)setEffects:(id)effects;
// converted property getter: -(id)effects;
-(BOOL)hasVectorNormalToDir:(int)dir atExtremePos:(int)extremePos;
-(BOOL)hasBandsNormalToDir:(int)dir;
// converted property setter: -(void)setBandColumn:(BOOL)column;
// converted property getter: -(BOOL)bandColumn;
// converted property setter: -(void)setBandRow:(BOOL)row;
// converted property getter: -(BOOL)bandRow;
// converted property setter: -(void)setLastColumn:(BOOL)column;
// converted property getter: -(BOOL)lastColumn;
// converted property setter: -(void)setLastRow:(BOOL)row;
// converted property getter: -(BOOL)lastRow;
// converted property setter: -(void)setFirstColumn:(BOOL)column;
// converted property getter: -(BOOL)firstColumn;
// converted property setter: -(void)setFirstRow:(BOOL)row;
// converted property getter: -(BOOL)firstRow;
// converted property setter: -(void)setRightToLeft:(BOOL)left;
// converted property getter: -(BOOL)rightToLeft;
// converted property setter: -(void)setStyle:(id)style;
// converted property getter: -(id)style;
// converted property setter: -(void)setStyleId:(id)anId;
// converted property getter: -(id)styleId;
-(void)dealloc;
-(id)initWithDefaults;
@end

