/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OAXEffect : XXUnknownSuperclass {
}
+(id)readEffectsFromXmlNode:(xmlNode*)xmlNode packagePart:(id)part drawingState:(id)state;
+(id)presetShadowTypeEnumMap;
+(void)readGlow:(id)glow fromXmlNode:(xmlNode*)xmlNode;
+(void)readReflection:(id)reflection fromXmlNode:(xmlNode*)xmlNode;
+(void)readPresetShadow:(id)shadow fromXmlNode:(xmlNode*)xmlNode;
+(void)readOuterShadow:(id)shadow fromXmlNode:(xmlNode*)xmlNode;
+(void)readShadow:(id)shadow fromXmlNode:(xmlNode*)xmlNode;
@end

