/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "OCPPackagePart.h"

@class SFUZipEntry;

__attribute__((visibility("hidden")))
@interface OCPZipPackagePart : OCPPackagePart {
@private
	SFUZipEntry* mEntry;
}
-(xmlTextReader*)xmlReader;
-(xmlDoc*)xmlDocument;
-(void)copyToFile:(id)file;
-(id)data;
-(void)dealloc;
-(id)initWithArchive:(id)archive location:(id)location package:(id)package;
@end

