/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OCPPackage.h"

@class NSMutableDictionary, SFUZipArchive;

__attribute__((visibility("hidden")))
@interface OCPZipPackage : OCPPackage {
@private
	SFUZipArchive* mArchive;
	NSMutableDictionary* mParts;
}
-(void)resetPartForLocation:(id)location;
-(id)partForLocation:(id)location;
-(void)dealloc;
-(id)initWithData:(id)data;
-(id)initWithPath:(id)path;
-(id)initWithArchive:(id)archive;
@end

