/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "PDAnimationCacheState.h"

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface PBAnimationCacheState : PDAnimationCacheState {
@private
	NSMutableSet* mEntranceDrawables;
	NSMutableSet* mExitDrawables;
}
-(BOOL)isValid:(id)valid;
-(void)dealloc;
-(id)init;
@end

