/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PBSlideState : XXUnknownSuperclass {
@private
	NSMutableDictionary* mBuildOrderMap;
	unsigned mCurrentGroupId;
}
-(unsigned)generateGroupId;
-(id)buildOrderMap;
-(void)addBuild:(id)build order:(unsigned)order;
-(void)reset;
-(void)dealloc;
-(id)init;
@end

