/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PDIterate : XXUnknownSuperclass {
@private
	int mType;
	BOOL mIsBackwards;
	BOOL mIsPercentage;
	double mValue;
}
@property(assign) double value;	// converted property
@property(assign) BOOL isValuePercentage;	// converted property
@property(assign) BOOL isBackwards;	// converted property
@property(assign) int type;	// converted property
// converted property setter: -(void)setValue:(double)value;
// converted property getter: -(double)value;
// converted property setter: -(void)setIsValuePercentage:(BOOL)percentage;
// converted property getter: -(BOOL)isValuePercentage;
// converted property setter: -(void)setIsBackwards:(BOOL)backwards;
// converted property getter: -(BOOL)isBackwards;
// converted property setter: -(void)setType:(int)type;
// converted property getter: -(int)type;
@end

