/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CMState.h"

@class OADTablePartStyle, CMOutlineState;

__attribute__((visibility("hidden")))
@interface PMState : CMState {
@private
	CMOutlineState* mListState;
	OADTablePartStyle* mCurrentRowStyle;
}
@property(retain) id currentRowStyle;	// converted property
// converted property getter: -(id)currentRowStyle;
// converted property setter: -(void)setCurrentRowStyle:(id)style;
-(id)listState;
-(void)dealloc;
-(id)init;
@end

