/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OAVState.h"

@class ESDObject, PBPresentationReaderState;

__attribute__((visibility("hidden")))
@interface PXVmlState : OAVState {
@private
	ESDObject* mLegacyTextGlobals;
	PBPresentationReaderState* mLegacyPresentationState;
}
@property(retain) id legacyPresentationState;	// converted property
@property(retain) id legacyTextGlobals;	// converted property
// converted property setter: -(void)setLegacyPresentationState:(id)state;
// converted property getter: -(id)legacyPresentationState;
// converted property setter: -(void)setLegacyTextGlobals:(id)globals;
// converted property getter: -(id)legacyTextGlobals;
-(void)dealloc;
@end

