/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WBParagraph : XXUnknownSuperclass {
}
+(int)blockType;
+(void)readFrom:(id)from textRun:(WrdParagraphTextRun*)run paragraph:(id)paragraph;
+(void)prepareFieldMarkersForWriting:(id)writing with:(id)with;
+(void)readAnnotationBookmarkFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readBookmarkFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readFieldMarkerFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readAnnotationFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readNoteFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readSymbolsFor:(id)aFor from:(id)from textRun:(WrdCharacterTextRun*)run;
+(void)readSpecialCharacterFor:(id)aFor from:(id)from at:(long)at textRun:(WrdCharacterTextRun*)run;
+(void)readPictureFor:(id)aFor from:(id)from at:(long)at textRun:(WrdCharacterTextRun*)run;
+(void)readOfficeArtFor:(id)aFor from:(id)from at:(long)at textRun:(WrdCharacterTextRun*)run;
+(void)readSpecialCharactersFor:(id)aFor from:(id)from textRun:(WrdCharacterTextRun*)run;
+(void)checkForAnnotationBookmarkFrom:(id)from runEnd:(int*)end readState:(WBParagraphReadState*)state;
+(void)checkForBookmarkFrom:(id)from runEnd:(int*)end readState:(WBParagraphReadState*)state;
+(void)check:(id)check forFieldMarkerFrom:(id)from runEnd:(int*)end readState:(WBParagraphReadState*)state;
+(bool)isCPAnnotationRangeEnd:(long)end bookmarkTable:(WrdBookmarkTable*)table;
+(void)checkForAnnotationFrom:(id)from runEnd:(int*)end readState:(WBParagraphReadState*)state;
+(void)checkForNoteFrom:(id)from footnote:(BOOL)footnote runEnd:(int*)end readState:(WBParagraphReadState*)state;
+(void)readCharacterRunsFor:(id)aFor from:(id)from readState:(WBParagraphReadState*)state;
+(void)readRunsFor:(id)aFor from:(id)from textRun:(WrdParagraphTextRun*)run;
@end

