/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"


__attribute__((visibility("hidden")))
@interface WBStyle : XXUnknownSuperclass {
}
+(void)prepareForWriting:(id)writing style:(id)style to:(WrdStyle*)to;
+(void)write:(id)write style:(id)style wrdStyle:(WrdStyle*)style3;
+(void)readFrom:(id)from wrdStyle:(WrdStyle*)style style:(id)style3;
+(void)readTableProperties:(id)properties style:(id)style from:(WrdStyle*)from;
@end

