/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "WDRun.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WDFormField : WDRun {
@private
	unsigned long mPosition;
	BOOL mLinkAbsolute;
	BOOL mLinkSpecifyingNamedLocation;
	NSString* mNamedLocation;
	NSString* mURI;
	NSString* mMacName;
	NSString* mDosName;
}
@property(retain) id dosName;	// converted property
@property(retain) id macName;	// converted property
@property(retain) id URI;	// converted property
@property(retain) id namedLocation;	// converted property
@property(assign) BOOL linkSpecifyingNamedLocation;	// converted property
@property(assign) BOOL linkAbsolute;	// converted property
@property(assign) unsigned long position;	// converted property
-(int)runType;
// converted property setter: -(void)setDosName:(id)name;
// converted property getter: -(id)dosName;
// converted property setter: -(void)setMacName:(id)name;
// converted property getter: -(id)macName;
// converted property setter: -(void)setURI:(id)uri;
// converted property getter: -(id)URI;
// converted property setter: -(void)setNamedLocation:(id)location;
// converted property getter: -(id)namedLocation;
// converted property setter: -(void)setLinkSpecifyingNamedLocation:(BOOL)location;
// converted property getter: -(BOOL)linkSpecifyingNamedLocation;
// converted property setter: -(void)setLinkAbsolute:(BOOL)absolute;
// converted property getter: -(BOOL)linkAbsolute;
// converted property setter: -(void)setPosition:(unsigned long)position;
// converted property getter: -(unsigned long)position;
-(void)dealloc;
-(id)initWithParagraph:(id)paragraph;
@end

