/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CMMapper.h"

@class WDSection;

__attribute__((visibility("hidden")))
@interface WMSectionMapper : CMMapper {
@private
	WDSection* wdSection;
	float mTopMargin;
	float mLeftMargin;
	BOOL mBreakAtStart;
	BOOL mBreakAtEnd;
	BOOL mIsTitlePage;
}
@property(assign) float leftMargin;	// converted property
@property(assign) float topMargin;	// converted property
+(BOOL)isContentEmpty:(id)empty;
// converted property getter: -(float)leftMargin;
// converted property setter: -(void)setLeftMargin:(float)margin;
// converted property getter: -(float)topMargin;
// converted property setter: -(void)setTopMargin:(float)margin;
-(void)mapAt:(id)at withState:(id)state;
-(void)MapSectionStyleAt:(id)at;
-(id)initWithWDSection:(id)wdsection breakAtStart:(BOOL)start breakAtEnd:(BOOL)end parent:(id)parent;
-(void)mapFooterAt:(id)at withState:(id)state;
-(void)mapHeaderAt:(id)at withState:(id)state;
@end

