/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import "PLCloudSharingJob.h"

@class NSDate, NSString;

@interface PLCloudSharingViewedStateChangeJob : PLCloudSharingJob {
@private
	NSString* _albumGUID;
	NSDate* _assetCollectionLastViewedCommentDate;
	BOOL _assetCollectionHasUnreadComments;
	NSString* _assetCollectionGUID;
	int _albumUnviewedAssetCount;
	BOOL _albumHasUnseenContent;
	int _jobType;
}
@property(retain, nonatomic) NSDate* assetCollectionLastViewedCommentDate;	// @synthesize=_assetCollectionLastViewedCommentDate
@property(assign, nonatomic) BOOL assetCollectionHasUnreadComments;	// @synthesize=_assetCollectionHasUnreadComments
@property(retain, nonatomic) NSString* assetCollectionGUID;	// @synthesize=_assetCollectionGUID
@property(assign, nonatomic) int albumUnviewedAssetCount;	// @synthesize=_albumUnviewedAssetCount
@property(assign, nonatomic) BOOL albumHasUnseenContent;	// @synthesize=_albumHasUnseenContent
@property(retain, nonatomic) NSString* albumGUID;	// @synthesize=_albumGUID
@property(assign, nonatomic) int jobType;	// @synthesize=_jobType
+(void)setLastViewedCommentDate:(id)date forAssetCollection:(id)assetCollection inAlbum:(id)album;
+(void)markAssetCollection:(id)collection asHavingUnreadComments:(BOOL)comments inAlbum:(id)album;
+(void)updateUnviewedAssetCollectionCount:(int)count forAlbum:(id)album;
+(void)markAlbum:(id)album asHavingUnseenContent:(BOOL)content;
// declared property setter: -(void)setJobType:(int)type;
// declared property getter: -(int)jobType;
// declared property setter: -(void)setAlbumHasUnseenContent:(BOOL)content;
// declared property getter: -(BOOL)albumHasUnseenContent;
// declared property setter: -(void)setAlbumUnviewedAssetCount:(int)count;
// declared property getter: -(int)albumUnviewedAssetCount;
// declared property setter: -(void)setAssetCollectionGUID:(id)guid;
// declared property getter: -(id)assetCollectionGUID;
// declared property setter: -(void)setAssetCollectionHasUnreadComments:(BOOL)comments;
// declared property getter: -(BOOL)assetCollectionHasUnreadComments;
// declared property setter: -(void)setAssetCollectionLastViewedCommentDate:(id)date;
// declared property getter: -(id)assetCollectionLastViewedCommentDate;
// declared property setter: -(void)setAlbumGUID:(id)guid;
// declared property getter: -(id)albumGUID;
-(void)_executeAssetLastViewedCommentDateChangedWithGroup;
-(void)_executeAssetCommentsReadStateChangedWithGroup;
-(void)_executeAlbumUnviewedAssetCountChangedWithGroup;
-(void)_executeAlbumViewedStateChanged;
-(void)runDaemonSide;
-(void)run;
-(int)daemonOperation;
-(void)dealloc;
-(id)description;
-(id)initFromXPCObject:(id)xpcobject;
-(void)encodeToXPCObject:(id)xpcobject;
@end

