/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import "PLCloudSharingJob.h"

@class NSDictionary;

@interface PLCloudSharedUpdateAlbumMetadataJob : PLCloudSharingJob {
@private
	NSDictionary* _metadata;
}
@property(retain, nonatomic) NSDictionary* metadata;	// @synthesize=_metadata
+(void)updateAlbumMetadata:(id)metadata;
// declared property setter: -(void)setMetadata:(id)metadata;
// declared property getter: -(id)metadata;
-(id)_argumentsDictionaryFromXPCEvent:(id)xpcevent;
-(id)_argumentsDictionaryAsData:(id)data;
-(void)runDaemonSide;
-(void)run;
-(int)daemonOperation;
-(id)description;
-(id)initFromXPCObject:(id)xpcobject;
-(void)encodeToXPCObject:(id)xpcobject;
@end

