/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface PLDelayedFiledSystemDeletions : XXUnknownSuperclass {
@private
	NSMutableArray* _deletionInfos;
}
+(id)deletionsFromChangeHubEvent:(id)changeHubEvent;
+(void)appendDescriptionForEvent:(id)event toComponents:(id)components;
-(id)initWithFilesystemDeletionInfos:(id)filesystemDeletionInfos;
-(void)deleteAllRemainingFilesAndThumbnails;
-(void)appendToXPCMessage:(id)xpcmessage;
-(void)addFilesystemDeletionInfo:(id)info;
-(void)dealloc;
-(id)debugDescription;
@end

