/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import "PLAlbumChangeNotification.h"

@class NSIndexSet, PLShuffledAlbum, NSOrderedSet;

@interface PLShuffledAlbumChangeNotification : PLAlbumChangeNotification {
@private
	PLShuffledAlbum* _album;
	PLAlbumChangeNotification* _backingNotification;
	NSIndexSet* _changedIndexes;
	NSOrderedSet* _newSet;
}
@property(readonly, retain) PLShuffledAlbum* album;	// converted property
@property(readonly, retain) NSIndexSet* changedIndexes;	// converted property
+(id)notificationForDerivedObject:(id)derivedObject priorChangeState:(id)state forBackingObjectNotification:(id)backingObjectNotification;
-(void)_calculateDiffs;
-(id)_changedObjects;
-(BOOL)_getOldSet:(id*)set newSet:(id*)set2;
-(id)_diffDescription;
-(id)description;
// converted property getter: -(id)changedIndexes;
-(id)insertedIndexes;
-(id)deletedIndexes;
-(BOOL)countDidChange;
-(BOOL)keyAssetDidChange;
-(BOOL)titleDidChange;
-(BOOL)shouldReload;
// converted property getter: -(id)album;
-(id)object;
-(void)dealloc;
-(id)initWithShuffledAlbum:(id)shuffledAlbum albumChangeNotification:(id)notification;
-(id)init;
@end

