/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import "MIME-Structs.h"
#import "MFByteSet.h"


@interface MFMutableByteSet : MFByteSet {
}
-(void)invert;
-(void)removeBytesInRange:(NSRange)range;
-(void)addBytesInRange:(NSRange)range;
@end

