/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMDaemonCore.framework/IMDaemonCore
 */

#import "IMDaemonCore-Structs.h"
#import "IMDHandle.h"
#import "IMFileCopierDelegate.h"
#import "IMDChat.h"
#import "IMDCallMonitor.h"
#import "IMDInvocationForwarder.h"
#import "IMDService.h"
#import "IMDAccount.h"
#import "IMTunesController.h"
#import "IMDFileTransferCenter.h"
#import "XXUnknownSuperclass.h"
#import "IMDServiceController.h"
#import "IMDServiceSession.h"
#import "IMDChatRegistry.h"
#import "IMSystemMonitorListener.h"
#import "IMServiceSessionProtocol.h"
#import "IMDAccountController.h"
#import "IMDAttachmentStore.h"
#import "IMConnectionMonitorDelegate.h"
#import "IMDMessageStore.h"
#import "IMDChatStore.h"
