/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BackBoardServices-Structs.h"

@class NSLock, NSThread;
@protocol BKSAccelerometerDelegate;

@interface BKSAccelerometer : XXUnknownSuperclass {
	id<BKSAccelerometerDelegate> _delegate;
	CFRunLoopSourceRef _accelerometerEventsSource;
	CFRunLoopRef _accelerometerEventsRunLoop;
	double _interval;
	NSLock* _lock;
	BOOL _orientationEventsEnabled;
	int _orientationCheckToken;
	int _orientationNotificationsToken;
	NSThread* _orientationEventsThread;
	float _xThreshold;
	float _yThreshold;
	float _zThreshold;
}
@property(assign, nonatomic) id<BKSAccelerometerDelegate> delegate;
@property(assign, nonatomic) BOOL orientationEventsEnabled;
@property(assign, nonatomic) float zThreshold;
@property(assign, nonatomic) float yThreshold;
@property(assign, nonatomic) float xThreshold;
@property(assign, nonatomic) double updateInterval;
@property(assign, nonatomic) BOOL accelerometerEventsEnabled;
-(void)_orientationDidChange;
-(id)_orientationEventsThread;
-(int)currentDeviceOrientation;
// declared property getter: -(BOOL)orientationEventsEnabled;
// declared property setter: -(void)setOrientationEventsEnabled:(BOOL)enabled;
-(void)_serverWasRestarted;
-(void)_checkOut;
-(void)_checkIn;
// declared property setter: -(void)setZThreshold:(float)threshold;
// declared property getter: -(float)zThreshold;
// declared property setter: -(void)setYThreshold:(float)threshold;
// declared property getter: -(float)yThreshold;
// declared property setter: -(void)setXThreshold:(float)threshold;
// declared property getter: -(float)xThreshold;
// declared property setter: -(void)setUpdateInterval:(double)interval;
// declared property getter: -(double)updateInterval;
// declared property setter: -(void)setAccelerometerEventsEnabled:(BOOL)enabled;
// declared property getter: -(BOOL)accelerometerEventsEnabled;
-(void)dealloc;
-(id)init;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
@end

