/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol OS_xpc_object;

@interface BKSXPCReply : XXUnknownSuperclass {
@private
	NSObject<OS_xpc_object>* _message;
}
+(id)messageWithReply:(id)reply;
-(void)sendReply:(id)reply;
-(id)message;
-(long long)messageKind;
-(void)dealloc;
-(id)initWithReply:(id)reply;
@end

