/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Search.framework/Search
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SPContentResult;

@interface SPTopHitsCompoundResult : XXUnknownSuperclass {
	SPContentResult* _content;
	unsigned _domain;
	NSString* _displayIdentifier;
}
@property(readonly, retain) SPContentResult* content;	// converted property
@property(readonly, assign) unsigned domain;	// converted property
@property(readonly, retain) NSString* displayIdentifier;	// converted property
-(void)dealloc;
// converted property getter: -(id)displayIdentifier;
// converted property getter: -(unsigned)domain;
// converted property getter: -(id)content;
-(id)initWithContent:(id)content domain:(unsigned)domain displayIdentifier:(id)identifier;
@end

