/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MediaStream.framework/MediaStream
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, MSTimerGate, CPDistributedMessagingCenter, NSObject;
@protocol OS_dispatch_queue;

@interface MSClientSidePauseContext : XXUnknownSuperclass {
@private
	NSString* _UUID;
	NSObject<OS_dispatch_queue>* _timerQueue;
	CPDistributedMessagingCenter* _server;
	MSTimerGate* _gate;
}
@property(retain, nonatomic) MSTimerGate* gate;	// @synthesize=_gate
@property(retain, nonatomic) CPDistributedMessagingCenter* server;	// @synthesize=_server
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* timerQueue;	// @synthesize=_timerQueue
// declared property setter: -(void)setGate:(id)gate;
// declared property getter: -(id)gate;
// declared property setter: -(void)setServer:(id)server;
// declared property getter: -(id)server;
// declared property setter: -(void)setTimerQueue:(id)queue;
// declared property getter: -(id)timerQueue;
-(void).cxx_destruct;
-(void)timerQueuePing;
-(void)timerQueueTimerFired;
-(void)resume;
-(id)initWithServer:(id)server;
@end

