/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccountSettingsUI.framework/AccountSettingsUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AccountSettingsUI-Structs.h"


@interface AccountSettingsUILinkButton : XXUnknownSuperclass {
	BOOL underline;
}
@property(assign, nonatomic) BOOL underline;	// @synthesize
// declared property setter: -(void)setUnderline:(BOOL)underline;
// declared property getter: -(BOOL)underline;
-(void)drawRect:(CGRect)rect;
-(void)setHighlighted:(BOOL)highlighted;
-(id)initWithFrame:(CGRect)frame;
@end

