/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccountSettingsUI.framework/AccountSettingsUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AccountSettingsUI-Structs.h"

@class NSArray, NSString;
@protocol AccountSettingsUIIdentityPickerControllerDelegate;

@interface AccountSettingsUIIdentityPickerController : XXUnknownSuperclass {
	id<AccountSettingsUIIdentityPickerControllerDelegate> _delegate;
	NSString* _property;
	NSArray* _identities;
	NSArray* _emailAddresses;
	BOOL _allowEditing;
}
@property(readonly, assign, nonatomic) NSString* property;	// @synthesize=_property
// declared property getter: -(id)property;
-(void)_updateCell:(id)cell selected:(BOOL)selected;
-(BOOL)_allowIdentitySelection;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(SecIdentity*)_selectedIdentity;
-(BOOL)_isPropertyEnabled;
-(id)_valueForSwitchSpecifier:(id)switchSpecifier;
-(void)_setPropertyEnabled:(BOOL)enabled identity:(SecIdentity*)identity;
-(void)_setValue:(id)value forSwitchSpecifier:(id)switchSpecifier;
-(SecIdentity*)_autoselectIdentityWithEnabled:(BOOL)enabled;
-(id)_identitySpecifiers;
-(id)_specifiersForIdentities:(id)identities;
-(void)_finishedFetchingIdentities:(id)identities;
-(id)specifiers;
-(void)viewDidLoad;
-(void)dealloc;
@end

