/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

#import "XMLHTTPRequest.h"
#import "Stocks-Structs.h"

@class ChartParserData, NSString, StockChartData;

@interface ChartUpdater : XMLHTTPRequest {
	id _delegate;
	NSString* _symbol;
	int _interval;
	StockChartData* _currentChartData;
	ChartParserData* _chartParserData;
}
@property(assign, nonatomic) __weak id delegate;	// @synthesize=_delegate
+(id)_rangeStringForInterval:(int)interval;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void).cxx_destruct;
-(id)aggregateDictionaryDomain;
-(void)failWithError:(id)error;
-(void)didParseData;
-(int)parseData:(id)data;
-(BOOL)updateChartForStock:(id)stock interval:(int)interval;
-(void)cancel;
-(id)init;
@end

