/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol OS_dispatch_queue;

@interface GraphRenderer : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _queue;
	BOOL _cancelled;
}
+(void)clearSharedRenderer;
+(id)sharedRenderer;
-(void).cxx_destruct;
-(void)performRenderOperation:(id)operation;
-(id)init;
@end

