/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

#import "XMLHTTPRequest.h"
#import "Stocks-Structs.h"

@class Stock, StockNewsItemCollection, NewsParserData;
@protocol NewsUpdaterDelegate;

@interface NewsUpdater : XMLHTTPRequest {
	id<NewsUpdaterDelegate> _delegate;
	BOOL _firstLoad;
	double _lastResponseTimestamp;
	StockNewsItemCollection* _lastNewsItemCollection;
	Stock* _stock;
	NewsParserData* _newsParserData;
}
@property(assign, nonatomic) __weak id<NewsUpdaterDelegate> delegate;	// @synthesize=_delegate
+(id)_newsItemCollectionCache;
+(id)sharedNewsUpdater;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void).cxx_destruct;
-(id)aggregateDictionaryDomain;
-(void)resetLocale;
-(void)didParseData;
-(void)failWithError:(id)error;
-(int)parseData:(id)data;
-(void)saveLastResponse;
-(BOOL)fetchNewsForStock:(id)stock;
-(void)loadNewsCacheFromDiskForSymbol:(id)symbol;
-(void)clearNewsCacheOnDisk;
-(BOOL)shouldReloadOnResume;
-(void)cancel;
-(id)init;
@end

