/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WebDatabasePauser : NSObject {
}
-(void)applicationWillEnterForeground;
-(void)applicationDidEnterBackground;
-(void)dealloc;
-(id)initWithBackgroundNotification:(id)backgroundNotification foregroundNotification:(id)notification;
@end

