/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import "NSURLDownloadDelegate.h"
#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WebDownloadInternal : NSObject <NSURLDownloadDelegate> {
@private
	id realDelegate;
}
-(void)download:(id)download didBeginChildDownload:(id)download2;
-(id)download:(id)download shouldBeginChildDownloadOfSource:(id)source delegate:(id*)delegate;
-(void)download:(id)download didFailWithError:(id)error;
-(void)downloadDidFinish:(id)download;
-(void)download:(id)download didCreateDestination:(id)destination;
-(void)download:(id)download decideDestinationWithSuggestedFilename:(id)suggestedFilename;
-(BOOL)download:(id)download shouldDecodeSourceDataOfMIMEType:(id)mimetype;
-(void)download:(id)download didReceiveDataOfLength:(unsigned)length;
-(void)download:(id)download didReceiveResponse:(id)response;
-(void)download:(id)download didCancelAuthenticationChallenge:(id)challenge;
-(void)download:(id)download didReceiveAuthenticationChallenge:(id)challenge;
-(id)download:(id)download willSendRequest:(id)request redirectResponse:(id)response;
-(void)downloadDidBegin:(id)download;
-(BOOL)respondsToSelector:(SEL)selector;
-(void)setRealDelegate:(id)delegate;
-(void)dealloc;
@end

