/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccessUI.framework/DataAccessUI
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface DADiagnosticsNotesController : XXUnknownSuperclass {
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(id)init;
-(void)_okButtonPressed;
-(void)_cancelButtonPressed;
-(void)_enableButtons;
-(void)_disableButtons;
@end

