/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccessUI.framework/DataAccessUI
 */

#import "AccountSettingsUIAccount.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (DASettingsAdditions)
+(id)buttonSpecifierWithTitle:(id)title target:(id)target action:(SEL)action confirmationInfo:(id)info;
+(id)switchSpecifierWithTitle:(id)title target:(id)target setter:(SEL)setter getter:(SEL)getter key:(id)key;
@end

@interface XXUnknownSuperclass (AccountSettingsUIAccount) <AccountSettingsUIAccount>
+(id)displayedShortAccountTypeString;
+(id)displayedAccountTypeString;
+(void*)createSyncDataSourceForDataclass:(id)dataclass options:(id)options;
+(Class)syncControllerClass;
+(Class)detailControllerClass;
+(id)allowedDataclasses;
-(BOOL)supportsPush;
-(id)uniqueId;
-(id)enabledDataclasses;
-(BOOL)otherAccountEnabledForDataclass:(id)dataclass;
@end

@interface XXUnknownSuperclass (UIAdditions)
-(id)accountInfoUsername;
-(BOOL)isOwnedByPayload:(id)payload;
@end

@interface XXUnknownSuperclass (ASAccount_SortedVisibleMailFolders)
-(id)_sortedVisibleASMailFolders;
-(id)_sortASFolders:(id)folders startingAtID:(id)anId;
@end

@interface XXUnknownSuperclass (UIAdditions)
-(id)owningProfile;
-(BOOL)isOwnedByPayload:(id)payload;
@end

