/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import "GQDTCell.h"


__attribute__((visibility("hidden")))
@interface GQDTGroupingCell : GQDTCell {
@private
	unsigned short mLevel;
	unsigned short mRowIdx;
	unsigned short mRowCount;
	BOOL mIsCollapsed;
	id mValue;
	id mFormat;
	CFBundleRef mProcessorBundle;
	BOOL mHasValidFormulaValue;
	CFStringRef mFormulaValue;
}
+(CFStringRef)displayTypeString:(int)string;
-(BOOL)hasFormulaValue;
-(CFStringRef)createFormattedValue;
-(id)value;
-(BOOL)isCollapsed;
-(unsigned short)rowCount;
-(unsigned short)rowIdx;
-(unsigned short)level;
-(void)dealloc;
-(int)readAttributes:(xmlTextReader*)attributes;
-(void)setProcessorBundle:(CFBundleRef)bundle;
-(int)readRootFormat:(xmlTextReader*)format;
-(int)readElement:(xmlTextReader*)element;
-(int)readValue:(xmlTextReader*)value;
@end

