/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import "GQDWPInlineList.h"

@class GQDSStyle;

__attribute__((visibility("hidden")))
@interface GQDWPParagraph : GQDWPInlineList {
@private
	GQDSStyle* mParaStyle;
	long mListLevel;
	BOOL mRestartList;
	BOOL mContinue;
	BOOL mIsHidden;
}
-(BOOL)isHidden;
-(BOOL)isBlank;
-(BOOL)cont;
-(BOOL)restartList;
-(long)listLevel;
-(id)paragraphStyle;
-(void)dealloc;
-(int)readAttributesFromReader:(xmlTextReader*)reader processor:(id)processor;
@end

