/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol SFUBufferedInputStream;

__attribute__((visibility("hidden")))
@interface SFUZipRecordInputStream : XXUnknownSuperclass {
@private
	id<SFUBufferedInputStream> mInput;
	const char* mBuffer;
	long long mBufferStart;
	long long mBufferEnd;
}
-(const char*)dataAtOffset:(long long)offset size:(unsigned long)size end:(long long)end;
-(void)dealloc;
-(id)initWithDataRepresentation:(id)dataRepresentation;
@end

