/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol NSCoding, NSObject;

@interface MSObjectWrapper : XXUnknownSuperclass {
@private
	long long _size;
	long long _uniqueID;
	id<NSObject, NSCoding> _object;
	int _errorCount;
}
@property(assign, nonatomic) int errorCount;	// @synthesize=_errorCount
@property(readonly, assign, nonatomic) id<NSCoding> object;	// @synthesize=_object
@property(assign, nonatomic) long long uniqueID;	// @synthesize=_uniqueID
@property(assign, nonatomic) long long size;	// @synthesize=_size
+(id)objectsFromWrappers:(id)wrappers equalToObject:(id)object;
+(id)objectsFromWrappers:(id)wrappers;
+(int)indexOfObject:(id)object inWrapperArray:(id)wrapperArray;
+(id)wrapperWithObject:(id)object size:(long long)size;
// declared property setter: -(void)setErrorCount:(int)count;
// declared property getter: -(int)errorCount;
// declared property getter: -(id)object;
// declared property setter: -(void)setUniqueID:(long long)anId;
// declared property getter: -(long long)uniqueID;
// declared property setter: -(void)setSize:(long long)size;
// declared property getter: -(long long)size;
-(void).cxx_destruct;
-(id)initWithObject:(id)object size:(long long)size;
@end

