/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "SSAuthenticateRequestDelegate.h"
#import "ISOperation.h"

@class NSNumber, SSAuthenticationContext, SSMutableAuthenticationContext;

@interface ISStoreAuthenticateOperation : ISOperation <SSAuthenticateRequestDelegate> {
@private
	NSNumber* _authenticatedDSID;
	SSMutableAuthenticationContext* _authenticationContext;
}
@property(readonly, assign) SSAuthenticationContext* authenticationContext;
-(void)_setAuthenticatedDSID:(id)dsid;
-(void)_handleAuthenticateResponse:(id)response;
-(id)_authenticatedDSID;
-(id)uniqueKey;
-(void)run;
-(id)authenticatedAccountDSID;
// declared property getter: -(id)authenticationContext;
-(void)dealloc;
-(id)initWithAuthenticationContext:(id)authenticationContext;
@end

