/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "ISSingleton.h"

@class ISUniqueOperationContext, NSLock, NSMutableDictionary, NSMutableArray;

@interface ISUniqueOperationManager : XXUnknownSuperclass <ISSingleton> {
	ISUniqueOperationContext* _activeContext;
	NSMutableArray* _contexts;
	NSLock* _lock;
	NSMutableDictionary* _lockPool;
}
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(id)_contextForOperation:(id)operation;
-(id)_activeContext;
-(void)uniqueOperationFinished:(id)finished forKey:(id)key;
-(void)setPredecessorIfNeeded:(id)needed forKey:(id)key;
-(id)predecessorForKey:(id)key operation:(id)operation;
-(id)lockWithIdentifier:(id)identifier;
-(void)checkOutOperation:(id)operation;
-(void)checkInOperation:(id)operation;
-(void)dealloc;
-(id)init;
@end

