/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import "IMSystemMonitorListener.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CKDispatchQueue, NSCache, CKMultiDict;

@interface CKPreviewManager : XXUnknownSuperclass <IMSystemMonitorListener> {
@private
	NSCache* _previewCache;
	CKMultiDict* _pendingOperations;
	CKDispatchQueue* _previewDispatchQueue;
}
@property(retain, nonatomic) CKDispatchQueue* previewDispatchQueue;	// @synthesize=_previewDispatchQueue
@property(retain, nonatomic) CKMultiDict* pendingOperations;	// @synthesize=_pendingOperations
@property(retain, nonatomic) NSCache* previewCache;	// @synthesize=_previewCache
+(id)sharedPreviewManager;
// declared property setter: -(void)setPreviewDispatchQueue:(id)queue;
// declared property setter: -(void)setPendingOperations:(id)operations;
// declared property setter: -(void)setPreviewCache:(id)cache;
-(void)didReceiveMemoryWarning;
-(void)prepareForResume;
-(void)prepareForSuspend;
-(void)resumePreviewDispatchQueue;
-(void)suspendPreviewDispatchQueue;
// declared property getter: -(id)previewDispatchQueue;
// declared property getter: -(id)pendingOperations;
// declared property getter: -(id)previewCache;
-(void)fileTransferRemoved:(id)removed;
-(void)fileTransferUpdated:(id)updated;
-(void)systemApplicationDidResumeForEventsOnly;
-(void)systemApplicationDidSuspendForEventsOnly;
-(void)systemApplicationDidResume;
-(void)systemApplicationDidSuspend;
-(void)flushCacheForMediaObject:(id)mediaObject;
-(id)previewForMediaObject:(id)mediaObject balloonOrientation:(int)orientation highlighted:(BOOL)highlighted;
-(id)init;
-(void)dealloc;
@end

