/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import "SportsWorkout-Structs.h"
#import "SWRunSensor.h"

@class NSMutableData, SWBluetoothMessageHandler, SWPacketUnscrambler, NSMutableArray;

@interface SWBluetoothRunSensor : SWRunSensor {
	NSMutableData* _bluetoothInputData;
	SWBluetoothMessageHandler* _messageHandler;
	unsigned _remainingBatteryLifetimeInHours;
	NSMutableArray* _packetRecord;
	SWPacketUnscrambler* _packetUnscrambler;
	unsigned _packetCount;
	double _connectionTime;
	double _disconnectionTime;
}
@property(readonly, assign, nonatomic) double secondsConnected;	// @dynamic
@property(readonly, assign, nonatomic) unsigned packetCount;	// @synthesize=_packetCount
@property(readonly, assign) unsigned remainingBatteryLifetimeInHours;	// converted property
+(void)__writePacketRecord:(id)record;
// declared property getter: -(unsigned)packetCount;
-(unsigned)_remainingBatteryLifetimeInHoursForPacket:(id)packet timestamp:(unsigned)timestamp;
-(XXStruct_BfdK7C)_deviceAddressForSerialNumber:(id)serialNumber;
-(id)_serialNumberForPacket:(id)packet timestamp:(unsigned)timestamp radioId:(unsigned*)anId;
-(BOOL)_isValidPacketForPaceModel:(id)paceModel timestamp:(unsigned)timestamp;
-(void)_receivedInputReadNotification:(id)notification;
-(void)_receivedConnectionFailureNotification:(id)notification;
-(void)_receivedConnectionNotification:(id)notification;
-(void)_receivedDiscoveryNotification:(id)notification;
-(void)_receivedActivationNotification:(id)notification;
-(void)_registerToReadInput;
-(void)_connectToDeviceWithAddress:(XXStruct_BfdK7C)address;
-(void)_discoverDevice;
-(void)cancelSearching;
-(void)beginSearching;
-(void)unlink;
-(void)cancelLinking;
-(void)beginLinking;
// converted property getter: -(unsigned)remainingBatteryLifetimeInHours;
-(void)deactivate;
// declared property getter: -(double)secondsConnected;
-(void)dealloc;
-(id)init;
@end

