/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSPersistentStoreCoordinator, NSManagedObjectContext, NSDictionary;
@protocol OS_dispatch_queue;

@interface SWDataController : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _dispatchQueue;
	BOOL _isPerformingMigration;
	NSPersistentStoreCoordinator* _persistentStoreCoordinator;
	NSManagedObjectContext* _managedObjectContext;
	int _priorMigrationVersionKey;
}
@property(readonly, assign, nonatomic) NSDictionary* achievements;	// @dynamic
+(id)sharedDataController;
-(void)_removeAllEmpedsFromCheckpoint;
-(void)_migrateTotals;
-(void)_migrateBests;
-(void)_importWorkoutFilesFromDirectory:(id)directory;
-(void)_migrateWorkoutData;
-(void)_migrateCalibrationData;
-(void)_fixupDatabase;
-(void)performMigrationIfNecessary;
-(void)_databaseProperty:(id)property setName:(id)name andIntegerValue:(int)value;
-(id)_plistForDatabaseProperty:(id)databaseProperty;
-(id)_databasePropertiesForName:(id)name;
-(void)_setCalibrationData:(id)data forSensorSerialNumber:(id)sensorSerialNumber walkCalibrationDate:(id)date runCalibrationDate:(id)date4;
-(void)setCalibrationData:(id)data forSensorSerialNumber:(id)sensorSerialNumber date:(id)date isWalk:(BOOL)walk;
-(id)_onQueue_calibrationDataForSensorSerialNumber:(id)sensorSerialNumber walkCalibrationDate:(id*)date runCalibrationDate:(id*)date3;
-(id)calibrationDataForSensorSerialNumber:(id)sensorSerialNumber walkCalibrationDate:(id*)date runCalibrationDate:(id*)date3;
-(void)clearAchievementForName:(id)name;
-(id)_onQueue_achievements;
// declared property getter: -(id)achievements;
-(id)_achievementsForName:(id)name sensorSerialNumber:(id)number;
-(void)_saveRunAchievementsToDatabase:(id)database forPreset:(id)preset sensorSerialNumber:(id)number;
-(void)_addValue:(id)value toAchievementName:(id)achievementName sensorSerialNumber:(id)number;
-(void)_replaceValueIfLarger:(id)larger forAchievementName:(id)achievementName sensorSerialNumber:(id)number;
-(void)_replaceValueIfSmaller:(id)smaller forAchievementName:(id)achievementName sensorSerialNumber:(id)number;
-(void)importExistingWorkoutSnapshotsWithCompletionBlock:(id)completionBlock;
-(void)_removeSnapshotForWorkout:(id)workout;
-(void)saveWorkoutSnapshot:(id)snapshot preset:(id)preset;
-(id)_pathOfSnapshotForWorkout:(id)workout;
-(BOOL)_workoutIsSynced:(id)synced;
-(id)latestWorkout;
-(id)unsyncedWorkouts;
-(id)syncedWorkouts;
-(id)allWorkouts;
-(id)_allWorkoutsWithSyncState:(int)syncState;
-(id)_dictionaryForWorkoutRecord:(id)workoutRecord;
-(void)_deleteXMLFileForWorkout:(id)workout;
-(void)deleteAllWorkouts;
-(void)deleteWorkoutForGUID:(id)guid;
-(id)_entitiesOfTypeName:(id)typeName forPropertyName:(id)propertyName isNull:(BOOL)null;
-(id)_entitiesOfTypeName:(id)typeName forPropertyName:(id)propertyName values:(id)values;
-(void)saveRunWorkout:(id)workout preset:(id)preset completionBlock:(id)block;
-(void)_saveRunWorkout:(id)workout preset:(id)preset;
-(id)_runWorkoutFileName;
-(void)_notifyDataStoreChanged;
-(void)_saveRunWorkoutToDatabase:(id)database xmlFileName:(id)name;
-(id)_snapshotForDictionary:(id)dictionary;
-(void)dealloc;
-(id)init;
@end

