/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import "SWSyncServiceConnection.h"

@class NSInputStream, NSString;
@protocol SWSyncWorkoutConnectionDelegate, SWSyncServiceConnectionDelegate;

@interface SWSyncWorkoutConnection : SWSyncServiceConnection {
	id<SWSyncServiceConnectionDelegate, SWSyncWorkoutConnectionDelegate> _delegate;
	NSString* _PIN;
	NSInputStream* _workoutXMLStream;
}
@property(readonly, assign, nonatomic) NSInputStream* workoutXMLStream;	// @synthesize=_workoutXMLStream
@property(readonly, assign, nonatomic) NSString* PIN;	// @synthesize=_PIN
@property(assign, nonatomic) id<SWSyncServiceConnectionDelegate, SWSyncWorkoutConnectionDelegate> delegate;	// @synthesize=_delegate
// declared property getter: -(id)workoutXMLStream;
// declared property getter: -(id)PIN;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)handleResponse:(id)response;
-(void)dealloc;
-(id)initWithPIN:(id)pin workoutXMLStream:(id)stream host:(id)host delegate:(id)delegate;
@end

