/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
 */

#import "GameKitServices-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface GCKEventItem : XXUnknownSuperclass {
@private
	XXStruct_jB8chB* _event;
	unsigned _pid;
}
@property(assign) unsigned pid;	// @synthesize=_pid
@property(assign) XXStruct_jB8chB* event;	// @synthesize=_event
// declared property setter: -(void)setPid:(unsigned)pid;
// declared property getter: -(unsigned)pid;
// declared property setter: -(void)setEvent:(XXStruct_jB8chB*)event;
// declared property getter: -(XXStruct_jB8chB*)event;
-(void)dealloc;
-(id)initWithEvent:(XXStruct_jB8chB*)event remotePeer:(unsigned)peer;
-(id)init;
@end

