/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray;
@protocol GKVoiceChatSessionDelegate;

@interface GKVoiceChatSession : XXUnknownSuperclass {
@private
	id opaqueSession;
}
@property(assign) float sessionVolume;
@property(readonly, assign) float inputMeter;
@property(assign, getter=isActiveSession) BOOL activeSession;
@property(readonly, assign) NSArray* peerList;
@property(readonly, assign) NSString* sessionName;
@property(assign) id<GKVoiceChatSessionDelegate> delegate;
// declared property setter: -(void)setSessionVolume:(float)volume;
// declared property getter: -(float)sessionVolume;
// declared property getter: -(float)inputMeter;
// declared property setter: -(void)setActiveSession:(BOOL)session;
// declared property getter: -(BOOL)isActiveSession;
// declared property getter: -(id)peerList;
// declared property getter: -(id)sessionName;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(float)outputMeterForPeer:(id)peer;
-(void)setMute:(BOOL)mute forPeer:(id)peer;
-(void)stopSession;
-(void)startSession;
-(void)dealloc;
-(id)initWithGKSession:(id)gksession sessionName:(id)name;
@end

