/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

typedef struct _NSZone NSZone;

typedef struct _NSRange {
	unsigned location;
	unsigned length;
} NSRange;

typedef struct NSObject {
	Class _field1;
} NSObject;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct opaqueCMSampleBuffer opaqueCMSampleBuffer;

typedef struct CGAffineTransform {
	float a;
	float b;
	float c;
	float d;
	float tx;
	float ty;
} CGAffineTransform;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct CGContext* CGContextRef;

typedef struct CGImage* CGImageRef;

typedef struct {
	double latitude;
	double longitude;
} XXStruct_zYrK5D;

typedef struct {
	int _field1;
	int _field2;
	int _field3;
	int _field4;
	int _field5;
	int _field6;
	BOOL _field7;
} XXStruct_g6RH7D;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct {
	BOOL _field1;
	BOOL _field2;
	BOOL _field3;
	BOOL _field4;
	float _field5;
	int _field6;
} XXStruct_3uUjXA;

typedef struct OpaqueFigSampleBufferProcessor OpaqueFigSampleBufferProcessor;

typedef struct _CAImageQueue* CAImageQueueRef;

typedef struct __CFString* CFStringRef;

typedef struct UIEdgeInsets {
	float top;
	float left;
	float bottom;
	float right;
} UIEdgeInsets;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct {
	int version;
	void* info;
	/*function-pointer*/ void* retain;
	/*function-pointer*/ void* release;
	/*function-pointer*/ void* copyDescription;
} XXStruct_4pnlqD;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct CGColorSpace* CGColorSpaceRef;

typedef struct {
	XXStruct_zYrK5D center;
	XXStruct_zYrK5D span;
} XXStruct_SRdqoD;

typedef struct CGPath* CGPathRef;

typedef struct __CFArray* CFArrayRef;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct _DNSServiceRef_t* DNSServiceRef_tRef;


