/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import "NSNetServiceDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSNetService, NSMutableArray, MediaControlClient, MCMediaControlClientRemote, AirPlayRemoteSlideshow, NSObject, NSString;
@protocol OS_dispatch_queue, PLAirTunesServicePhotoBrowsingDataSource;

@interface PLAirTunesService : XXUnknownSuperclass <NSNetServiceDelegate> {
	NSNetService* _netService;
	DNSServiceRef_tRef _dnsService;
	NSString* _deviceID;
	id<PLAirTunesServicePhotoBrowsingDataSource> _dataSource;
	NSMutableArray* _streamedPhotoUuids;
	MediaControlClient* _mediaControlClient;
	MCMediaControlClientRemote* _remoteMediaControlClient;
	NSString* _ipAddress;
	BOOL _streamingPhotos;
	BOOL _streamingRemoteSlideshow;
	BOOL _streamingLocalSlideShow;
	BOOL _streamingVideo;
	AirPlayRemoteSlideshow* _remoteSlideshow;
	NSDictionary* _remoteSlideshowAvailableFeatures;
	NSString* _password;
	BOOL _requiresPassword;
	BOOL _requiresPIN;
	BOOL _showingPasswordAlert;
	BOOL _validPassword;
	BOOL _validated;
	BOOL _sentPhoto;
	double _playStartTime;
	unsigned _features;
@private
	NSObject<OS_dispatch_queue>* _resolveQueue;
}
@property(assign, nonatomic) unsigned features;	// @synthesize=_features
@property(retain, nonatomic) NSString* password;	// @synthesize=_password
@property(assign, nonatomic) BOOL validPassword;	// @synthesize=_validPassword
@property(assign, nonatomic) BOOL requiresPIN;	// @synthesize=_requiresPIN
@property(assign, nonatomic) BOOL requiresPassword;	// @synthesize=_requiresPassword
@property(retain, nonatomic) NSDictionary* remoteSlideshowAvailableFeatures;	// @synthesize=_remoteSlideshowAvailableFeatures
@property(retain, nonatomic) AirPlayRemoteSlideshow* remoteSlideshow;	// @synthesize=_remoteSlideshow
@property(retain, nonatomic) NSString* ipAddress;	// @synthesize=_ipAddress
@property(assign, nonatomic) id<PLAirTunesServicePhotoBrowsingDataSource> dataSource;	// @synthesize=_dataSource
@property(assign, nonatomic) BOOL streamingLocalSlideShow;	// @synthesize=_streamingLocalSlideShow
@property(readonly, assign, nonatomic) NSString* deviceID;	// @synthesize=_deviceID
@property(readonly, assign, nonatomic) NSNetService* netService;	// @synthesize=_netService
+(void)endNetworkAssertion;
+(void)beginNetworkAssertion;
+(BOOL)canDisplayMedia:(id)media;
// declared property setter: -(void)setFeatures:(unsigned)features;
// declared property getter: -(unsigned)features;
// declared property setter: -(void)setStreamingLocalSlideShow:(BOOL)show;
// declared property getter: -(BOOL)streamingLocalSlideShow;
// declared property setter: -(void)setDataSource:(id)source;
// declared property getter: -(id)dataSource;
// declared property setter: -(void)setPassword:(id)password;
// declared property getter: -(id)password;
// declared property setter: -(void)setValidPassword:(BOOL)password;
// declared property getter: -(BOOL)validPassword;
// declared property setter: -(void)setRequiresPIN:(BOOL)pin;
// declared property getter: -(BOOL)requiresPIN;
// declared property setter: -(void)setRequiresPassword:(BOOL)password;
// declared property getter: -(BOOL)requiresPassword;
// declared property setter: -(void)setRemoteSlideshowAvailableFeatures:(id)features;
// declared property getter: -(id)remoteSlideshowAvailableFeatures;
// declared property setter: -(void)setRemoteSlideshow:(id)slideshow;
// declared property getter: -(id)remoteSlideshow;
// declared property setter: -(void)setIpAddress:(id)address;
// declared property getter: -(id)deviceID;
// declared property getter: -(id)netService;
-(id)description;
-(void)getRemoteFeaturesWithCompletionHandler:(id)completionHandler;
-(void)stopRemoteSlideshow;
-(void)startRemoteSlideshowWithTheme:(id)theme remoteSlideshowDelegate:(id)delegate;
-(id)remoteLocalizationForSlideshowThemeKey:(id)slideshowThemeKey;
-(id)supportedRemoteSlideshowThemes;
-(BOOL)supportsRemoteSlideshow;
-(void)_setDeviceID:(id)anId;
-(id)_fixLegacyEvent:(id)event;
-(BOOL)_streaming;
-(void)setVideoPosition:(double)position;
-(void)getVideoPosition:(id)position;
-(void)setRate:(float)rate;
-(void)playVideo:(id)video startTime:(double)time stateChangedBlock:(id)block;
-(void)streamPhoto:(id)photo withTransition:(id)transition;
-(void)invalidatePhotoCache;
-(void)_streamPhotosAdjacentToPhoto:(id)photo withTransition:(id)transition;
-(void)_streamPhoto:(id)photo withTransition:(id)transition andAction:(id)action;
-(void)stopStreamingWithCompletionBlock:(id)completionBlock;
-(void)stopStreaming;
-(void)invalidateStreaming;
-(void)_reallySendPhotoData:(id)data forPhotoWithUUID:(id)uuid withTransition:(id)transition andAction:(id)action;
-(BOOL)_allowsPhotoCaching;
-(BOOL)_supportsPhotoCaching;
-(void)validate;
-(void)_validateForBadPassword:(BOOL)badPassword completionBlock:(id)block;
-(void*)_keychainAccessibility;
-(BOOL)isAvailable;
// declared property getter: -(id)ipAddress;
-(id)name;
-(void)netService:(id)service didNotResolve:(id)resolve;
-(void)netServiceDidResolveAddress:(id)netService;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithNSNetService:(id)nsnetService;
-(void)_resolveWithTimeout:(double)timeout;
-(void)_cancelResolve;
@end

