/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLCameraFocusView.h"
#import "PhotoLibrary-Structs.h"

@class CAKeyframeAnimation;

@interface PLCameraFocusLockView : PLCameraFocusView {
	CAKeyframeAnimation* _lockBoundsAnimation;
	BOOL _scalingDown;
	BOOL _shouldEndFocus;
	CGAffineTransform _defaultTransform;
}
-(void)focusDidEnd;
-(void)startAnimating;
-(void)animateScaleDown;
-(void)finishedScalingDown;
-(void)animateLock;
-(id)_createLockBoundsAnimation;
-(void)dealloc;
-(id)init;
@end

