/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "UIScrollViewDelegate.h"
#import "PhotoLibrary-Structs.h"
#import "PLPhotoBrowserControllerDelegate.h"
#import "PLApplicationCameraViewControllerDelegate.h"
#import "PLCameraPreviewWellImageChangeObserver.h"
#import "PLAlbumListChangeObserver.h"
#import "PLAlbumChangeObserver.h"
#import "UIPageControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, PLApplicationCameraViewController, UIPanGestureRecognizer, PLKeepDaemonAliveAssertion;

@interface PLCameraPageController : XXUnknownSuperclass <PLApplicationCameraViewControllerDelegate, PLAlbumListChangeObserver, PLAlbumChangeObserver, PLCameraPreviewWellImageChangeObserver, PLPhotoBrowserControllerDelegate, UIScrollViewDelegate, UIPageControllerDelegate> {
	NSObject* _cameraAlbum;
	PLApplicationCameraViewController* _cameraViewController;
	UIViewController* _cameraAlbumNavigationController;
	UIViewController* _presentedCameraAlbumNavigationController;
	UIPanGestureRecognizer* _cameraPagePanGestureRecognizer;
	double _sessionStartTime;
	BOOL _supportsVideos;
	BOOL _usesSessionAlbum;
	BOOL _shouldShowCameraAlbum;
	BOOL _delayLoadingPhotoLibrary;
	BOOL _previouslyDidntChangeStatusBar;
	BOOL _ignoreVolumeButtons;
	BOOL _isDismissingCameraAlbum;
	BOOL _reallyIgnoreVolumeButtonEvents;
	PLKeepDaemonAliveAssertion* _keepDaemonAliveAssertion;
}
@property(retain, nonatomic) UIViewController* cameraAlbumNavigationController;	// @synthesize=_cameraAlbumNavigationController
@property(retain, nonatomic) PLApplicationCameraViewController* cameraViewController;	// @synthesize=_cameraViewController
@property(readonly, assign) NSObject* cameraAlbum;	// converted property
+(void)initialize;
// declared property setter: -(void)setCameraAlbumNavigationController:(id)controller;
// declared property setter: -(void)setCameraViewController:(id)controller;
-(void)_cleanupForCameraEnd;
-(void)prepareAlbumNavigationControllerForReuse:(id)reuse;
-(id)newAlbumNavigationController;
-(void)_showCameraAlbumIndexSheet:(BOOL)sheet;
-(unsigned)albumPageIndex;
-(unsigned)cameraPageIndex;
-(void)_handleVolumeButtonUp;
-(void)_handleVolumeButtonDown;
-(void)_setWantsVolumeButtonEvents:(BOOL)events;
-(void)_updateVolumeButtonEventsAbility;
-(void)cameraPreviewWellImageDidChange:(id)cameraPreviewWellImage;
-(void)_makeViewControllersPerformSelector:(SEL)selector withNotification:(id)notification;
-(void)albumDidChange:(id)album;
-(void)albumListDidChange:(id)albumList;
-(void)_libraryDidChange:(id)_library;
-(void)prepareForDefaultImageSnapshot;
-(void)dismissCameraAlbumForSuspension;
-(void)dismissCameraAlbum:(id)album;
-(void)dismissCameraAlbumAnimated:(BOOL)animated forSuspension:(BOOL)suspension;
-(void)prepareForDismissal;
-(void)_stopCameraPreviewAnimated:(BOOL)animated;
-(void)stopCameraPreview;
-(void)setSessionID:(id)anId;
-(void)startCameraPreviewWithSavedConfiguration;
-(void)startCameraPreview;
-(BOOL)showingCameraPreview;
-(void)takePicture;
-(void)photoBrowserControllerDidEndPaging:(id)photoBrowserController;
-(void)photoBrowserControllerWillBeginPaging:(id)photoBrowserController;
-(void)cameraViewControllerFinishedOpeningIrisForPreview:(id)preview;
-(void)cameraViewControllerFinishedClosingIris:(id)iris;
-(void)cameraViewControllerUIShouldUnlock:(id)cameraViewControllerUI;
-(void)cameraViewControllerUIShouldLock:(id)cameraViewControllerUI;
-(void)_enableSwipeToCameraRoll:(BOOL)cameraRoll;
-(void)_updatePhotoBrowsersGestureEnabledState;
-(void)pageControllerDidEndPaging:(id)pageController;
-(void)pageControllerWillBeginPaging:(id)pageController;
-(id)pageController:(id)controller viewControllerAtIndex:(int)index;
-(void)_resetStatusBarPosition;
-(void)_updateStatusBarPositionForView:(id)view;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)_setupSwipeGesture;
-(Class)_pageControllerScrollViewClass;
-(id)_currentPhotoBrowser;
-(id)_pagingPhotoBrowser;
-(id)_presentedPhotoBrowser;
-(id)_photoBrowserForNavigationController:(id)navigationController;
// converted property getter: -(NSObject*)cameraAlbum;
// declared property getter: -(id)cameraViewController;
// declared property getter: -(id)cameraAlbumNavigationController;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)_applicationDidEnterBackground:(id)_application;
-(void)_applicationWillEnterForeground:(id)_application;
-(void)applicationDidResume;
-(void)applicationWillSuspend;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)_createCameraViewControllerWithSessionAlbum:(BOOL)sessionAlbum useCameraLocationBundleID:(BOOL)anId startPreviewImmediately:(BOOL)immediately;
-(void)dealloc;
-(id)initWithSessionID:(id)sessionID startPreviewImmediately:(BOOL)immediately;
-(id)initWithSessionID:(id)sessionID;
-(id)init;
-(id)_initWithSessionID:(id)sessionID useCameraLocationBundleID:(BOOL)anId startPreviewImmediately:(BOOL)immediately;
@end

