/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PhotoLibrary-Structs.h"

@class PLManagedAsset, UIImage, NSError, NSMutableDictionary, NSData, NSString;

@interface PLCameraImportItem : XXUnknownSuperclass {
	NSString* _identifier;
	NSString* _parentFolder;
	NSString* _basePath;
	NSMutableDictionary* _representationsMapping;
	UIImage* _thumbnail;
	NSData* _thumbnailData;
	int _thumbnailState;
	BOOL _metadataRequested;
	BOOL _thumbnailRequested;
	BOOL _shouldImport;
	NSError* _importError;
@private
	NSString* eventName;
	PLManagedAsset* importedAsset;
}
@property(retain, nonatomic) NSError* importError;	// @synthesize=_importError
@property(assign, nonatomic) BOOL shouldImport;	// @synthesize=_shouldImport
@property(retain, nonatomic) NSData* thumbnailData;	// @synthesize=_thumbnailData
@property(readonly, assign, nonatomic) UIImage* thumbnail;	// @synthesize=_thumbnail
@property(retain, nonatomic) PLManagedAsset* importedAsset;	// @synthesize
@property(retain, nonatomic) NSString* eventName;	// @synthesize
@property(retain, nonatomic) NSString* basePath;	// @synthesize=_basePath
@property(readonly, assign, nonatomic) NSString* parentFolder;	// @synthesize=_parentFolder
@property(readonly, assign, nonatomic) NSString* identifier;	// @synthesize=_identifier
@property(assign) int thumbnailState;	// converted property
// declared property setter: -(void)setImportedAsset:(id)asset;
// declared property getter: -(id)importedAsset;
// declared property setter: -(void)setEventName:(id)name;
// declared property getter: -(id)eventName;
// declared property setter: -(void)setImportError:(id)error;
// declared property getter: -(id)importError;
// declared property setter: -(void)setShouldImport:(BOOL)import;
// declared property getter: -(BOOL)shouldImport;
// declared property setter: -(void)setThumbnailData:(id)data;
// declared property getter: -(id)thumbnailData;
// declared property getter: -(id)thumbnail;
// declared property setter: -(void)setBasePath:(id)path;
// declared property getter: -(id)basePath;
// declared property getter: -(id)parentFolder;
// declared property getter: -(id)identifier;
-(id)otherExtensions;
-(id)audioExtension;
-(id)movieExtension;
-(id)rawExtension;
-(id)jpgExtension;
-(id)_fileExtensionForTypeWithSelector:(SEL)selector;
-(id)fileExtensions;
-(BOOL)isStandaloneMovie;
-(BOOL)isStandalonePhoto;
-(BOOL)isAudio;
-(BOOL)isMovie;
-(BOOL)isRaw;
-(BOOL)isJPEG;
-(BOOL)_isTypeWithSelector:(SEL)selector;
-(unsigned long long)fileSize;
-(id)creationDate;
-(void)markRepresentationsInDatabase;
-(BOOL)isInDatabaseForce:(BOOL)databaseForce;
-(BOOL)isOnDisk;
-(BOOL)isLocked;
-(void)setThumbnailWithImageRef:(CGImageRef)imageRef;
-(void)clearThumbnail;
-(void)cancelThumbnailRequest;
-(BOOL)canRequestThumbnail;
-(void)requestThumbnail;
// converted property setter: -(void)setThumbnailState:(int)state;
// converted property getter: -(int)thumbnailState;
-(void)clearMetadata;
-(BOOL)hasAllMetadata;
-(id)metadataForRepresentationWithFileExtension:(id)fileExtension;
-(BOOL)canRequestMetadata;
-(void)requestMetadata;
-(id)representationForCameraFile:(id)cameraFile;
-(void)removeRepresentationForCameraFile:(id)cameraFile;
-(void)_removeRepresentation:(id)representation;
-(void)addRepresentationForCameraFile:(id)cameraFile;
-(void)_addRepresentation:(id)representation;
-(id)representations;
-(id)description;
-(void)dealloc;
-(id)initWithIdentifier:(id)identifier parentFolder:(id)folder;
@end

