/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIViewController, UIImageView;
@protocol PLModalDimmingContained;

@interface PLModalDimmingViewController : XXUnknownSuperclass {
	UIImageView* _vignetteView;
	UIViewController<PLModalDimmingContained>* _contentViewController;
	UIView* _wrapperView;
}
@property(retain, nonatomic) UIViewController<PLModalDimmingContained>* contentViewController;	// @synthesize=_contentViewController
// declared property getter: -(id)contentViewController;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)_updateVignetteToOrientation:(int)orientation;
-(void)dismissWithCustomAnimation:(int)customAnimation completionHandler:(id)handler;
-(void)presentWithCustomAnimation;
-(void)presentModalOnViewController:(id)controller animated:(BOOL)animated completionHandler:(id)handler;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_updateWrapperView:(id)view toOrientation:(int)orientation forViewController:(id)viewController;
// declared property setter: -(void)setContentViewController:(id)controller;
-(void)viewDidLoad;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithContentViewController:(id)contentViewController;
@end

