/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView, UILabel;

@interface PLPublicURLActivityView : XXUnknownSuperclass {
	UIActivityIndicatorView* _spinner;
	UILabel* _infoLabel;
}
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame turningPublicURLON:(BOOL)urlon;
@end

