/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLAlbumViewController.h"
#import "PhotoLibrary-Structs.h"


@interface PLUIAlbumViewController : PLAlbumViewController {
	int _previousStatusBarStyle;
	int _newStatusBarStyle;
	unsigned _didSetPreviousStatusBarStyle : 1;
}
-(BOOL)footerSubtitleAllowsEmail:(id)email;
-(id)footerAccessoryViewForAlbumView:(id)albumView;
-(void)albumView:(id)view didTapPhotoAtIndexPath:(id)indexPath;
-(void)albumViewSelectionDidChange:(id)albumViewSelection added:(id)added removed:(id)removed;
-(void)setAlbum:(NSObject*)album;
-(void)_setImagePickerMediaTypes:(id)types;
-(void)_doneButtonClicked:(id)clicked;
-(void)_cancelButtonClicked:(id)clicked;
-(void)_showDoneButton;
-(void)_showCancelButton;
-(BOOL)_dismissButtonAllowed;
-(id)albumView:(id)view badgeImageForPhotoAtIndexPath:(id)indexPath;
-(void)updateUnreadMarkerAnimated:(BOOL)animated;
-(void)_libraryDidChange:(id)_library;
-(int)_imagePickerStatusBarStyle;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
@end

