/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CalDAVContainerMultiGetTask : XXUnknownSuperclass {
	BOOL _getScheduleTags;
	BOOL _getScheduleChanges;
}
@property(assign) BOOL getScheduleChanges;	// @synthesize=_getScheduleChanges
@property(assign) BOOL getScheduleTags;	// @synthesize=_getScheduleTags
// declared property setter: -(void)setGetScheduleChanges:(BOOL)changes;
// declared property getter: -(BOOL)getScheduleChanges;
// declared property setter: -(void)setGetScheduleTags:(BOOL)tags;
// declared property getter: -(BOOL)getScheduleTags;
-(void)setAdditionalProperties:(id)properties onDataItem:(id)item;
-(id)copyAdditionalPropElements;
-(id)initWithURLs:(id)urls atContainerURL:(id)containerURL getScheduleTags:(BOOL)tags getScheduleChanges:(BOOL)changes;
-(id)initWithURLs:(id)urls atContainerURL:(id)containerURL getScheduleTags:(BOOL)tags getScheduleChanges:(BOOL)changes appSpecificCalendarItemClass:(Class)aClass;
@end

