/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoardUI-Structs.h"

@class SBDeviceLockViewWithKeyboard;

@interface SBDeviceLockKeyboard : XXUnknownSuperclass {
	SBDeviceLockViewWithKeyboard* _deviceLockView;
}
-(void)maximize;
-(void)minimize;
-(BOOL)shouldSaveMinimizationState;
-(BOOL)canDismiss;
-(BOOL)isActive;
-(id)initWithFrame:(CGRect)frame deviceLockView:(id)view;
@end

