/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TIDebugValue : XXUnknownSuperclass {
@private
	float defaultValue;
	float sweepValue;
	float sweepMin;
	float sweepMax;
	float stepSize;
}
@property(assign, nonatomic) float stepSize;	// @synthesize
@property(assign, nonatomic) float sweepMax;	// @synthesize
@property(assign, nonatomic) float sweepMin;	// @synthesize
@property(assign, nonatomic) float sweepValue;	// @synthesize
@property(assign, nonatomic) float defaultValue;	// @synthesize
// declared property setter: -(void)setStepSize:(float)size;
// declared property getter: -(float)stepSize;
// declared property setter: -(void)setSweepMax:(float)max;
// declared property getter: -(float)sweepMax;
// declared property setter: -(void)setSweepMin:(float)min;
// declared property getter: -(float)sweepMin;
// declared property setter: -(void)setSweepValue:(float)value;
// declared property getter: -(float)sweepValue;
// declared property setter: -(void)setDefaultValue:(float)value;
// declared property getter: -(float)defaultValue;
@end

