/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

#import "UIAccessibility-Structs.h"


@protocol UIAccessibilityReadingContent
-(id)accessibilityPageContent;
-(CGRect)accessibilityFrameForLineNumber:(int)lineNumber;
-(id)accessibilityContentForLineNumber:(int)lineNumber;
-(int)accessibilityLineNumberForPoint:(CGPoint)point;
@end

