/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SSProtocolConditionalContext, NSDictionary;

@interface SSProtocolConditionalEvaluator : XXUnknownSuperclass {
@private
	SSProtocolConditionalContext* _context;
	NSDictionary* _dictionary;
}
+(void)setDefaultConditionalContext:(id)context;
+(id)defaultConditionalContext;
-(int)_logicalOperatorForString:(id)string;
-(id)_dictionaryByEvaluatingWithForcedValue:(int)forcedValue;
-(id)_dictionaryByEvaluatingDictionary:(id)dictionary withForcedValue:(int)forcedValue;
-(id)_dictionaryByEvaluatingChildrenOfDictionary:(id)dictionary withForcedValue:(int)forcedValue;
-(BOOL)_checkConditions:(id)conditions withOperator:(id)anOperator;
-(id)_arrayByEvaluatingChildrenOfArray:(id)array withForcedValue:(int)forcedValue;
-(id)dictionaryByRemovingConditions;
-(id)dictionaryByEvaluatingConditions;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary conditionalContext:(id)context;
-(id)initWithDictionary:(id)dictionary;
-(id)init;
@end

