/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "SSXPCCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SSSoftwareLibraryItem : XXUnknownSuperclass <SSXPCCoding> {
@private
	NSMutableDictionary* _etags;
	BOOL _profileValidated;
	NSMutableDictionary* _propertyValues;
}
@property(assign, nonatomic, getter=isProfileValidated) BOOL profileValidated;	// @synthesize=_profileValidated
// declared property setter: -(void)setProfileValidated:(BOOL)validated;
// declared property getter: -(BOOL)isProfileValidated;
-(id)copyXPCEncoding;
-(id)initWithXPCEncoding:(id)xpcencoding;
-(void)_setValue:(id)value forProperty:(id)property;
-(id)_initWithITunesMetadata:(id)itunesMetadata;
-(id)valueForProperty:(id)property;
-(BOOL)setETag:(id)tag forAssetType:(id)assetType error:(id*)error;
-(id)ETagForAssetType:(id)assetType;
-(void)dealloc;
@end

