/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "VectorKit-Structs.h"
#import "VKShieldArtwork.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface _VKGenericShieldArtwork : VKShieldArtwork {
@private
	float _leftCap;
	float _rightCap;
	float _baseline;
	float _horizontalPadding;
	NSDictionary* _stringAttributes;
	CGColorRef _shadowColor;
	CGSize _shadowOffset;
	float _shadowSize;
}
-(CGImageRef)newImageWithShieldText:(id)shieldText;
-(CGSize)sizeWithTextWidth:(float)textWidth;
-(float)rightCapWidth;
-(float)leftCapWidth;
-(void)dealloc;
-(id)initWithImage:(id)image scale:(float)scale horizontalPadding:(float)padding textColor:(VGLColor)color baseline:(float)baseline leftCap:(float)cap rightCap:(float)cap7 shouldStroke:(BOOL)stroke strokeWidth:(float)width strokeColor:(VGLColor)color10 shouldShadow:(BOOL)shadow shadowOffset:(CGSize)offset shadowSize:(float)size shadowColor:(VGLColor)color14 fontSize:(float)size15;
@end

