/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "VectorKit-Structs.h"
#import "VGLProgram.h"


__attribute__((visibility("hidden")))
@interface VGLCircleStrokeProgram : VGLProgram {
@private
	int _uTextureSampler;
	int _textureSampler;
	int _uColor;
	VGLColor _color;
	int _uLocalEyePos;
	int _uLocalEyeDir;
	int _uTanHalfHorizFOV;
	int _uHalfScreenDims;
	XXStruct_ZUkpeA _localEyePos;
	XXStruct_ZUkpeA _localEyeDir;
	float _tanHalfHorizFOV;
	CGSize _halfScreenDims;
}
@property(assign, nonatomic) CGSize halfScreenDims;	// @synthesize=_halfScreenDims
@property(assign, nonatomic) float tanHalfHorizFOV;	// @synthesize=_tanHalfHorizFOV
@property(assign, nonatomic) XXStruct_ZUkpeA localEyeDir;	// @synthesize=_localEyeDir
@property(assign, nonatomic) XXStruct_ZUkpeA localEyePos;	// @synthesize=_localEyePos
@property(assign, nonatomic) VGLColor color;	// @synthesize=_color
@property(assign, nonatomic) int textureSampler;	// @synthesize=_textureSampler
+(id)program;
// declared property getter: -(CGSize)halfScreenDims;
// declared property getter: -(float)tanHalfHorizFOV;
// declared property getter: -(XXStruct_ZUkpeA)localEyeDir;
// declared property getter: -(XXStruct_ZUkpeA)localEyePos;
// declared property getter: -(VGLColor)color;
// declared property getter: -(int)textureSampler;
// declared property setter: -(void)setHalfScreenDims:(CGSize)dims;
// declared property setter: -(void)setTanHalfHorizFOV:(float)fov;
// declared property setter: -(void)setLocalEyeDir:(XXStruct_ZUkpeA)dir;
// declared property setter: -(void)setLocalEyePos:(XXStruct_ZUkpeA)pos;
// declared property setter: -(void)setColor:(VGLColor)color;
// declared property setter: -(void)setTextureSampler:(int)sampler;
-(id)init;
@end

