/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "VGLCullableMesh.h"
#import "VectorKit-Structs.h"


__attribute__((visibility("hidden")))
@interface VGLCenterLineMesh : VGLCullableMesh {
@private
	int _lastRenderPass;
	int _meshType;
	int _roadClass;
	int _trafficSpeed;
	int _drivingDirection;
	float _textureMappingStepQuantizationScaler;
	VGLColor _trafficPrimaryColor;
}
@property(assign, nonatomic) VGLColor trafficPrimaryColor;	// @synthesize=_trafficPrimaryColor
@property(assign, nonatomic) float textureMappingStepQuantizationScaler;	// @synthesize=_textureMappingStepQuantizationScaler
@property(assign, nonatomic) int drivingDirection;	// @synthesize=_drivingDirection
@property(assign, nonatomic) int trafficSpeed;	// @synthesize=_trafficSpeed
@property(readonly, assign, nonatomic) int centerLineMeshType;	// @synthesize=_meshType
@property(assign, nonatomic) int roadClass;	// @synthesize=_roadClass
// declared property setter: -(void)setTrafficPrimaryColor:(VGLColor)color;
// declared property getter: -(VGLColor)trafficPrimaryColor;
// declared property setter: -(void)setTextureMappingStepQuantizationScaler:(float)scaler;
// declared property getter: -(float)textureMappingStepQuantizationScaler;
// declared property setter: -(void)setTrafficSpeed:(int)speed;
// declared property getter: -(int)trafficSpeed;
// declared property setter: -(void)setDrivingDirection:(int)direction;
// declared property getter: -(int)drivingDirection;
// declared property getter: -(int)centerLineMeshType;
// declared property setter: -(void)setRoadClass:(int)aClass;
// declared property getter: -(int)roadClass;
-(id)initDashedMesh;
-(id)initTrafficMesh;
-(id)initRoadAsLinesMesh;
-(id)initRoadMesh;
-(id)initMeshOfType:(int)type;
-(id)init;
-(BOOL)isPrimaryIndexModeLinesWithTriangles;
@end

