/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface VKAnimation : XXUnknownSuperclass {
	id _stepHandler;
	id _completionHandler;
	id _timingFunction;
	double _duration;
	double _startTimestamp;
	double _pauseTimestamp;
	struct {
		unsigned runsForever : 1;
		unsigned startTimestampSet : 1;
		unsigned pauseTimestampSet : 1;
		unsigned completed : 1;
		unsigned state : 2;
	} _flags;
	NSString* _name;
	int _priority;
}
@property(readonly, assign, nonatomic) int priority;	// @synthesize=_priority
@property(assign, nonatomic) BOOL runsForever;
@property(readonly, assign, nonatomic) BOOL running;
@property(copy, nonatomic) id timingFunction;	// @synthesize=_timingFunction
@property(assign, nonatomic) double duration;	// @synthesize=_duration
// declared property getter: -(int)priority;
// declared property getter: -(id)timingFunction;
// declared property getter: -(double)duration;
-(void)stop;
-(void)startWithStepHandler:(id)stepHandler completionHandler:(id)handler;
-(void)onTimerFired:(double)fired;
-(void)resume;
-(void)pause;
-(void)_stopAnimation:(BOOL)animation;
-(id)description;
-(void)dealloc;
-(id)initWithName:(id)name;
-(id)initWithDuration:(double)duration name:(id)name;
-(id)init;
-(id)initWithDuration:(double)duration;
-(id)initWithPriority:(int)priority;
-(id)initWithPriority:(int)priority name:(id)name;
-(id)initWithDuration:(double)duration priority:(int)priority name:(id)name;
// declared property getter: -(BOOL)runsForever;
// declared property setter: -(void)setRunsForever:(BOOL)forever;
// declared property getter: -(BOOL)running;
// declared property setter: -(void)setTimingFunction:(id)function;
// declared property setter: -(void)setDuration:(double)duration;
@end

