/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "NSObject.h"
#import "VectorKit-Structs.h"

@class NSString, UIView;

@protocol VKCalloutSource <NSObject>
@optional
@property(readonly, assign, nonatomic) UIView* rightCalloutAccessoryView;
@property(readonly, assign, nonatomic) UIView* leftCalloutAccessoryView;
@property(readonly, assign, nonatomic) NSString* subtitle;
@required
@property(readonly, assign, nonatomic) NSString* title;
// declared property getter: -(id)title;
-(id)debugAnchorPointString;
-(void)setCalloutView:(id)view;
-(CGPoint)screenPointToScrollRelativeToWithCanvasSize:(CGSize)canvasSize;
-(CGPoint)calloutAnchorPointWithCanvasSize:(CGSize)canvasSize;
@optional
// declared property getter: -(id)rightCalloutAccessoryView;
// declared property getter: -(id)leftCalloutAccessoryView;
// declared property getter: -(id)subtitle;
@end

