/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "VectorKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMapTable, VKClassicGlobeCanvas;

__attribute__((visibility("hidden")))
@interface VKGlobePointCache : XXUnknownSuperclass {
@private
	VKClassicGlobeCanvas* _canvas;
	NSMapTable* _poiMapTable;
}
@property(assign, nonatomic) VKClassicGlobeCanvas* canvas;	// @synthesize=_canvas
// declared property setter: -(void)setCanvas:(id)canvas;
// declared property getter: -(id)canvas;
-(XXStruct_taVrlB)pointForHandle:(id)handle atCoordinate:(XXStruct_zYrK5D)coordinate withHighPrecision:(BOOL)highPrecision;
-(void)removeHandle:(id)handle;
-(id)addHandleAtCoordinate:(XXStruct_zYrK5D)coordinate withHighPrecision:(BOOL)highPrecision;
-(void)dealloc;
-(id)init;
@end

