/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import "VectorKit-Structs.h"
#import "VKOverlay.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class GEOMapRegion;

__attribute__((visibility("hidden")))
@interface VKMultiPointOverlay : XXUnknownSuperclass <VKOverlay> {
@private
	CGSize* _points;
	unsigned _pointCount;
	XXStruct_HKaJvA _bounds;
	GEOMapRegion* _boundingMapRegion;
}
@property(readonly, assign, nonatomic) XXStruct_HKaJvA bounds;	// @synthesize=_bounds
@property(readonly, assign, nonatomic) CGSize* points;	// @synthesize=_points
@property(readonly, assign, nonatomic) unsigned pointCount;	// @synthesize=_pointCount
@property(readonly, assign, nonatomic) XXStruct_zYrK5D coordinate;
@property(readonly, assign, nonatomic) GEOMapRegion* boundingMapRegion;	// @synthesize=_boundingMapRegion
// declared property getter: -(id)boundingMapRegion;
// declared property getter: -(XXStruct_HKaJvA)bounds;
// declared property getter: -(unsigned)pointCount;
// declared property getter: -(CGSize*)points;
// declared property getter: -(XXStruct_zYrK5D)coordinate;
-(void)_setCoordinates:(XXStruct_zYrK5D*)coordinates count:(unsigned)count;
-(void)dealloc;
@end

