/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface VKPIconPack : XXUnknownSuperclass {
@private
	NSMutableArray* _atlas;
	NSMutableArray* _icons;
	unsigned _identifier;
}
@property(retain, nonatomic) NSMutableArray* icons;	// @synthesize=_icons
@property(retain, nonatomic) NSMutableArray* atlas;	// @synthesize=_atlas
@property(assign, nonatomic) unsigned identifier;	// @synthesize=_identifier
// declared property setter: -(void)setIcons:(id)icons;
// declared property getter: -(id)icons;
// declared property setter: -(void)setAtlas:(id)atlas;
// declared property getter: -(id)atlas;
// declared property setter: -(void)setIdentifier:(unsigned)identifier;
// declared property getter: -(unsigned)identifier;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)copyTo:(id)to;
-(void)writeTo:(id)to;
-(BOOL)readFrom:(id)from;
-(id)dictionaryRepresentation;
-(id)description;
-(id)iconsAtIndex:(unsigned)index;
-(unsigned)iconsCount;
-(void)addIcons:(id)icons;
-(void)clearIcons;
-(id)atlasAtIndex:(unsigned)index;
-(unsigned)atlasCount;
-(void)addAtlas:(id)atlas;
-(void)clearAtlas;
-(void)dealloc;
@end

