/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SelectorStringThread : XXUnknownSuperclass {
}
+(void)detachNewThreadSelector:(SEL)selector toTarget:(id)target withObject:(id)object;
@end

