/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import "StepByStepUIDevicePicker.h"
#import "StepByStepUIViewController_DevicePicker.h"

@class NSString, UIView, UILabel;

__attribute__((visibility("hidden")))
@interface StepByStepUIViewController_Join_Config : StepByStepUIViewController_DevicePicker <StepByStepUIDevicePicker> {
	UIView* tableHeaderContainerView;
	UIView* justTextContainerView;
	UILabel* justTextLabel;
	NSString* personalizedBaseName;
	unsigned productID;
	int deviceKind;
}
@property(retain, nonatomic) NSString* personalizedBaseName;	// @synthesize
@property(retain, nonatomic) UILabel* justTextLabel;	// @synthesize
@property(retain, nonatomic) UIView* justTextContainerView;	// @synthesize
@property(retain, nonatomic) UIView* tableHeaderContainerView;	// @synthesize
// declared property setter: -(void)setPersonalizedBaseName:(id)name;
// declared property getter: -(id)personalizedBaseName;
// declared property setter: -(void)setJustTextLabel:(id)label;
// declared property getter: -(id)justTextLabel;
// declared property setter: -(void)setJustTextContainerView:(id)view;
// declared property getter: -(id)justTextContainerView;
// declared property setter: -(void)setTableHeaderContainerView:(id)view;
// declared property getter: -(id)tableHeaderContainerView;
-(BOOL)showMoreOptions;
-(void)selectedDeviceUpdated;
-(id)devicePickerLabel;
-(id)deviceTableLabel;
-(void)setupDevices;
-(void)updateNavigationButtons;
-(void)prepareParams;
-(void)primaryActionSelected:(BOOL)selected;
-(void)setupHeaderAndFooter;
-(void)setupEditableBaseStationName;
-(void)textFieldDidChangeAtIndexPath:(id)textField;
-(BOOL)shouldChangeTextField:(id)field atIndexPath:(id)indexPath forTextIndex:(unsigned)textIndex toString:(id)string;
-(void)viewDidLoad;
-(void)syncTopoUIForTarget:(id)target andSource:(id)source andNetwork:(id)network connectionType:(id)type;
-(void)setupTable;
-(BOOL)isAirPlayDevice;
-(void)validateAndUpdateNextButton;
@end

