/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import "AirPortAssistant-Structs.h"
#import "UITextFieldDelegate.h"
#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDataSource.h"

@class UIView, NSMutableDictionary, UITableView, NSIndexPath, UIColor;
@protocol TableViewManagerDelegate;

__attribute__((visibility("hidden")))
@interface TableViewManager : XXUnknownSuperclass <UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource> {
	NSMutableDictionary* _tableDescriptorDict;
	UITableView* _managedTableView;
	id _delegate;
	NSIndexPath* _currentFirstResponderCellPath;
	UIView* _currentFirstResponder;
	BOOL _handlingBulkUpdate;
	float _cellLeftEdgeOrigin;
	float _cellContentWidth;
	UIColor* _blueGreyColor;
	UIColor* _subtitleColor;
}
@property(retain, nonatomic) UITableView* managedTableView;
@property(assign, nonatomic) id<TableViewManagerDelegate> delegate;
-(BOOL)tagOfCellAtIndexPath:(id)indexPath tag:(int*)tag;
-(id)indexPathOfCellWithTag:(int)tag;
-(unsigned)indexOfSectionWithIdentifier:(id)identifier;
-(unsigned)tagOfSelectedRowInMenuSection:(unsigned)menuSection;
-(unsigned)indexOfSelectedRowInMenuSection:(unsigned)menuSection;
-(id)cellInfoOfSelectedRowInMenuSection:(unsigned)menuSection;
-(void)selectMenuCellAtIndexPath:(id)indexPath;
-(void)bulkUpdateEnd;
-(void)bulkUpdateBegin;
-(void)segmentedControlValueChanged:(id)changed;
-(void)buttonAction:(id)action;
-(void)switchAction:(id)action;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)uiTextFieldDidChange:(id)uiTextField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)setRepresentedObject:(id)object forCellAtIndexPath:(id)indexPath;
-(void)updateFooter:(id)footer forSectionWithIdentifier:(id)identifier;
-(void)updateHeader:(id)header forSectionWithIdentifier:(id)identifier;
-(void)updateRowInfoValue:(id)value forKey:(id)key atIndexPath:(id)indexPath;
-(id)getRepresentedObjectForCellAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)findNextResponderInTableView:(id)tableView foundParentCell:(id*)cell;
-(id)findFirstResponderInTableView:(id)tableView foundParentCell:(id*)cell;
-(id)findFirstResponderInTableView:(id)tableView fromSection:(unsigned)section fromRow:(unsigned)row foundParentCell:(id*)cell;
-(id)findFirstResponderInView:(id)view;
-(void)makeFirstEditableCellCurrentResponder;
-(void)setNewRow:(id)row editingStyle:(int)style;
-(void)setNewRow:(id)row editingAccessoryType:(int)type;
-(void)setNewRow:(id)row validateAccessoryType:(int)type;
-(void)setNewRow:(id)row accessoryType:(int)type;
-(void)setNewRow:(id)row representedObject:(id)object;
-(void)setNewRow:(id)row tag:(unsigned)tag;
-(BOOL)setNewRow:(id)row itemAttribute:(id)attribute forItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex toValue:(id)value;
-(void)setValue:(id)value forItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCellAtIndexPath:(id)indexPath;
-(void)setValue:(id)value forItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCellWithTag:(int)tag;
-(id)getValueForItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCellWithTag:(int)tag;
-(id)getValueForFirstItemOfType:(id)type inCellWithTag:(int)tag;
-(id)getValueForFirstItemOfType:(id)type inCellAtIndexPath:(id)indexPath;
-(id)getValueForItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCellAtIndexPath:(id)indexPath;
-(id)getValueForItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCell:(id)cell;
-(id)getInfoForItemOfType:(id)type atItemTypeIndex:(unsigned)itemTypeIndex inCell:(id)cell;
-(unsigned)findAndSetItemObject:(id)object toValue:(id)value inCellWithTag:(unsigned)tag;
-(id)createRowStyleProgressViewWithCancelAndStatus:(id)cancelAndStatus statusText:(id)text altText:(id)text3 withTag:(unsigned)tag;
-(id)createRowStyleSegmentedControlWithItems:(id)items selectedSegmentIndex:(id)index enabled:(BOOL)enabled withTag:(unsigned)tag;
-(id)createRowStyleTitledParagraphWithLeftImage:(id)leftImage title:(id)title bodyText:(id)text withTag:(unsigned)tag;
-(id)createRowStyleTitledParagraph:(id)paragraph titleImage:(id)image bodyText:(id)text withTag:(unsigned)tag;
-(id)createRowStyleBasicButtons:(id)buttons title2:(id)a2 withTag:(unsigned)tag;
-(id)createRowStyleBasicWholeCellButton:(id)button withTag:(unsigned)tag;
-(id)createRowStyleBasicOnOffWithImage:(id)image labelText:(id)text isOn:(BOOL)on withTag:(unsigned)tag;
-(id)createRowStyleBasicEditableWithImage:(id)image labelText:(id)text currentValue:(id)value placeholderText:(id)text4 isSecure:(BOOL)secure keyboardType:(int)type withTag:(unsigned)tag;
-(id)createRowStyleBasicWithText:(id)text centerImage:(id)image text2:(id)a2 withTag:(unsigned)tag;
-(id)createRowStyleSubtitleWithRightText:(id)rightText subtitleText:(id)text rightText:(id)text3 withTag:(unsigned)tag;
-(id)createRowStyleSubtitleWithRightImage:(id)rightImage subtitleText:(id)text rightImage:(id)image withTag:(unsigned)tag;
-(id)createRowStyleBasicWithImage:(id)image text1:(id)a1 text2:(id)a2 withTag:(unsigned)tag;
-(id)commonAddOptionalStaticText:(id)text withNeighborItem:(id)neighborItem toCellItems:(id)cellItems;
-(id)commonAddOptionalBasicImage:(id)image withNeighborItem:(id)neighborItem toCellItems:(id)cellItems;
-(void)setSectionValue:(id)value forKey:(id)key inSection:(unsigned)section;
-(void)deleteSectionWithIdentifier:(id)identifier;
-(void)deleteSectionWithIdentifier:(id)identifier animated:(BOOL)animated;
-(void)deleteSection:(unsigned)section;
-(void)insertSectionInfo:(id)info atIndex:(unsigned)index withRowAnimation:(int)rowAnimation;
-(void)addSectionInfo:(id)info;
-(void)addSectionInfo:(id)info animated:(BOOL)animated;
-(void)recordInitialSelectedMenuItemsForNewSection:(int)newSection;
-(void)deleteSections:(id)sections withRowAnimation:(int)rowAnimation;
-(void)deleteAllRowsInSection:(unsigned)section;
-(void)deleteAllRowsInSectionCore:(unsigned)sectionCore;
-(void)cleanTableViewForReuse;
-(void)deleteRowInSection:(unsigned)section withTag:(int)tag;
-(void)deleteRowsAtIndexPaths:(id)indexPaths withRowAnimation:(int)rowAnimation;
-(void)appendNewRow:(id)row forSection:(unsigned)section;
-(void)insertNewRows:(id)rows atIndexPaths:(id)indexPaths withRowAnimation:(int)rowAnimation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
// declared property getter: -(id)delegate;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)managedTableView;
// declared property setter: -(void)setManagedTableView:(id)view;
-(void)dealloc;
-(id)init;
-(void)awakeFromNib;
-(void)initializeTableViewManagerCommon;
-(void)hideKeyboard;
-(void)endEditing;
-(void)informOfNewCellLeftEdge:(float)newCellLeftEdge andWidth:(float)width;
-(id)progressView:(id)view;
-(void)setProgressViewValue:(id)value usingItemInfo:(id)info;
-(id)segmentedControlView:(id)view;
-(id)buttonView:(id)view;
-(void)setButtonViewValue:(id)value usingItemInfo:(id)info;
-(id)activityView:(id)view;
-(void)setActivityViewValue:(id)value usingItemInfo:(id)info;
-(id)switchView:(id)view;
-(void)setSwitchViewValue:(id)value usingItemInfo:(id)info;
-(id)wholeCellButtonView:(id)view;
-(id)editTextView:(id)view;
-(void)setEditTextViewValue:(id)value usingItemInfo:(id)info;
-(id)multilineLabelView:(id)view;
-(void)setMultilineLabelViewValue:(id)value usingItemInfo:(id)info;
-(id)labelView:(id)view;
-(void)setLabelViewValue:(id)value usingItemInfo:(id)info;
-(void)updateValidateAccessoryView:(int)view forCell:(id)cell;
-(id)imageView:(id)view;
-(void)setImageViewValue:(id)value usingItemInfo:(id)info;
-(id)getRowArrayForSection:(unsigned)section;
-(void)setDescriptorObject:(id)object forKey:(id)key inSection:(int)section;
-(id)getDescriptorObjectForKey:(id)key inSection:(int)section;
-(id)getSectionDictForSection:(int)section;
-(void)setMenuCell:(id)cell visualStateToSelected:(BOOL)selected atIndexPath:(id)indexPath;
-(void)reloadSection:(unsigned)section;
-(id)getCellDictForCellAtIndexPath:(id)indexPath;
@end

