/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AirPortAssistant-Structs.h"

@class NSObject, NSTimer, NSMutableDictionary, NSDictionary;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface WiFiUtils : XXUnknownSuperclass {
	NSDictionary* _unmergedScanInfoDict;
	NSMutableDictionary* _missingBSSIDCounts;
	WiFiShimContext* _wifiShim;
	NSObject<OS_dispatch_semaphore>* _wifiBusy;
	BOOL _scanInProgress;
	BOOL _joinInProgress;
	BOOL _scanningActive;
	BOOL _scanOnlyWhenAppActive;
	NSTimer* _scanTimer;
}
@property(retain) NSTimer* _scanTimer;	// @synthesize
@property(retain) NSDictionary* unmergedScanInfoDict;	// converted property
@property(assign, getter=isJoinInProgress) BOOL joinInProgress;	// converted property
@property(assign, getter=isScanInProgress) BOOL scanInProgress;	// converted property
@property(readonly, assign, getter=isScanningActive) BOOL scanningActive;	// converted property
+(int)barsForRSSI:(int)rssi;
+(BOOL)networkIsApple:(id)apple productID:(unsigned*)anId;
+(BOOL)networkIsSecure:(id)secure secMode:(int*)mode isEnterprise:(BOOL*)enterprise;
+(id)getNetworkPassword:(id)password;
+(BOOL)scanInfoIsIBSS:(id)ibss;
+(BOOL)scanInfoIs5GHz:(id)hz;
+(void)sharedInstanceRelease;
+(id)sharedInstanceRef;
+(id)sharedInstance;
+(BOOL)stringArray:(id)array containsBSSID:(id)bssid;
// declared property setter: -(void)set_scanTimer:(id)timer;
// declared property getter: -(id)_scanTimer;
-(id)getNetworkPasswordForNetworkNamed:(id)networkNamed;
-(id)getPreferredNetworks:(BOOL)networks;
-(BOOL)isCurrentlyAssociatedToAnInfrastructureNetwork:(BOOL*)anInfrastructureNetwork;
-(BOOL)getAutoJoinState;
-(long)setAutoJoinState:(BOOL)state;
-(id)getLinkStatus;
-(id)getIfList;
-(id)getCurrentAssociationScanInfo;
-(id)getCurrentAssociationInfoOrNil;
-(id)getCurrentAssociationInfo;
-(long)scanInfoViaDirectedScanAsync:(id)async waitingForNetwork:(BOOL)network;
-(long)clearScanCacheSync;
-(long)dissassociateSync;
-(long)joinNetworkWithNameAsync:(id)nameAsync password:(id)password rememberChoice:(int)choice;
-(long)joinNetworkWithScanInfoAsync:(id)scanInfoAsync password:(id)password rememberChoice:(int)choice;
-(id)scanInfoForName:(id)name wifiType:(int)type;
-(id)scanInfoForMACAddress:(id)macaddress;
-(id)unconfiguredScanInfosOfType:(int)type;
-(id)mergedScanInfoArray;
-(id)unmergedScanInfoArray;
-(void)cancelAsync;
// converted property getter: -(BOOL)isJoinInProgress;
// converted property getter: -(BOOL)isScanInProgress;
// converted property getter: -(BOOL)isScanningActive;
-(void)activateScanning:(BOOL)scanning;
-(void)setScanOnlyWhenAppActive:(BOOL)active;
-(BOOL)airPortIsOn;
-(void)dealloc;
-(id)init;
// converted property setter: -(void)setUnmergedScanInfoDict:(id)dict;
// converted property getter: -(id)unmergedScanInfoDict;
-(void)mergeScanResults:(id)results;
-(void)asyncWiFiScanThread:(id)thread;
-(long)asyncWiFiScan:(BOOL)scan;
-(long)joinNetworkWithScanInfo:(id)scanInfo password:(id)password rememberChoice:(int)choice;
-(void)joinNetworkWithNameThread:(id)nameThread;
-(void)joinNetworkWithScanInfoThread:(id)scanInfoThread;
-(long)scanInfoViaDirectedScanSync:(id)sync scanInfo:(id*)info;
-(void)scanInfoViaDirectedScanThread:(id)thread;
// converted property setter: -(void)setJoinInProgress:(BOOL)progress;
// converted property setter: -(void)setScanInProgress:(BOOL)progress;
-(void)triggerScan;
-(void)scanTimerCallback:(id)callback;
-(long)closeWiFi;
-(long)openWiFi;
@end

