/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import "MCPayload.h"

@class NSArray;

@interface MCAPNPayload : MCPayload {
	NSArray* _apnInfos;
	BOOL _wasInstalled;
}
@property(assign, nonatomic) BOOL wasInstalled;	// @synthesize=_wasInstalled
+(id)apnDomainName;
+(id)localizedDescriptionForPayloadCount:(unsigned)payloadCount;
+(id)typeStrings;
// declared property setter: -(void)setWasInstalled:(BOOL)installed;
// declared property getter: -(BOOL)wasInstalled;
-(void).cxx_destruct;
-(id)subtitle2Description;
-(id)subtitle2Label;
-(id)subtitle1Description;
-(id)subtitle1Label;
-(id)description;
-(id)stubDictionary;
-(id)_strippedAPNDefaults;
-(id)apnDefaults;
-(id)initWithDictionary:(id)dictionary profile:(id)profile outError:(id*)error;
-(void)_finishInitializationWithContents:(id)contents;
-(BOOL)_checkForValidContents:(id)validContents outError:(id*)error;
-(id)_validationErrorType:(int)type forInvalidKey:(id)invalidKey;
@end

