/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MCARCHacks : XXUnknownSuperclass {
}
+(id)performSelector:(SEL)selector withReturnedObjectOnClass:(Class)returnedObjectOnClass withObject:(id)object;
+(void)performSelector:(SEL)selector onClass:(Class)aClass withObject:(id)object;
@end

