/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import "ManagedConfiguration-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (MCUtilities)
-(id)MCRetainOptionalNonZeroLengthStringKey:(id)key errorDomain:(id)domain invalidDataCode:(int)code invalidDataErrorString:(id)string outError:(id*)error;
-(id)MCRetainRequiredNonZeroLengthStringKey:(id)key errorDomain:(id)domain missingDataCode:(int)code missingDataErrorString:(id)string invalidDataCode:(int)code5 invalidDataErrorString:(id)string6 outError:(id*)error;
-(id)MCRetainOptionalObjectKey:(id)key type:(Class)type errorDomain:(id)domain invalidDataCode:(int)code invalidDataErrorString:(id)string outError:(id*)error;
-(id)MCRetainRequiredObjectKey:(id)key type:(Class)type errorDomain:(id)domain missingDataCode:(int)code missingDataErrorString:(id)string invalidDataCode:(int)code6 invalidDataErrorString:(id)string7 outError:(id*)error;
-(id)MCDeepCopy;
-(id)MCDeepCopyWithZone:(NSZone*)zone;
-(id)MCMutableDeepCopy;
-(id)MCMutableDeepCopyWithZone:(NSZone*)zone;
@end

@interface XXUnknownSuperclass (MCUtilities)
-(void)MCSetObjectIfNotNil:(id)aNil forKey:(id)key;
-(void)MCDeepCopyMissingEntriesFromDictionary:(id)dictionary;
-(void)MCDeepCopyEntriesFromDictionary:(id)dictionary;
@end

@interface XXUnknownSuperclass (MCExtension)
+(id)MCErrorWithDomain:(id)domain code:(int)code descriptionArray:(id)array suggestion:(id)suggestion USEnglishSuggestion:(id)suggestion5 underlyingError:(id)error errorType:(id)type;
+(id)MCErrorWithDomain:(id)domain code:(int)code descriptionArray:(id)array underlyingError:(id)error errorType:(id)type;
+(id)MCErrorWithDomain:(id)domain code:(int)code descriptionArray:(id)array errorType:(id)type;
+(id)MCErrorWithDomain:(id)domain code:(int)code description:(id)description errorType:(id)type;
-(id)MCErrorType;
-(id)MCUSEnglishSuggestion;
-(id)MCUSEnglishDescription;
-(BOOL)MCContainsErrorDomain:(id)domain code:(int)code;
-(id)MCMakePrimaryError;
-(id)MCFindPrimaryError;
-(id)MCVerboseDescription;
@end

@interface XXUnknownSuperclass (MCUtilities)
+(id)MCMakeUUID;
-(id)MCAppendDeviceName;
-(id)MCSHA256DigestWithSalt;
-(id)MCSafeFilenameHashWithExtension:(id)extension;
-(id)MCSafeFilenameHash;
@end

@interface XXUnknownSuperclass (ManagedConfiguration)
+(id)MCDataWithCFData:(CFDataRef)cfdata;
+(id)MCDataWithHexString:(id)hexString;
-(id)MCHexString;
@end

@interface XXUnknownSuperclass (MCHacks)
-(id)MCAppendGreenteaSuffix;
@end

@interface XXUnknownSuperclass (MCHacks)
-(void)MCFixUpRestrictionsDictionaryForMDMReporting;
@end

