/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSHTTPURLResponse, NSError, NSDictionary;

@interface AAResponse : XXUnknownSuperclass {
	NSDictionary* _responseDictionary;
	NSHTTPURLResponse* _httpResponse;
	NSError* _error;
}
@property(readonly, assign, nonatomic) NSString* protocolVersion;
@property(retain, nonatomic) NSError* error;	// @synthesize=_error
@property(readonly, assign, nonatomic) NSDictionary* responseDictionary;	// @synthesize=_responseDictionary
// declared property setter: -(void)setError:(id)error;
// declared property getter: -(id)error;
// declared property getter: -(id)responseDictionary;
-(void).cxx_destruct;
// declared property getter: -(id)protocolVersion;
-(id)initWithHTTPResponse:(id)httpresponse data:(id)data bodyIsPlist:(BOOL)plist;
-(id)initWithHTTPResponse:(id)httpresponse data:(id)data;
-(void)_parsePlistResponse:(id)response;
@end

