/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

#import <Accounts/ACAccount.h>


@interface ACAccount (AppleID)
-(BOOL)canRemoveAccount;
-(id)_registeredBundles;
-(void)unregisterBundle:(id)bundle;
-(void)registerBundle:(id)bundle;
-(id)dsid;
-(void)setDSID:(id)dsid;
-(id)appleID;
-(id)initWithAppleID:(id)appleID password:(id)password;
@end

