/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import "ImageCapture-Structs.h"
#import "ICDevice.h"

@class NSArray, NSString;

@interface ICCameraDevice : ICDevice {
@private
	void* _cameraProperties;
}
@property(assign) BOOL beingEjected;
@property(copy) NSString* volumePath;
@property(readonly, assign) NSArray* contents;
@property(assign, getter=isAccessRestrictedAppleDevice) BOOL accessRestrictedAppleDevice;
@property(assign) unsigned numberOfDownloadableItems;
@property(readonly, assign) double timeOffset;
@property(readonly, assign) unsigned batteryLevel;
@property(readonly, assign) BOOL batteryLevelAvailable;
@property(readonly, assign) NSArray* mediaFiles;
@property(assign) BOOL allowsSyncingClock;
@property(assign, getter=isLocked) BOOL locked;
@property(assign, getter=isEjectable) BOOL ejectable;
@property(assign) unsigned contentCatalogPercentCompleted;
@property(assign) unsigned estimatedNumberOfDownloadableItems;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(void)receivedDeviceCommandCompletion;
-(void)addToMetadataFetchQ:(id)metadataFetchQ;
-(void)addToThumbnailFetchQ:(id)thumbnailFetchQ;
-(void)removeFolder:(id)folder;
-(void)addFolder:(id)folder;
-(void)cancelDownload;
-(void)requestDownloadFile:(id)file options:(id)options downloadDelegate:(id)delegate didDownloadSelector:(SEL)selector contextInfo:(void*)info;
-(void)requestEject;
-(void)requestDeleteFiles:(id)files;
-(void)requestSyncClock;
-(void)requestCloseSession;
-(void)requestOpenSession;
-(void)handleImageCaptureEventNotification:(id)notification;
-(void)handleCommandCompletionNotification:(id)notification;
-(id)filesOfType:(id)type;
// declared property getter: -(id)mediaFiles;
// declared property getter: -(id)contents;
-(void)pendNotifyingDelegateOfAddedItem:(id)addedItem;
-(void)notifyDelegateOfAddedItem:(id)addedItem;
-(dispatch_semaphore_s*)deviceQSemaphore;
-(dispatch_queue_s*)generalQ;
// declared property setter: -(void)setAccessRestrictedAppleDevice:(BOOL)device;
// declared property getter: -(BOOL)isAccessRestrictedAppleDevice;
// declared property setter: -(void)setContentCatalogPercentCompleted:(unsigned)completed;
// declared property getter: -(unsigned)contentCatalogPercentCompleted;
-(void)incrementNumberOfDownloadableItems;
-(void)decrementNumberOfDownloadableItems;
// declared property setter: -(void)setNumberOfDownloadableItems:(unsigned)downloadableItems;
// declared property getter: -(unsigned)numberOfDownloadableItems;
-(void)incrementEstimatedNumberOfDownloadableItems;
-(void)decrementEstimatedNumberOfDownloadableItems;
// declared property setter: -(void)setEstimatedNumberOfDownloadableItems:(unsigned)downloadableItems;
// declared property getter: -(unsigned)estimatedNumberOfDownloadableItems;
-(double)downloadCancelTimestamp;
// declared property getter: -(double)timeOffset;
// declared property getter: -(unsigned)batteryLevel;
// declared property getter: -(BOOL)batteryLevelAvailable;
// declared property setter: -(void)setAllowsSyncingClock:(BOOL)clock;
// declared property getter: -(BOOL)allowsSyncingClock;
// declared property setter: -(void)setLocked:(BOOL)locked;
// declared property getter: -(BOOL)isLocked;
// declared property setter: -(void)setBeingEjected:(BOOL)ejected;
// declared property getter: -(BOOL)beingEjected;
// declared property setter: -(void)setEjectable:(BOOL)ejectable;
// declared property getter: -(BOOL)isEjectable;
// declared property setter: -(void)setVolumePath:(id)path;
// declared property getter: -(id)volumePath;
-(void)finalize;
-(void)dealloc;
-(id)description;
-(id)init;
@end

