/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface PTPProbeResponsePacket : XXUnknownSuperclass {
}
-(id)description;
-(id)contentForTCP;
-(id)initWithTCPBuffer:(void*)tcpbuffer;
@end

