/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSString, NSArray, NSURL, NSNumber;

@interface SAAlarmSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSNumber* minute;
@property(copy, nonatomic) NSString* label;
@property(copy, nonatomic) NSURL* identifier;
@property(copy, nonatomic) NSNumber* hour;
@property(copy, nonatomic) NSArray* frequency;
@property(copy, nonatomic) NSNumber* enabled;
@property(copy, nonatomic) NSURL* targetAppId;
+(id)searchWithDictionary:(id)dictionary context:(id)context;
+(id)search;
-(BOOL)requiresResponse;
// declared property setter: -(void)setMinute:(id)minute;
// declared property getter: -(id)minute;
// declared property setter: -(void)setLabel:(id)label;
// declared property getter: -(id)label;
// declared property setter: -(void)setIdentifier:(id)identifier;
// declared property getter: -(id)identifier;
// declared property setter: -(void)setHour:(id)hour;
// declared property getter: -(id)hour;
// declared property setter: -(void)setFrequency:(id)frequency;
// declared property getter: -(id)frequency;
// declared property setter: -(void)setEnabled:(id)enabled;
// declared property getter: -(id)enabled;
// declared property setter: -(void)setTargetAppId:(id)anId;
// declared property getter: -(id)targetAppId;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

