/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray;

@interface SAAppsGetRestrictedApps : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray* appIds;
+(id)getRestrictedAppsWithDictionary:(id)dictionary context:(id)context;
+(id)getRestrictedApps;
-(BOOL)requiresResponse;
// declared property setter: -(void)setAppIds:(id)ids;
// declared property getter: -(id)appIds;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

