/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSString, NSArray, NSDictionary;

@interface SAAppInfo : SADomainObject {
}
@property(copy, nonatomic) NSArray* supportedSchemes;
@property(copy, nonatomic) NSArray* supportedCommands;
@property(copy, nonatomic) NSDictionary* spotlightNameMap;
@property(copy, nonatomic) NSString* spotlightName;
@property(copy, nonatomic) NSString* providerName;
@property(copy, nonatomic) NSDictionary* displayAppNameMap;
@property(copy, nonatomic) NSString* displayAppName;
@property(copy, nonatomic) NSString* appVersion;
@property(copy, nonatomic) NSDictionary* appNameMap;
@property(copy, nonatomic) NSString* appName;
@property(copy, nonatomic) NSString* appId;
+(id)appInfoWithDictionary:(id)dictionary context:(id)context;
+(id)appInfo;
-(void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
// declared property setter: -(void)setSupportedSchemes:(id)schemes;
// declared property getter: -(id)supportedSchemes;
// declared property setter: -(void)setSupportedCommands:(id)commands;
// declared property getter: -(id)supportedCommands;
// declared property setter: -(void)setSpotlightNameMap:(id)map;
// declared property getter: -(id)spotlightNameMap;
// declared property setter: -(void)setSpotlightName:(id)name;
// declared property getter: -(id)spotlightName;
// declared property setter: -(void)setProviderName:(id)name;
// declared property getter: -(id)providerName;
// declared property setter: -(void)setDisplayAppNameMap:(id)map;
// declared property getter: -(id)displayAppNameMap;
// declared property setter: -(void)setDisplayAppName:(id)name;
// declared property getter: -(id)displayAppName;
// declared property setter: -(void)setAppVersion:(id)version;
// declared property getter: -(id)appVersion;
// declared property setter: -(void)setAppNameMap:(id)map;
// declared property getter: -(id)appNameMap;
// declared property setter: -(void)setAppName:(id)name;
// declared property getter: -(id)appName;
// declared property setter: -(void)setAppId:(id)anId;
// declared property getter: -(id)appId;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

