/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL;

@interface SACalendarDefaultSourceGet : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSURL* targetAppId;
+(id)defaultSourceGetWithDictionary:(id)dictionary context:(id)context;
+(id)defaultSourceGet;
-(BOOL)requiresResponse;
// declared property setter: -(void)setTargetAppId:(id)anId;
// declared property getter: -(id)targetAppId;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

