/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSString, NSURL;

@interface SAClockAddCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* refId;	// @dynamic
@property(copy, nonatomic) NSString* aceId;	// @dynamic
@property(copy, nonatomic) NSURL* worldClockId;
@property(assign, nonatomic) BOOL alreadyExists;
+(id)addCompletedWithDictionary:(id)dictionary context:(id)context;
+(id)addCompleted;
// declared property setter: -(void)setWorldClockId:(id)anId;
// declared property getter: -(id)worldClockId;
// declared property setter: -(void)setAlreadyExists:(BOOL)exists;
// declared property getter: -(BOOL)alreadyExists;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

