/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SABaseCommand.h"

@class SALocalSearchAceNavigationEta, NSNumber, NSString, SALocalSearchRoute;

@interface SALocalSearchGetNavigationStatusCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* refId;	// @dynamic
@property(copy, nonatomic) NSString* aceId;	// @dynamic
@property(retain, nonatomic) SALocalSearchRoute* route;
@property(retain, nonatomic) SALocalSearchAceNavigationEta* overallEta;
@property(retain, nonatomic) SALocalSearchAceNavigationEta* nextManeuverEta;
@property(retain, nonatomic) NSNumber* navigating;
@property(retain, nonatomic) NSNumber* etaInMinutes;
+(id)getNavigationStatusCompletedWithDictionary:(id)dictionary context:(id)context;
+(id)getNavigationStatusCompleted;
// declared property setter: -(void)setRoute:(id)route;
// declared property getter: -(id)route;
// declared property setter: -(void)setOverallEta:(id)eta;
// declared property getter: -(id)overallEta;
// declared property setter: -(void)setNextManeuverEta:(id)eta;
// declared property getter: -(id)nextManeuverEta;
// declared property setter: -(void)setNavigating:(id)navigating;
// declared property getter: -(id)navigating;
// declared property setter: -(void)setEtaInMinutes:(id)minutes;
// declared property getter: -(id)etaInMinutes;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

