/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSArray;

@interface SAObjectSupport : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSArray* supportedProperties;
@property(copy, nonatomic) NSString* groupId;
@property(copy, nonatomic) NSString* classId;
@property(copy, nonatomic) NSString* aceVersion;
+(id)objectSupportWithDictionary:(id)dictionary context:(id)context;
+(id)objectSupport;
// declared property setter: -(void)setSupportedProperties:(id)properties;
// declared property getter: -(id)supportedProperties;
// declared property setter: -(void)setGroupId:(id)anId;
// declared property getter: -(id)groupId;
// declared property setter: -(void)setClassId:(id)anId;
// declared property getter: -(id)classId;
// declared property setter: -(void)setAceVersion:(id)version;
// declared property getter: -(id)aceVersion;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

