/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSString;

@interface SAReminderListObject : SADomainObject {
}
@property(copy, nonatomic) NSString* name;
+(id)listObjectWithDictionary:(id)dictionary context:(id)context;
+(id)listObject;
-(void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
// declared property setter: -(void)setName:(id)name;
// declared property getter: -(id)name;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

