/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSNumber;

@interface SAWeatherWindSpeed : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSNumber* windDirectionDegree;
@property(copy, nonatomic) NSString* windDirection;
@property(copy, nonatomic) NSString* value;
+(id)windSpeedWithDictionary:(id)dictionary context:(id)context;
+(id)windSpeed;
// declared property setter: -(void)setWindDirectionDegree:(id)degree;
// declared property getter: -(id)windDirectionDegree;
// declared property setter: -(void)setWindDirection:(id)direction;
// declared property getter: -(id)windDirection;
// declared property setter: -(void)setValue:(id)value;
// declared property getter: -(id)value;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

