/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSString, NSArray;

@interface SAWeatherLocationSearchCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* refId;	// @dynamic
@property(copy, nonatomic) NSString* aceId;	// @dynamic
@property(copy, nonatomic) NSArray* weatherLocations;
+(id)locationSearchCompletedWithWeatherLocations:(id)weatherLocations;
+(id)locationSearchCompletedWithDictionary:(id)dictionary context:(id)context;
+(id)locationSearchCompleted;
// declared property setter: -(void)setWeatherLocations:(id)locations;
// declared property getter: -(id)weatherLocations;
-(id)initWithWeatherLocations:(id)weatherLocations;
-(id)encodedClassName;
-(id)groupIdentifier;
@end

