/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

#import "NSURLConnectionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLConnection, NSMutableData, NSURLRequest;

@interface RUIHTTPRequest : XXUnknownSuperclass <NSURLConnectionDelegate> {
	NSURLRequest* _request;
	NSURLConnection* _connection;
	NSMutableData* _rawData;
	BOOL _invalidResponse;
	id _delegate;
}
@property(readonly, retain) NSURLRequest* request;	// converted property
+(id)safeBaseURL;
+(BOOL)anyRequestLoading;
+(id)nonSecureConnectionNotAllowedError;
+(id)invalidResponseError;
+(id)serviceUnavailableError;
-(BOOL)receivedValidResponse:(id)response;
-(void)failWithError:(id)error;
-(void)parseData:(id)data;
-(void)didParseData;
-(void)willParseData;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
// converted property getter: -(id)request;
-(void)loadStatusChanged;
-(BOOL)isLoading;
-(void)cancel;
-(void)loadRequest:(id)request;
-(BOOL)loggingEnabled;
-(void)_finishedLoading;
-(void)_startedLoading;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
-(id)init;
@end

