/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

#import "IMAttributedStringParserContext.h"
#import "IMFoundation-Structs.h"

@class NSMutableArray, NSArray;

@interface IMFromSuperParserContext : IMAttributedStringParserContext {
	NSMutableArray* _inlinedFileTransferGUIDs;
	NSMutableArray* _standaloneFileTransferGUIDs;
}
@property(readonly, assign, nonatomic) NSArray* standaloneFileTransferGUIDs;	// @synthesize=_standaloneFileTransferGUIDs
@property(readonly, assign, nonatomic) NSArray* inlinedFileTransferGUIDs;	// @synthesize=_inlinedFileTransferGUIDs
// declared property getter: -(id)standaloneFileTransferGUIDs;
// declared property getter: -(id)inlinedFileTransferGUIDs;
-(void)parser:(id)parser foundAttributes:(id)attributes inRange:(NSRange)range fileTransferGUID:(id)guid filename:(id)filename bookmark:(id)bookmark width:(id)width height:(id)height;
-(void)parser:(id)parser foundAttributes:(id)attributes inRange:(NSRange)range characters:(id)characters;
-(void)parserDidStart:(id)parser bodyAttributes:(id)attributes;
-(void)parser:(id)parser foundAttributes:(id)attributes inRange:(NSRange)range;
-(void)parserDidStart:(id)parser;
-(id)resultsForLogging;
-(id)name;
-(void)dealloc;
-(id)initWithAttributedString:(id)attributedString;
@end

