/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSString;
@protocol OS_xpc_object;

@interface IMRemoteObject : XXUnknownSuperclass {
	id _internal;
}
@property(readonly, assign, nonatomic) BOOL isValid;
@property(readonly, assign, nonatomic) NSObject<OS_xpc_object>* connection;
@property(assign, nonatomic) int pid;
@property(readonly, assign, nonatomic) NSString* portName;
+(void)initialize;
+(void)_unregisterIMRemoteObject:(id)object;
+(void)_registerIMRemoteObject:(id)object;
+(id)_remoteObjects;
-(id)_queue;
-(id)description;
-(void)invalidate;
-(void)setPortName:(id)name;
// declared property getter: -(id)portName;
// declared property setter: -(void)setPid:(int)pid;
// declared property getter: -(int)pid;
// declared property getter: -(id)connection;
-(void)forwardInvocation:(id)invocation;
-(unsigned)forwardXPCObject:(id)object;
-(id)methodSignatureForSelector:(SEL)selector;
-(void)_systemShutdown:(id)shutdown;
// declared property getter: -(BOOL)isValid;
-(void)_portDidBecomeInvalid;
-(void)dealloc;
-(void)finalize;
-(void)_cleanupMachBitsCanPost:(BOOL)post;
-(id)initWithConnection:(id)connection protocol:(id)protocol alreadyConfigured:(BOOL)configured;
-(id)initWithPortName:(id)portName protocol:(id)protocol;
-(id)initWithConnection:(id)connection protocol:(id)protocol;
-(id)_initWithConnection:(id)connection portName:(id)name protocol:(id)protocol alreadyConfigured:(BOOL)configured;
@end

