/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface CPTextLineMerge : XXUnknownSuperclass {
	NSMutableArray* avail;
}
-(void)mergeLinesIn:(id)anIn;
-(void)dropCaps:(id)caps to:(id)to;
-(float)averageHeight:(id)height;
-(id)findLineFor:(id)aFor in:(id)anIn;
-(void)detachDropCaps:(id)caps to:(id)to;
-(unsigned)countOverlapsOfLineAtIndex:(unsigned)index in:(id)anIn;
-(void)removeOverlapping:(id)overlapping;
-(void)makeOverlappingLinesTo:(id)to;
-(BOOL)hasOverlappingLines;
-(void)eliminate:(id)eliminate;
-(void)mergeByColumn:(id)column;
-(void)mergeLinesInInterval:(id)interval from:(id)from;
-(void)mergeColumn:(id)column;
-(void)addInterval:(id)interval to:(id)to;
-(BOOL)fits:(id)fits into:(id)into;
@end

