/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSXMLParserDelegate.h"

@class NSMutableString, UIPDFAnnotation;

@interface UIPDFAnnotationParserDelegate : XXUnknownSuperclass <NSXMLParserDelegate> {
	NSMutableString* _characters;
	BOOL _parseError;
@private
	UIPDFAnnotation* _annotation;
}
@property(readonly, assign, nonatomic) BOOL parseError;	// @synthesize=_parseError
@property(retain, nonatomic) UIPDFAnnotation* annotation;	// @synthesize=_annotation
// declared property getter: -(BOOL)parseError;
// declared property setter: -(void)setAnnotation:(id)annotation;
// declared property getter: -(id)annotation;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parser:(id)parser foundCharacters:(id)characters;
-(void)parserDidStartDocument:(id)parser;
-(void)parser:(id)parser parseErrorOccurred:(id)occurred;
-(void)dealloc;
-(id)init;
@end

