/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SocialDaemon.framework/SocialDaemon
 */

#import "SLDServiceDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface SLDFacebookServiceDelegate : XXUnknownSuperclass <SLDServiceDelegate> {
	NSMutableDictionary* _ssoDialogCache;
}
@property(retain) NSMutableDictionary* ssoDialogCache;	// @synthesize=_ssoDialogCache
// declared property setter: -(void)setSsoDialogCache:(id)cache;
// declared property getter: -(id)ssoDialogCache;
-(void).cxx_destruct;
-(void)_observeBackgroundTaskAgent;
-(void)service:(id)service didInitWithServer:(id)server;
-(id)createSessionWithService:(id)service managedObjectContext:(id)context;
-(id)xpcServiceName;
@end

