/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import "GeoServices-Structs.h"
#import "_GEORegionalResourcesNode.h"


__attribute__((visibility("hidden")))
@interface _GEORegionalResourcesMultiNode : _GEORegionalResourcesNode {
@private
	XXStruct_1aFH4A* _regions;
	unsigned _regionsCount;
}
-(BOOL)containsTileKey:(GEOTileKey*)key;
-(void)dealloc;
-(id)initWithRegions:(XXStruct_1aFH4A*)regions count:(unsigned)count;
@end

