/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSData, NSString;

__attribute__((visibility("hidden")))
@interface _GEOResourceInfo : XXUnknownSuperclass {
@private
	NSString* _name;
	NSURL* _url;
	NSData* _data;
	NSString* _onDiskPath;
}
@property(copy, nonatomic) NSString* onDiskPath;	// @synthesize=_onDiskPath
@property(retain, nonatomic) NSData* data;	// @synthesize=_data
@property(retain, nonatomic) NSURL* url;	// @synthesize=_url
@property(copy, nonatomic) NSString* name;	// @synthesize=_name
// declared property setter: -(void)setOnDiskPath:(id)path;
// declared property getter: -(id)onDiskPath;
// declared property setter: -(void)setData:(id)data;
// declared property getter: -(id)data;
// declared property setter: -(void)setUrl:(id)url;
// declared property getter: -(id)url;
// declared property setter: -(void)setName:(id)name;
// declared property getter: -(id)name;
-(void)dealloc;
@end

