/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface GEOLanguage : PBCodable {
@private
	unsigned _identifier;
	NSMutableArray* _languages;
}
@property(retain, nonatomic) NSMutableArray* languages;	// @synthesize=_languages
@property(assign, nonatomic) unsigned identifier;	// @synthesize=_identifier
// declared property setter: -(void)setLanguages:(id)languages;
// declared property getter: -(id)languages;
// declared property setter: -(void)setIdentifier:(unsigned)identifier;
// declared property getter: -(unsigned)identifier;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)copyTo:(id)to;
-(void)writeTo:(id)to;
-(BOOL)readFrom:(id)from;
-(id)dictionaryRepresentation;
-(id)description;
-(id)languageAtIndex:(unsigned)index;
-(unsigned)languagesCount;
-(void)addLanguage:(id)language;
-(void)clearLanguages;
-(void)dealloc;
@end

