/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "GeoServices-Structs.h"


@interface GEOLocationShiftFunctionResponse : XXUnknownSuperclass {
@private
	XXStruct_zYrK5D _originalCoordinate;
	XXStruct_zYrK5D _shiftedCoordinate;
	double _creationTime;
}
@property(assign, nonatomic) XXStruct_zYrK5D originalCoordinate;	// @synthesize=_originalCoordinate
// declared property setter: -(void)setOriginalCoordinate:(XXStruct_zYrK5D)coordinate;
// declared property getter: -(XXStruct_zYrK5D)originalCoordinate;
-(BOOL)needsNewFunctionForCoordinate:(XXStruct_zYrK5D)coordinate;
-(BOOL)wantsNewFunctionForCoordinate:(XXStruct_zYrK5D)coordinate;
-(XXStruct_zYrK5D)shiftedCoordinateForCoordinate:(XXStruct_zYrK5D)coordinate accuracy:(double*)accuracy;
-(id)initWithLocationShiftResponse:(id)locationShiftResponse originalCoordinate:(XXStruct_zYrK5D)coordinate;
@end

