/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <ProtocolBuffer/PBCodable.h>
#import "GeoServices-Structs.h"

@class NSMutableArray, NSString;

@interface GEOPhoto : PBCodable {
@private
	NSMutableArray* _photoInfos;
	int _photoType;
	NSString* _uid;
	XXStruct_ec15KC _has;
}
@property(retain, nonatomic) NSString* uid;	// @synthesize=_uid
@property(readonly, assign, nonatomic) BOOL hasUid;
@property(retain, nonatomic) NSMutableArray* photoInfos;	// @synthesize=_photoInfos
@property(assign, nonatomic) int photoType;	// @synthesize=_photoType
@property(assign, nonatomic) BOOL hasPhotoType;
// declared property setter: -(void)setUid:(id)uid;
// declared property getter: -(id)uid;
// declared property setter: -(void)setPhotoInfos:(id)infos;
// declared property getter: -(id)photoInfos;
// declared property getter: -(int)photoType;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)copyTo:(id)to;
-(void)writeTo:(id)to;
-(BOOL)readFrom:(id)from;
-(id)dictionaryRepresentation;
-(id)description;
// declared property getter: -(BOOL)hasUid;
-(id)photoInfoAtIndex:(unsigned)index;
-(unsigned)photoInfosCount;
-(void)addPhotoInfo:(id)info;
-(void)clearPhotoInfos;
// declared property getter: -(BOOL)hasPhotoType;
// declared property setter: -(void)setHasPhotoType:(BOOL)type;
// declared property setter: -(void)setPhotoType:(int)type;
-(void)dealloc;
@end

