/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import "GeoServices-Structs.h"
#import <ProtocolBuffer/PBCodable.h>

@class NSString, GEONameInfo, NSMutableArray;

@interface GEOStep : PBCodable {
@private
	XXStruct_TrK5YA* _laneGuidances;
	unsigned _laneGuidancesCount;
	unsigned _laneGuidancesSpace;
	XXStruct_DtYHXC* _junctionElements;
	unsigned _junctionElementsCount;
	unsigned _junctionElementsSpace;
	unsigned _distance;
	GEONameInfo* _exitNumber;
	unsigned _expectedTime;
	int _hintFirstAnnouncementZilchIndex;
	NSString* _instructions;
	int _junctionType;
	int _maneuverEndBasicIndex;
	int _maneuverEndZilchIndex;
	NSMutableArray* _maneuverNames;
	int _maneuverStartZilchIndex;
	int _maneuverType;
	NSString* _notice;
	int _overrideDrivingSide;
	int _overrideTransportType;
	NSMutableArray* _signposts;
	unsigned _stepID;
	struct {
		unsigned distance : 1;
		unsigned expectedTime : 1;
		unsigned hintFirstAnnouncementZilchIndex : 1;
		unsigned junctionType : 1;
		unsigned maneuverEndBasicIndex : 1;
		unsigned maneuverEndZilchIndex : 1;
		unsigned maneuverStartZilchIndex : 1;
		unsigned maneuverType : 1;
		unsigned overrideDrivingSide : 1;
		unsigned overrideTransportType : 1;
		unsigned stepID : 1;
	} _has;
}
@property(retain, nonatomic) NSString* notice;	// @synthesize=_notice
@property(readonly, assign, nonatomic) BOOL hasNotice;
@property(retain, nonatomic) NSString* instructions;	// @synthesize=_instructions
@property(readonly, assign, nonatomic) BOOL hasInstructions;
@property(retain, nonatomic) GEONameInfo* exitNumber;	// @synthesize=_exitNumber
@property(readonly, assign, nonatomic) BOOL hasExitNumber;
@property(assign, nonatomic) int overrideDrivingSide;	// @synthesize=_overrideDrivingSide
@property(assign, nonatomic) BOOL hasOverrideDrivingSide;
@property(assign, nonatomic) int overrideTransportType;	// @synthesize=_overrideTransportType
@property(assign, nonatomic) BOOL hasOverrideTransportType;
@property(assign, nonatomic) int hintFirstAnnouncementZilchIndex;	// @synthesize=_hintFirstAnnouncementZilchIndex
@property(assign, nonatomic) BOOL hasHintFirstAnnouncementZilchIndex;
@property(retain, nonatomic) NSMutableArray* signposts;	// @synthesize=_signposts
@property(readonly, assign, nonatomic) XXStruct_DtYHXC* junctionElements;
@property(readonly, assign, nonatomic) unsigned junctionElementsCount;
@property(assign, nonatomic) int junctionType;	// @synthesize=_junctionType
@property(assign, nonatomic) BOOL hasJunctionType;
@property(readonly, assign, nonatomic) XXStruct_TrK5YA* laneGuidances;
@property(readonly, assign, nonatomic) unsigned laneGuidancesCount;
@property(retain, nonatomic) NSMutableArray* maneuverNames;	// @synthesize=_maneuverNames
@property(assign, nonatomic) int maneuverType;	// @synthesize=_maneuverType
@property(assign, nonatomic) BOOL hasManeuverType;
@property(assign, nonatomic) unsigned expectedTime;	// @synthesize=_expectedTime
@property(assign, nonatomic) BOOL hasExpectedTime;
@property(assign, nonatomic) unsigned distance;	// @synthesize=_distance
@property(assign, nonatomic) BOOL hasDistance;
@property(assign, nonatomic) int maneuverEndZilchIndex;	// @synthesize=_maneuverEndZilchIndex
@property(assign, nonatomic) BOOL hasManeuverEndZilchIndex;
@property(assign, nonatomic) int maneuverStartZilchIndex;	// @synthesize=_maneuverStartZilchIndex
@property(assign, nonatomic) BOOL hasManeuverStartZilchIndex;
@property(assign, nonatomic) int maneuverEndBasicIndex;	// @synthesize=_maneuverEndBasicIndex
@property(assign, nonatomic) BOOL hasManeuverEndBasicIndex;
@property(assign, nonatomic) unsigned stepID;	// @synthesize=_stepID
@property(assign, nonatomic) BOOL hasStepID;
@property(readonly, assign, nonatomic) int hintFirstAnnouncementIndex;
@property(readonly, assign, nonatomic) BOOL hasHintFirstAnnouncementIndex;
@property(readonly, assign, nonatomic) unsigned maneuverStartIndex;
@property(readonly, assign, nonatomic) unsigned maneuverEndIndex;
// declared property setter: -(void)setNotice:(id)notice;
// declared property getter: -(id)notice;
// declared property setter: -(void)setInstructions:(id)instructions;
// declared property getter: -(id)instructions;
// declared property setter: -(void)setExitNumber:(id)number;
// declared property getter: -(id)exitNumber;
// declared property getter: -(int)overrideDrivingSide;
// declared property getter: -(int)overrideTransportType;
// declared property setter: -(void)setSignposts:(id)signposts;
// declared property getter: -(id)signposts;
// declared property setter: -(void)setManeuverNames:(id)names;
// declared property getter: -(id)maneuverNames;
// declared property getter: -(int)maneuverType;
// declared property getter: -(unsigned)expectedTime;
// declared property getter: -(unsigned)distance;
// declared property getter: -(unsigned)stepID;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)copyTo:(id)to;
-(void)writeTo:(id)to;
-(BOOL)readFrom:(id)from;
-(id)dictionaryRepresentation;
-(id)description;
// declared property getter: -(BOOL)hasNotice;
// declared property getter: -(BOOL)hasInstructions;
// declared property getter: -(BOOL)hasExitNumber;
// declared property getter: -(BOOL)hasOverrideDrivingSide;
// declared property setter: -(void)setHasOverrideDrivingSide:(BOOL)side;
// declared property setter: -(void)setOverrideDrivingSide:(int)side;
// declared property getter: -(BOOL)hasOverrideTransportType;
// declared property setter: -(void)setHasOverrideTransportType:(BOOL)type;
// declared property setter: -(void)setOverrideTransportType:(int)type;
// declared property getter: -(BOOL)hasHintFirstAnnouncementZilchIndex;
// declared property setter: -(void)setHasHintFirstAnnouncementZilchIndex:(BOOL)index;
// declared property setter: -(void)setHintFirstAnnouncementZilchIndex:(int)index;
// declared property getter: -(int)hintFirstAnnouncementZilchIndex;
-(id)signpostAtIndex:(unsigned)index;
-(unsigned)signpostsCount;
-(void)addSignpost:(id)signpost;
-(void)clearSignposts;
-(void)setJunctionElements:(XXStruct_DtYHXC*)elements count:(unsigned)count;
-(XXStruct_DtYHXC)junctionElementAtIndex:(unsigned)index;
-(void)addJunctionElement:(XXStruct_DtYHXC)element;
-(void)clearJunctionElements;
// declared property getter: -(XXStruct_DtYHXC*)junctionElements;
// declared property getter: -(unsigned)junctionElementsCount;
// declared property getter: -(BOOL)hasJunctionType;
// declared property setter: -(void)setHasJunctionType:(BOOL)type;
// declared property setter: -(void)setJunctionType:(int)type;
// declared property getter: -(int)junctionType;
-(void)setLaneGuidances:(XXStruct_TrK5YA*)guidances count:(unsigned)count;
-(XXStruct_TrK5YA)laneGuidanceAtIndex:(unsigned)index;
-(void)addLaneGuidance:(XXStruct_TrK5YA)guidance;
-(void)clearLaneGuidances;
// declared property getter: -(XXStruct_TrK5YA*)laneGuidances;
// declared property getter: -(unsigned)laneGuidancesCount;
-(id)maneuverNameAtIndex:(unsigned)index;
-(unsigned)maneuverNamesCount;
-(void)addManeuverName:(id)name;
-(void)clearManeuverNames;
// declared property getter: -(BOOL)hasManeuverType;
// declared property setter: -(void)setHasManeuverType:(BOOL)type;
// declared property setter: -(void)setManeuverType:(int)type;
// declared property getter: -(BOOL)hasExpectedTime;
// declared property setter: -(void)setHasExpectedTime:(BOOL)time;
// declared property setter: -(void)setExpectedTime:(unsigned)time;
// declared property getter: -(BOOL)hasDistance;
// declared property setter: -(void)setHasDistance:(BOOL)distance;
// declared property setter: -(void)setDistance:(unsigned)distance;
// declared property getter: -(BOOL)hasManeuverEndZilchIndex;
// declared property setter: -(void)setHasManeuverEndZilchIndex:(BOOL)index;
// declared property setter: -(void)setManeuverEndZilchIndex:(int)index;
// declared property getter: -(int)maneuverEndZilchIndex;
// declared property getter: -(BOOL)hasManeuverStartZilchIndex;
// declared property setter: -(void)setHasManeuverStartZilchIndex:(BOOL)index;
// declared property setter: -(void)setManeuverStartZilchIndex:(int)index;
// declared property getter: -(int)maneuverStartZilchIndex;
// declared property getter: -(BOOL)hasManeuverEndBasicIndex;
// declared property setter: -(void)setHasManeuverEndBasicIndex:(BOOL)index;
// declared property setter: -(void)setManeuverEndBasicIndex:(int)index;
// declared property getter: -(int)maneuverEndBasicIndex;
// declared property getter: -(BOOL)hasStepID;
// declared property setter: -(void)setHasStepID:(BOOL)anId;
// declared property setter: -(void)setStepID:(unsigned)anId;
-(void)dealloc;
// declared property getter: -(int)hintFirstAnnouncementIndex;
// declared property getter: -(BOOL)hasHintFirstAnnouncementIndex;
// declared property getter: -(unsigned)maneuverStartIndex;
// declared property getter: -(unsigned)maneuverEndIndex;
@end

