/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface GEOTileDBProtection : XXUnknownSuperclass {
@private
	int _currentState;
}
+(id)sharedObject;
-(void)updateState;
-(int)state;
-(void)dealloc;
-(id)init;
@end

