/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "GeoServices-Structs.h"


@interface GEOTileKeyMap : XXUnknownSuperclass {
	int _type;
	void* _map;
}
-(void)removeObjectForKey:(const GEOTileKey*)key;
-(void)setObject:(id)object forKey:(const GEOTileKey*)key;
-(id)objectForKey:(const GEOTileKey*)key;
-(id)contentsDescription;
-(void)dealloc;
-(id)initWithMapType:(int)mapType;
@end

