/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <ProtocolBuffer/PBCodable.h>


__attribute__((visibility("hidden")))
@interface GEOVLaneConnection : PBCodable {
@private
	unsigned _firstLaneIndex;
	unsigned _firstRoadIndex;
	unsigned _secondLaneIndex;
	unsigned _secondRoadIndex;
}
@property(assign, nonatomic) unsigned secondLaneIndex;	// @synthesize=_secondLaneIndex
@property(assign, nonatomic) unsigned secondRoadIndex;	// @synthesize=_secondRoadIndex
@property(assign, nonatomic) unsigned firstLaneIndex;	// @synthesize=_firstLaneIndex
@property(assign, nonatomic) unsigned firstRoadIndex;	// @synthesize=_firstRoadIndex
// declared property setter: -(void)setSecondLaneIndex:(unsigned)index;
// declared property getter: -(unsigned)secondLaneIndex;
// declared property setter: -(void)setSecondRoadIndex:(unsigned)index;
// declared property getter: -(unsigned)secondRoadIndex;
// declared property setter: -(void)setFirstLaneIndex:(unsigned)index;
// declared property getter: -(unsigned)firstLaneIndex;
// declared property setter: -(void)setFirstRoadIndex:(unsigned)index;
// declared property getter: -(unsigned)firstRoadIndex;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)copyTo:(id)to;
-(void)writeTo:(id)to;
-(BOOL)readFrom:(id)from;
-(id)dictionaryRepresentation;
-(id)description;
-(void)dealloc;
@end

