/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ScreenReaderCore.framework/ScreenReaderCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSConditionLock;

__attribute__((visibility("hidden")))
@interface _SCRCThreadTask : XXUnknownSuperclass {
@private
	id _target;
	SEL _selector;
	unsigned long _count;
	void* _objects[4];
	NSConditionLock* _waitLock;
	unsigned long _mask;
}
-(void)fire;
-(void)setWaitLock:(id)lock;
-(void)dealloc;
-(id)initWithTarget:(id)target selector:(SEL)selector cancelMask:(unsigned long)mask count:(unsigned long)count firstObject:(id)object moreObjects:(void*)objects;
@end

