/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Weather.framework/Weather
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface WeatherImageLoader : XXUnknownSuperclass {
}
+(id)yahooButtonImage;
+(id)twcButtonImage;
+(id)conditionImageNamed:(id)named;
+(id)conditionImageWithConditionIndex:(int)conditionIndex;
@end

