/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Weather.framework/Weather
 */

#import "CLLocationManagerDelegate.h"
#import "WeatherValidatorDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CLLocationManager;

@interface WeatherUpdateController : XXUnknownSuperclass <CLLocationManagerDelegate, WeatherValidatorDelegate> {
	CLLocationManager* _locationManager;
	id searchCompletion;
	id currentLocationCompletion;
	id weatherInfoCompletion;
@private
	CLLocationManager* locationManager;
}
@property(copy, nonatomic) id weatherInfoCompletion;	// @synthesize
@property(copy, nonatomic) id currentLocationCompletion;	// @synthesize
@property(copy, nonatomic) id searchCompletion;	// @synthesize
@property(retain, nonatomic) CLLocationManager* locationManager;	// @synthesize
+(id)sharedWeatherUpdateController;
// declared property setter: -(void)setWeatherInfoCompletion:(id)completion;
// declared property getter: -(id)weatherInfoCompletion;
// declared property setter: -(void)setCurrentLocationCompletion:(id)completion;
// declared property getter: -(id)currentLocationCompletion;
// declared property setter: -(void)setSearchCompletion:(id)completion;
// declared property getter: -(id)searchCompletion;
// declared property setter: -(void)setLocationManager:(id)manager;
// declared property getter: -(id)locationManager;
-(void)weatherInformationForIDs:(id)ids withCompletionHandler:(id)completionHandler;
-(void)weatherInformationForLocation:(id)location withCompletionHandler:(id)completionHandler;
-(void)removeAllCities;
-(void)locationManager:(id)manager didFailWithError:(id)error;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)didFailWithError:(id)error;
-(void)didValidateLocation:(id)location;
-(BOOL)weatherListContainsCity:(id)city;
-(id)addCityToWeatherAppList:(id)weatherAppList;
-(int)activeCity;
-(id)citiesInWeatherAppList;
-(void)searchForCitiesWithName:(id)name withCompletionHandler:(id)completionHandler;
-(void)dealloc;
@end

