/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
 */

#import <Foundation/NSData.h>


@interface PLXPCTransaction : NSData {
@private
	const char* _identifier;
}
+(id)transaction:(const char*)transaction;
-(id)description;
-(void)stillAlive;
-(void)dealloc;
-(id)initWithIdentifier:(const char*)identifier;
@end

