/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MFDAMailAccountRequest.h"


@interface _MFDAMessageStoreDeleteRequest : XXUnknownSuperclass <MFDAMailAccountRequest> {
}
@property(readonly, assign, nonatomic) BOOL isUserRequested;
@property(readonly, assign, nonatomic) BOOL shouldSend;
-(id)deferredOperation;
// declared property getter: -(BOOL)isUserRequested;
// declared property getter: -(BOOL)shouldSend;
-(unsigned long long)generationNumber;
@end

