/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "Message-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, ActivityMonitor, MailAccount, MailboxUid;

@interface MailMessageStore : XXUnknownSuperclass {
	struct {
		unsigned isReadOnly : 1;
		unsigned hasUnsavedChangesToMessageData : 1;
		unsigned haveOpenLockFile : 1;
		unsigned compacting : 1;
		unsigned cancelInvalidation : 1;
		unsigned forceInvalidation : 1;
		unsigned isWritingChangesToDisk : 1;
		unsigned isTryingToClose : 1;
		unsigned compactOnClose : 1;
		unsigned reserved : 22;
	} _flags;
	MailboxUid* _mailboxUid;
	MailAccount* _account;
	unsigned _deletedMessagesSize;
	unsigned _deletedMessageCount;
	unsigned _unreadMessageCount;
	unsigned _lastFetchCount;
	unsigned _generationNumber;
	int _state;
	NSTimer* _timer;
	double timeOfLastAutosaveOperation;
	ActivityMonitor* _openMonitor;
}
@property(readonly, retain) MailboxUid* mailboxUid;	// converted property
@property(readonly, retain) MailAccount* account;	// converted property
+(Class)headersClass;
+(int)copyMessages:(id)messages toMailbox:(id)mailbox markAsRead:(BOOL)read deleteOriginals:(BOOL)originals isDeletion:(BOOL)deletion unsuccessfulOnes:(id)ones;
+(Class)classForMimePart;
+(BOOL)storeAtPathIsWritable:(id)pathIsWritable;
+(BOOL)createEmptyStoreForPath:(id)path;
+(BOOL)createEmptyStoreIfNeededForPath:(id)path;
-(BOOL)_shouldChangeComponentMessageFlagsForMessage:(id)message;
-(BOOL)_shouldChangeComponentMessageFlags;
-(BOOL)_updateFlagForMessage:(id)message key:(id)key value:(BOOL)value;
-(void)messagesWereAdded:(id)added earliestReceivedDate:(id)date;
-(void)updateMessages:(id)messages updateNumberOfAttachments:(BOOL)attachments;
-(void)_setFlagsForMessages:(id)messages;
-(void)_setFlagsForMessages:(id)messages mask:(unsigned long long)mask;
-(id)_setOrGetBody:(id)body forMessage:(id)message updateFlags:(BOOL)flags;
-(void)updateBodyFlagsForMessage:(id)message body:(id)body;
-(void)_rebuildTableOfContentsSynchronously;
-(id)_fetchHeaderDataForMessage:(id)message downloadIfNecessary:(BOOL)necessary;
-(int)archiveDestination;
-(BOOL)shouldArchive;
-(BOOL)supportsArchiving;
-(BOOL)shouldDeleteInPlace;
-(BOOL)canDeleteMessage:(id)message;
-(BOOL)shouldSetSummaryForMessage:(id)message;
-(id)loadMeetingMetadataForMessage:(id)message;
-(id)loadMeetingDataForMessage:(id)message;
-(id)loadMeetingExternalIDForMessage:(id)message;
-(BOOL)shouldDownloadBodyDataForMessage:(id)message;
-(void)setLibrary:(id)library;
-(void)_flushAllMessageData;
-(void)close;
-(id)storeData:(id)data forMimePart:(id)mimePart isComplete:(BOOL)complete;
-(BOOL)setPreferredEncoding:(unsigned long)encoding forMessage:(id)message;
-(int)fetchMobileSynchronously:(unsigned)synchronously;
-(int)fetchMobileSynchronously:(unsigned)synchronously preservingUID:(id)uid options:(unsigned)options;
-(int)fetchNumMessages:(unsigned)messages preservingUID:(id)uid options:(unsigned)options;
-(id)status;
-(void)setNumberOfAttachments:(unsigned)attachments isSigned:(BOOL)aSigned isEncrypted:(BOOL)encrypted forMessage:(id)message;
-(void)setFlagsCancelled:(id)cancelled forMessages:(id)messages;
-(id)willSetFlagsFromDictionary:(id)dictionary forMessages:(id)messages;
-(void)setFlag:(id)flag state:(BOOL)state forMessages:(id)messages;
-(id)setFlagsLocallyFromDictionary:(id)dictionary forMessages:(id)messages;
-(id)setFlagsFromDictionary:(id)dictionary forMessages:(id)messages;
-(BOOL)hasCachedDataForMimePart:(id)mimePart;
-(id)headerDataForMessage:(id)message downloadIfNecessary:(BOOL)necessary;
-(id)lastViewedMessageDate;
-(id)lastViewedMessageWithOptions:(unsigned)options;
-(id)messageForRemoteID:(id)remoteID;
-(id)messageForMessageID:(id)messageID options:(unsigned)options;
-(int)appendMessages:(id)messages unsuccessfulOnes:(id)ones;
-(int)appendMessages:(id)messages unsuccessfulOnes:(id)ones newMessageIDs:(id)ids;
-(int)appendMessages:(id)messages unsuccessfulOnes:(id)ones newMessageIDs:(id)ids newMessages:(id)messages4;
-(int)appendMessages:(id)messages unsuccessfulOnes:(id)ones newMessageIDs:(id)ids newMessages:(id)messages4 flagsToSet:(id)set;
-(BOOL)allowsAppend;
-(void)messagesWereDeleted:(id)deleted;
-(void)undeleteMessages:(id)messages;
-(void)deleteMessages:(id)messages moveToTrash:(BOOL)trash;
-(void)deleteMessagesOlderThanNumberOfDays:(int)days compact:(BOOL)compact;
-(void)doCompact;
-(BOOL)canCompact;
-(id)finishRoutingMessages:(id)messages routed:(id)routed;
-(id)_defaultRouterDestination;
-(int)fetchMessagesWithMessageIDs:(id)messageIDs andSetFlags:(unsigned long long)flags;
-(BOOL)canFetchMessageIDs;
-(id)remoteIDsMatchingCriterion:(id)criterion limit:(unsigned)limit error:(id*)error;
-(int)fetchMessagesMatchingCriterion:(id)criterion limit:(unsigned)limit;
-(BOOL)allMessagesAvailableLocally;
-(BOOL)canFetchSearchResults;
-(id)copyMessagesWithRemoteIDs:(id)remoteIDs options:(unsigned)options;
-(id)copyMessagesMatchingCriterion:(id)criterion options:(unsigned)options;
-(id)copyMessagesMatchingText:(id)text options:(unsigned)options;
-(id)copyMessagesMatchingText:(id)text;
-(id)copyOfAllMessagesForBodyLoadingFromRowID:(unsigned)rowID limit:(unsigned)limit;
-(id)copyOfAllMessagesWithOptions:(unsigned)options;
-(id)mutableCopyOfAllMessages;
-(id)copyOfMessagesInRange:(NSRange)range;
-(id)copyOfAllMessages;
-(unsigned)indexOfMessage:(id)message;
-(BOOL)hasMessageForAccount:(id)account;
-(unsigned)unreadCountMatchingCriterion:(id)criterion;
-(unsigned)unreadCount;
-(void)purgeMessagesBeyondLimit:(unsigned)limit keepingMessage:(id)message;
-(BOOL)hasMoreMessages:(unsigned)messages;
-(unsigned)serverUnreadCount;
-(unsigned)serverUnreadOnlyOnServerCount;
-(unsigned)serverMessageCount;
-(unsigned)nonDeletedCountIncludingServerSearch:(BOOL)search andThreadSearch:(BOOL)search2;
-(unsigned)totalCount;
-(void)deletedCount:(unsigned*)count andSize:(unsigned*)size;
-(void)updateUserInfoToLatestValues;
-(void)messagesWillBeCompacted:(id)messages;
-(void)messagesWereCompacted:(id)compacted;
-(void)messagesWereAdded:(id)added;
-(void)structureDidChange;
-(void)messageFlagsDidChange:(id)messageFlags flags:(id)flags;
-(BOOL)isDrafts;
-(id)description;
-(BOOL)isReadOnly;
-(id)displayName;
-(id)storePathRelativeToAccount;
-(BOOL)isOpened;
// converted property getter: -(id)mailboxUid;
// converted property getter: -(id)account;
-(void)writeUpdatedMessageDataToDisk;
-(void)cancelOpen;
-(void)didOpen;
-(void)openSynchronously;
-(void)openAsynchronously;
-(void)dealloc;
-(id)initWithMailboxUid:(id)mailboxUid readOnly:(BOOL)only;
@end

