/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "Message-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MFSQLiteConnection : XXUnknownSuperclass {
	NSString* _path;
	sqlite3* _db;
@private
	NSString* _databaseName;
	CFDictionaryRef _statementCache;
	void* _ICUSearchContext;
	void* _CPSearchContext;
	int _transactionType;
	unsigned _transactionCount;
}
@property(readonly, assign, nonatomic) sqlite3* db;	// @synthesize=_db
// declared property getter: -(sqlite3*)db;
-(int)rollbackTransaction;
-(int)commitTransaction;
-(int)beginTransactionWithType:(int)type;
-(int)beginTransaction;
-(sqlite3_stmt*)preparedStatementForPattern:(id)pattern;
-(void)flush;
-(BOOL)isOpen;
-(void)close;
-(int)open;
-(const char*)_vfsModuleName;
-(void)dealloc;
-(id)initWithPath:(id)path databaseName:(id)name;
@end

