/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface CertInfoTrustDetailsViewController : XXUnknownSuperclass {
	NSArray* _trustProperties;
}
@property(retain, nonatomic) NSArray* trustProperties;	// @synthesize=_trustProperties
// declared property setter: -(void)setTrustProperties:(id)properties;
// declared property getter: -(id)trustProperties;
-(void)viewWillAppear:(BOOL)view;
-(void)_setupNavItem;
-(void)dealloc;
-(void)loadView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
@end

