/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol CertInfoTrustDescription;

@interface CertInfoCertificateListController : XXUnknownSuperclass {
	id<CertInfoTrustDescription> _description;
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)dealloc;
-(id)initWithTrustDescription:(id)trustDescription;
@end

