/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/SoftwareUpdateServices
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSString, NSMutableSet, NSSet;

@interface SUScanOptions : XXUnknownSuperclass <NSCoding> {
@private
	NSString* _identifier;
	BOOL _forced;
	NSMutableSet* _types;
}
@property(retain, nonatomic) NSSet* types;	// @synthesize=_types
@property(assign, nonatomic, getter=isForced) BOOL forced;	// @synthesize=_forced
@property(retain, nonatomic) NSString* identifier;	// @synthesize=_identifier
// declared property setter: -(void)setTypes:(id)types;
// declared property getter: -(id)types;
// declared property setter: -(void)setForced:(BOOL)forced;
// declared property getter: -(BOOL)isForced;
// declared property setter: -(void)setIdentifier:(id)identifier;
// declared property getter: -(id)identifier;
-(id)description;
-(void)clearTypes;
-(BOOL)findsAnyUpdate;
-(BOOL)containsType:(int)type;
-(void)removeType:(int)type;
-(void)addType:(int)type;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)init;
-(void)dealloc;
@end

