/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface EmbeddedInternalPageViewController : XXUnknownSuperclass {
}
-(id)newViewControllerForPage:(id)page ofType:(int)type returningError:(id*)error;
-(id)newFetchOperation;
-(void)handleFailureWithError:(id)error;
-(BOOL)decidePolicyForWebNavigationAction:(id)webNavigationAction request:(id)request decisionListener:(id)listener;
@end

