/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "IUSimpleCellConfiguration.h"


@interface HomeSharingActionRowCellConfiguration : IUSimpleCellConfiguration {
}
+(id)backgroundColorWithModifiers:(unsigned)modifiers;
-(void)reloadLayoutInformation;
-(id)colorForLabelAtIndex:(unsigned)index withModifiers:(unsigned)modifiers;
@end

