/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "IUMediaQueriesDataSource.h"


@interface IUGenresDataSource : IUMediaQueriesDataSource {
}
+(int)mediaEntityType;
+(id)tabBarItemTitleKey;
+(id)tabBarItemIconName;
-(Class)cellConfigurationClassForEntity:(id)entity;
-(id)viewControllerContextForIndex:(unsigned)index;
-(id)viewControllerContextForMediaQuery:(id)mediaQuery;
-(SEL)libraryHasDisplayableEntitiesSelector;
@end

