/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "IUSegmentedViewController.h"
#import "ViewControllerArchiveNode.h"

@class NSArray, NSString, IUModalContext, IUViewControllerContext, NSMutableArray;

@interface IUiPodSegmentedViewController : IUSegmentedViewController <ViewControllerArchiveNode> {
@private
	NSMutableArray* _contexts;
	IUModalContext* _modalContext;
	NSString* _savedSelectedIdentifier;
	BOOL _hasContent;
}
@property(readonly, assign, nonatomic) IUViewControllerContext* selectedViewControllerContext;
@property(readonly, assign, nonatomic) NSArray* viewControllerContexts;	// @synthesize=_contexts
@property(retain, nonatomic) NSString* selectedIdentifier;
// declared property getter: -(id)viewControllerContexts;
-(void)_resetViewControllersWithContexts:(id)contexts;
-(id)_identifierForViewController:(id)viewController;
-(void)_availableMediaLibrariesDidChangeNotification:(id)_availableMediaLibraries;
-(void)_enabledMediaTypesDidChangeNotification:(id)_enabledMediaTypes;
-(void)_databaseContentsDidChangeNotification:(id)_databaseContents;
-(BOOL)restoreArchivedContexts:(id)contexts;
-(id)copyArchivableContexts;
-(BOOL)editable;
// declared property getter: -(id)selectedViewControllerContext;
-(id)noContentViewContextForContexts:(id)contexts;
-(void)setModalContext:(id)context;
-(void)setViewControllersWithIdentifiers:(id)identifiers style:(int)style;
-(void)setViewControllersWithContexts:(id)contexts;
// declared property setter: -(void)setSelectedIdentifier:(id)identifier;
// declared property getter: -(id)selectedIdentifier;
-(void)dealloc;
-(id)init;
@end

