/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "iPodUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface IUMediaActionButton : XXUnknownSuperclass {
	BOOL _forceHighlighted;
	BOOL _naturalHighlighted;
}
-(void)endForcedHighlighted;
-(void)setForcedTemporaryHighlight;
-(void)setHighlighted:(BOOL)highlighted;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

