/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "IUPlaybackViewController.h"
#import "IUCoverFlowOwner.h"

@class IUMediaEntitySpecifier, IUCoverFlowViewController;

@interface IUMixedPlaybackViewController : IUPlaybackViewController <IUCoverFlowOwner> {
@private
	IUMediaEntitySpecifier* _albumContextSpecifier;
	BOOL _animateREO;
	BOOL _nextPushWillZoomArtwork;
	IUMediaEntitySpecifier* _playlistContextSpecifier;
	BOOL _showFlipperHint;
	IUCoverFlowViewController* _transferredCoverFlowController;
}
@property(readonly, assign, nonatomic) BOOL isShowingCoverFlow;	// @dynamic
@property(retain, nonatomic) IUCoverFlowViewController* coverFlowViewController;
@property(assign, nonatomic) BOOL nextPushWillZoomArtwork;
-(BOOL)_isExistingGeniusMixForDataSource:(id)dataSource;
-(BOOL)_previousViewControllerIsActiveGeniusMix;
-(void)_updateAnimateForResumeEventsOnly;
-(void)_setFakeItemForDataSource:(id)dataSource;
-(void)_setAnimatesForResumeEventsOnly:(BOOL)resumeEventsOnly;
-(void)_reloadTVOutForQuery:(id)query;
-(void)_exitToPlaylistContext:(id)playlistContext animated:(BOOL)animated;
-(void)_exitToAlbumContext:(id)albumContext animated:(BOOL)animated;
-(void)_backOfAlbumTrackChangeNotification:(id)albumTrackChangeNotification;
-(void)_playlistChangeNotification:(id)notification;
-(unsigned)transitionEffectForViewController:(id)viewController;
// declared property setter: -(void)setCoverFlowViewController:(id)controller;
// declared property getter: -(BOOL)isShowingCoverFlow;
// declared property getter: -(id)coverFlowViewController;
// declared property setter: -(void)setNextPushWillZoomArtwork:(BOOL)zoomArtwork;
// declared property getter: -(BOOL)nextPushWillZoomArtwork;
-(BOOL)IUShouldApplyInterfaceStyle;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)setOrientation:(int)orientation animated:(BOOL)animated;
-(void)setItem:(id)item animated:(BOOL)animated;
-(void)exitPlayerAnimated:(BOOL)animated;
-(id)newViewControllerForItem:(id)item interfaceOrientation:(int)orientation reusingController:(id)controller;
-(id)newTransitionControllerForChangeToInterfaceOrientation:(int)interfaceOrientation fromInterfaceOrientation:(int)interfaceOrientation2;
-(id)newTransitionControllerForChangeToItem:(id)item fromItem:(id)item2;
-(id)newMediaNavigationItem;
-(void)dealloc;
-(id)init;
@end

