/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface IUMutableComponentsArray : XXUnknownSuperclass {
@private
	NSArray* _componentArrays;
}
@property(retain, nonatomic) NSArray* componentArrays;	// @synthesize=_componentArrays
// declared property setter: -(void)setComponentArrays:(id)arrays;
// declared property getter: -(id)componentArrays;
-(void)removeObjectsAtIndexes:(id)indexes;
-(void)removeAllObjects;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)removeLastObject;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(void)addObject:(id)object;
-(id)objectAtIndex:(unsigned)index;
-(id)_arrayForIndex:(unsigned*)index;
-(id)_mutableArrayForIndex:(unsigned*)index;
-(id)_arrayForIndex:(unsigned*)index mutable:(BOOL)aMutable;
-(unsigned)count;
-(void)dealloc;
-(id)initWithComponentArrays:(id)componentArrays;
@end

