/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor, UIImageView, IUReflectionView;

@interface IUReflectionImageView : XXUnknownSuperclass {
	float _reflectionHeight;
	float _spacing;
	float _reflectionAlpha;
	BOOL _useImageSize;
	unsigned _nonSquareImage : 1;
	UIImageView* _imageView;
	IUReflectionView* _reflection;
	UIColor* _imageBackgroundColor;
}
@property(retain, nonatomic) UIColor* imageBackgroundColor;	// @synthesize=_imageBackgroundColor
@property(assign, nonatomic) BOOL nonSquareImage;
// declared property getter: -(id)imageBackgroundColor;
-(void)setUseImageSize:(BOOL)size;
-(void)setReflectionVisible:(BOOL)visible;
-(void)setReflectionAlphaWhenVisible:(float)visible;
// declared property setter: -(void)setNonSquareImage:(BOOL)image;
// declared property setter: -(void)setImageBackgroundColor:(id)color;
-(void)setImage:(id)image;
// declared property getter: -(BOOL)nonSquareImage;
-(void)dealloc;
-(id)initWithReflectionHeight:(float)reflectionHeight spacing:(float)spacing;
-(id)init;
@end

