/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import "iPodUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIColor;

@interface IUStaticReflectionTitleView : XXUnknownSuperclass {
	NSString* _title;
	UIColor* _textColor;
}
@property(retain, nonatomic) UIColor* textColor;	// @synthesize=_textColor
@property(retain, nonatomic) NSString* title;	// @synthesize=_title
// declared property getter: -(id)title;
// declared property setter: -(void)setTextColor:(id)color;
// declared property getter: -(id)textColor;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawRect:(CGRect)rect;
// declared property setter: -(void)setTitle:(id)title;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

