/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IUMediaListDataSource;

@interface MediaPickerDataSourceActionRowTag : XXUnknownSuperclass {
	IUMediaListDataSource* _dataSource;
	int _tag;
}
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)initWithDataSource:(id)dataSource actionRowAtIndex:(unsigned)index;
@end

