/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTClientServices.framework/FTClientServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface FTCServiceAvailabilityCenter : XXUnknownSuperclass {
	NSMutableDictionary* _availabilityHandlers;
}
+(id)sharedInstance;
-(int)availabilityForListenerID:(id)listenerID forService:(int)service;
-(BOOL)removeListenerID:(id)anId forService:(int)service;
-(BOOL)addListenerID:(id)anId forService:(int)service;
-(BOOL)hasListenerID:(id)anId forService:(int)service;
-(id)containerForService:(int)service create:(BOOL)create;
-(void)_stopListeningToMonitor:(id)monitor;
-(void)_startListeningToMonitor:(id)monitor;
-(void)_handleServiceMonitorNotification:(id)notification;
-(void)_postNotificationForService:(int)service availability:(int)availability;
-(BOOL)_isValidServiceType:(int)type;
-(void)dealloc;
-(id)init;
@end

