/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

#import </libobjc.A.h>
#import "AccessibilityUtilities-Structs.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface AXIPCServer : NSObject {
@private
	id _defaultHandler;
	CFRunLoopSourceRef _serverRunLoopSource;
	CFRunLoopSourceRef _clientInvalidationSource;
	unsigned _serverPort;
	unsigned _clientInvalidationPort;
	NSMutableDictionary* _validSecurityTokens;
	NSMutableSet* _connectedClients;
	id _clientInvalidationHandler;
	NSMutableDictionary* _entitlements;
	unsigned _assignedServerPort;
	unsigned machPort;
	BOOL _running;
	NSString* _serviceName;
	NSMutableDictionary* _handlers;
}
@property(copy, nonatomic) id defaultHandler;
@property(retain, nonatomic) NSMutableDictionary* handlers;	// @synthesize=_handlers
@property(retain, nonatomic) CFRunLoopSourceRef serviceRunLoopSource;	// @dynamic
@property(readonly, assign, nonatomic) unsigned machPort;	// @synthesize
@property(retain, nonatomic) NSString* serviceName;	// @synthesize=_serviceName
@property(assign, nonatomic, getter=isRunning) BOOL running;	// @synthesize=_running
// declared property setter: -(void)setHandlers:(id)handlers;
// declared property getter: -(id)handlers;
// declared property setter: -(void)setServiceName:(id)name;
// declared property getter: -(id)serviceName;
// declared property setter: -(void)setRunning:(BOOL)running;
// declared property getter: -(BOOL)isRunning;
-(id)_handleIncomingMessage:(id)message securityToken:(XXStruct_AVM35A)token auditToken:(XXStruct_kUSYWB)token3 clientPort:(unsigned)port;
-(void)_handleClientRegistration:(id)registration;
-(void)_startServerThread;
-(void)_handleClientInvalidation:(unsigned)invalidation;
-(void)setClientInvalidationCallback:(id)callback;
-(void)setValidateMessage:(int)message validate:(BOOL)validate withEntitlement:(id)entitlement;
-(id)handlerForKey:(int)key withError:(id*)error;
-(BOOL)removeHandlerForKey:(int)key withError:(id*)error;
-(BOOL)addHandler:(id)handler forKey:(int)key withError:(id*)error;
-(BOOL)stopServerWithError:(id*)error;
-(BOOL)startServerWithError:(id*)error;
// declared property setter: -(void)setDefaultHandler:(id)handler;
// declared property getter: -(id)defaultHandler;
-(BOOL)_hasEntitlement:(unsigned)entitlement auditToken:(XXStruct_kUSYWB)token key:(int)key;
// declared property getter: -(unsigned)machPort;
-(id)description;
-(void)dealloc;
// declared property setter: -(void)setServiceRunLoopSource:(CFRunLoopSourceRef)source;
-(id)initWithPort:(unsigned)port;
-(id)initWithServiceName:(id)serviceName;
@end

