/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

#import </libobjc.A.h>


@interface AXTestRunner : NSObject {
@private
	id _preTestAction;
	id _postTestAction;
}
@property(copy, nonatomic) id postTestAction;	// @synthesize=_postTestAction
@property(copy, nonatomic) id preTestAction;	// @synthesize=_preTestAction
// declared property setter: -(void)setPostTestAction:(id)action;
// declared property getter: -(id)postTestAction;
// declared property setter: -(void)setPreTestAction:(id)action;
// declared property getter: -(id)preTestAction;
-(void)runTest:(Class)test;
-(void)dealloc;
@end

