/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AWDServerConnection : XXUnknownSuperclass {
}
-(unsigned long long)getAWDTimestamp;
-(BOOL)registerQueriableMetricCallbackForLogging:(id)logging;
-(BOOL)registerQueriableMetricCallback:(id)callback forIdentifier:(unsigned long)identifier;
-(BOOL)submitMetric:(id)metric;
-(id)newMetricContainerWithIdentifier:(unsigned long)identifier;
-(void)dealloc;
-(id)initWithComponentId:(unsigned long)componentId andBlockOnConfiguration:(BOOL)configuration;
-(id)initWithComponentId:(unsigned long)componentId;
@end

