/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVTaskDelegate.h"
#import "CoreDAVTaskGroup.h"
#import "CoreDAVPropFindTaskDelegate.h"
#import "CoreDAVOptionsTaskDelegate.h"
#import "CoreDAVPrincipalSearchPropertySetTaskDelegate.h"

@class NSSet, NSURL, NSString, NSMutableSet;
@protocol CoreDAVGetAccountPropertiesTaskGroupDelegate;

@interface CoreDAVGetAccountPropertiesTaskGroup : CoreDAVTaskGroup <CoreDAVPropFindTaskDelegate, CoreDAVOptionsTaskDelegate, CoreDAVPrincipalSearchPropertySetTaskDelegate, CoreDAVTaskDelegate> {
@private
	NSURL* _principalURL;
	NSString* _displayName;
	NSURL* _resourceID;
	NSSet* _emailAddresses;
	NSSet* _collections;
	NSSet* _principalSearchProperties;
	BOOL _isExpandPropertyReportSupported;
	BOOL _fetchPrincipalSearchProperties;
	BOOL _shouldIgnoreHomeSetOnDifferentHost;
	NSMutableSet* _redirectHistory;
}
@property(assign, nonatomic) BOOL shouldIgnoreHomeSetOnDifferentHost;	// @synthesize=_shouldIgnoreHomeSetOnDifferentHost
@property(assign, nonatomic) id<CoreDAVGetAccountPropertiesTaskGroupDelegate> delegate;	// @dynamic
@property(assign) BOOL fetchPrincipalSearchProperties;	// @synthesize=_fetchPrincipalSearchProperties
@property(readonly, assign) BOOL isExpandPropertyReportSupported;	// @synthesize=_isExpandPropertyReportSupported
@property(readonly, assign) NSSet* principalSearchProperties;	// @synthesize=_principalSearchProperties
@property(readonly, assign) NSSet* collections;	// @synthesize=_collections
@property(readonly, assign) NSSet* emailAddresses;	// @synthesize=_emailAddresses
@property(readonly, assign) NSURL* resourceID;	// @synthesize=_resourceID
@property(readonly, assign) NSString* displayName;	// @synthesize=_displayName
@property(readonly, assign) NSURL* principalURL;	// @synthesize=_principalURL
// declared property setter: -(void)setShouldIgnoreHomeSetOnDifferentHost:(BOOL)ignoreHomeSetOnDifferentHost;
// declared property getter: -(BOOL)shouldIgnoreHomeSetOnDifferentHost;
// declared property getter: -(id)principalSearchProperties;
// declared property setter: -(void)setFetchPrincipalSearchProperties:(BOOL)properties;
// declared property getter: -(BOOL)fetchPrincipalSearchProperties;
// declared property getter: -(BOOL)isExpandPropertyReportSupported;
// declared property getter: -(id)collections;
// declared property getter: -(id)emailAddresses;
// declared property getter: -(id)resourceID;
// declared property getter: -(id)displayName;
// declared property getter: -(id)principalURL;
-(void)task:(id)task didFinishWithError:(id)error;
-(void)searchPropertySetTask:(id)task completetWithPropertySearchSet:(id)propertySearchSet error:(id)error;
-(void)processPrincipalHeaders:(id)headers;
-(void)coaxServerForPrincipalHeaders;
-(void)propFindTask:(id)task parsedResponses:(id)responses error:(id)error;
-(BOOL)forceOptionsRequest;
-(void)_taskCompleted:(id)completed withError:(id)error;
-(void)_setPropertiesFromParsedResponses:(id)parsedResponses;
-(void)startTaskGroup;
-(id)homeSet;
-(id)_copyAccountPropertiesPropFindElements;
-(void)taskGroupWillCancelWithError:(id)taskGroup;
-(id)description;
-(void)dealloc;
-(id)initWithAccountInfoProvider:(id)accountInfoProvider taskManager:(id)manager;
@end

