/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVItem.h"

@class CoreDAVHrefItem;

@interface CoreDAVItemWithHrefChildItem : CoreDAVItem {
	CoreDAVHrefItem* _href;
}
@property(retain) CoreDAVHrefItem* href;	// @synthesize=_href
+(id)copyParseRules;
// declared property setter: -(void)setHref:(id)href;
// declared property getter: -(id)href;
-(void)write:(id)write;
-(id)description;
-(void)dealloc;
@end

