/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVItem.h"

@class CoreDAVItemWithNoChildren, NSMutableSet;

@interface CoreDAVItemWithHrefChildren : CoreDAVItem {
	NSMutableSet* _hrefs;
	CoreDAVItemWithNoChildren* _unauthenticated;
}
@property(retain) CoreDAVItemWithNoChildren* unauthenticated;	// @synthesize=_unauthenticated
@property(retain) NSMutableSet* hrefs;	// @synthesize=_hrefs
+(id)copyParseRules;
// declared property setter: -(void)setUnauthenticated:(id)unauthenticated;
// declared property getter: -(id)unauthenticated;
// declared property setter: -(void)setHrefs:(id)hrefs;
// declared property getter: -(id)hrefs;
-(id)hrefsAsStrings;
-(id)hrefsAsOriginalURLs;
-(id)hrefsAsFullURLs;
-(void)addHref:(id)href;
-(id)description;
-(void)dealloc;
@end

