/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVTaskGroup.h"
#import "CoreDAVContainerMultiGetSubmittable.h"

@class NSSet, NSMutableSet, CoreDAVContainerMultiGetTask, NSError;
@protocol CoreDAVAccountInfoProvider, CoreDAVTaskManager;

@interface CoreDAVMultiGetWithFallbackTaskGroup : CoreDAVTaskGroup <CoreDAVContainerMultiGetSubmittable> {
	BOOL _shouldIgnoreResponseErrors;
	BOOL _usingMultiGet;
	CoreDAVContainerMultiGetTask* _multiGetTask;
	id _getBlock;
	NSMutableSet* _urls;
	NSMutableSet* _parsedContents;
}
@property(assign, nonatomic) BOOL shouldIgnoreResponseErrors;	// @synthesize=_shouldIgnoreResponseErrors
@property(readonly, assign, nonatomic) NSSet* parsedContents;
@property(readonly, assign, nonatomic) NSSet* missingURLs;
@property(assign) double timeoutInterval;
@property(readonly, assign, nonatomic) NSError* error;
@property(assign, nonatomic) id<CoreDAVAccountInfoProvider> accountInfoProvider;
@property(assign, nonatomic) id<CoreDAVTaskManager> taskManager;
@property(copy, nonatomic) id completionBlock;
// declared property setter: -(void)setShouldIgnoreResponseErrors:(BOOL)ignoreResponseErrors;
// declared property getter: -(BOOL)shouldIgnoreResponseErrors;
// declared property getter: -(id)parsedContents;
// declared property getter: -(id)missingURLs;
// declared property getter: -(id)error;
-(void)taskGroupWillCancelWithError:(id)taskGroup;
-(void)startTaskGroup;
-(void)_fetchOneItem;
-(void)_switchToSingleGetMode;
-(void)_configureAndSubmitTask:(id)task;
-(void)dealloc;
-(id)initWithURLs:(id)urls multiGetBlock:(id)block getBlock:(id)block3 accountInfoProvider:(id)provider taskManager:(id)manager;
@end

