/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVContainerMultiGetTask.h"


@interface CoreDAVFolderContentsMultiGetTask : CoreDAVContainerMultiGetTask {
}
-(void)setAdditionalProperties:(id)properties onDataItem:(id)item;
-(id)copyAdditionalPropElements;
-(id)initWithURLs:(id)urls atContainerURL:(id)containerURL appSpecificDataItemClass:(Class)aClass;
@end

