/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NoteContext, AccountsManager;

@interface AccountUtilities : XXUnknownSuperclass {
	AccountsManager* _accountsManager;
	NSArray* _syncableAccounts;
	NoteContext* _noteContext;
}
@property(readonly, retain) AccountsManager* accountsManager;	// converted property
+(id)sharedAccountUtilities;
-(void).cxx_destruct;
-(BOOL)localNotesExist;
-(BOOL)isDeviceLocalAccount:(id)account;
-(id)defaultStoreSyncIdWithDesiredSyncId:(id)desiredSyncId;
-(id)syncAccountIdForDisplayAccountId:(id)displayAccountId;
-(id)allDisplayAccounts;
-(id)allSyncableAccounts;
-(void)dealloc;
-(id)init;
-(void)accountsChanged;
// converted property getter: -(id)accountsManager;
@end

