/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AITTarget.framework/AITTarget
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AITTarget-Structs.h"

@class NSString;
@protocol AITXPCConnectionDelegate;

@interface AITXPCConnection : XXUnknownSuperclass {
@private
	int _pid;
	id<AITXPCConnectionDelegate> _delegate;
	NSString* _bundleId;
	xpc_connection_s* _connection;
	void* _currentMessage;
	dispatch_queue_s* _dispatchQueue;
	dispatch_queue_s* _internalQueue;
}
@property(assign, nonatomic) dispatch_queue_s* internalQueue;	// @synthesize=_internalQueue
@property(assign, nonatomic) dispatch_queue_s* dispatchQueue;	// @synthesize=_dispatchQueue
@property(assign, nonatomic) void* currentMessage;	// @synthesize=_currentMessage
@property(assign, nonatomic) xpc_connection_s* connection;	// @synthesize=_connection
@property(readonly, assign, nonatomic) int pid;
@property(copy, nonatomic) NSString* bundleId;	// @synthesize=_bundleId
@property(readonly, assign, nonatomic) BOOL available;
@property(assign, nonatomic) id<AITXPCConnectionDelegate> delegate;	// @synthesize=_delegate
// declared property setter: -(void)setInternalQueue:(dispatch_queue_s*)queue;
// declared property getter: -(dispatch_queue_s*)internalQueue;
// declared property setter: -(void)setDispatchQueue:(dispatch_queue_s*)queue;
// declared property getter: -(dispatch_queue_s*)dispatchQueue;
// declared property setter: -(void)setCurrentMessage:(void*)message;
// declared property getter: -(void*)currentMessage;
// declared property setter: -(void)setConnection:(xpc_connection_s*)connection;
// declared property getter: -(xpc_connection_s*)connection;
// declared property setter: -(void)setBundleId:(id)anId;
// declared property getter: -(id)bundleId;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
// declared property getter: -(int)pid;
// declared property getter: -(BOOL)available;
-(void)barrierWithCompletionHandler:(id)completionHandler;
-(void)sendMessage:(id)message userInfo:(id)info replyHandler:(id)handler;
-(void)sendMessage:(id)message userInfo:(id)info;
-(void)_handleEvent:(void*)event;
-(id)_deserializeMessage:(void*)message;
-(void)closeConnection;
-(id)initWithConnection:(xpc_connection_s*)connection delegate:(id)delegate dispatchQueue:(dispatch_queue_s*)queue;
-(id)initWithConnection:(xpc_connection_s*)connection delegate:(id)delegate;
-(void)dealloc;
@end

