/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMCSSRule.h"

@class NSString, DOMMediaList, DOMCSSStyleSheet;

__attribute__((visibility("hidden")))
@interface DOMCSSImportRule : DOMCSSRule {
}
@property(readonly, assign) DOMCSSStyleSheet* styleSheet;
@property(readonly, assign) DOMMediaList* media;
@property(readonly, assign) NSString* href;
// declared property getter: -(id)styleSheet;
// declared property getter: -(id)media;
// declared property getter: -(id)href;
@end

