/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMHTMLElement.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface DOMHTMLMetaElement : DOMHTMLElement {
}
@property(copy) NSString* scheme;
@property(copy) NSString* name;
@property(copy) NSString* httpEquiv;
@property(copy) NSString* content;
// declared property setter: -(void)setScheme:(id)scheme;
// declared property getter: -(id)scheme;
// declared property setter: -(void)setName:(id)name;
// declared property getter: -(id)name;
// declared property setter: -(void)setHttpEquiv:(id)equiv;
// declared property getter: -(id)httpEquiv;
// declared property setter: -(void)setContent:(id)content;
// declared property getter: -(id)content;
@end

