/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMObject.h"


__attribute__((visibility("hidden")))
@interface DOMValidityState : DOMObject {
}
@property(readonly, assign) BOOL valid;
@property(readonly, assign) BOOL customError;
@property(readonly, assign) BOOL stepMismatch;
@property(readonly, assign) BOOL rangeOverflow;
@property(readonly, assign) BOOL rangeUnderflow;
@property(readonly, assign) BOOL tooLong;
@property(readonly, assign) BOOL patternMismatch;
@property(readonly, assign) BOOL typeMismatch;
@property(readonly, assign) BOOL valueMissing;
// declared property getter: -(BOOL)valid;
// declared property getter: -(BOOL)customError;
// declared property getter: -(BOOL)stepMismatch;
// declared property getter: -(BOOL)rangeOverflow;
// declared property getter: -(BOOL)rangeUnderflow;
// declared property getter: -(BOOL)tooLong;
// declared property getter: -(BOOL)patternMismatch;
// declared property getter: -(BOOL)typeMismatch;
// declared property getter: -(BOOL)valueMissing;
-(void)finalize;
-(void)dealloc;
@end

