/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SUButtonAction : XXUnknownSuperclass {
@private
	BOOL _activated;
}
@property(readonly, assign, nonatomic, getter=isActivated) BOOL activated;	// @synthesize=_activated
// declared property getter: -(BOOL)isActivated;
-(void)_setActivated:(BOOL)activated;
-(void)_buttonAction:(id)action;
@end

