/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString;

@interface SUCompletionsResponse : XXUnknownSuperclass {
@private
	NSArray* _completionItems;
	NSString* _title;
}
@property(readonly, assign, nonatomic) NSString* title;	// @synthesize=_title
@property(readonly, assign, nonatomic) NSArray* completionItems;	// @synthesize=_completionItems
// declared property getter: -(id)title;
// declared property getter: -(id)completionItems;
-(void)dealloc;
-(id)initWithPropertyList:(id)propertyList;
-(id)init;
@end

