/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUNavigationItem.h"

@class NSNumber;

@interface SUDelayedNavigationItem : SUNavigationItem {
@private
	id _delayedBackButtonTitle;
	id _delayedLeftBarButtonItems;
	NSNumber* _delayedLeftItemsSupplementBackButton;
	id _delayedTitle;
	id _delayedTitleView;
	id _delayedRightBarButtonItems;
	BOOL _shouldDelayChanges;
	SUNavigationItem* _wrappedNavigationItem;
}
@property(assign, nonatomic) BOOL shouldDelayChanges;	// @synthesize=_shouldDelayChanges
@property(retain, nonatomic) SUNavigationItem* wrappedNavigationItem;	// @synthesize=_wrappedNavigationItem
@property(retain) id titleView;	// converted property
@property(retain) id title;	// converted property
@property(assign) BOOL leftItemsSupplementBackButton;	// converted property
@property(retain) id backButtonTitle;	// converted property
// declared property setter: -(void)setWrappedNavigationItem:(id)item;
// declared property getter: -(id)wrappedNavigationItem;
// declared property setter: -(void)setShouldDelayChanges:(BOOL)delayChanges;
// declared property getter: -(BOOL)shouldDelayChanges;
-(void)_scheduleCommit;
-(void)_prepareButtonItemForDisplay:(id)display;
// converted property getter: -(id)titleView;
// converted property getter: -(id)title;
-(void)setTitleView:(id)view animated:(BOOL)animated;
// converted property setter: -(void)setTitleView:(id)view;
// converted property setter: -(void)setTitle:(id)title;
-(void)setRightBarButtonItems:(id)items animated:(BOOL)animated;
-(void)setRightBarButtonItem:(id)item animated:(BOOL)animated;
// converted property setter: -(void)setLeftItemsSupplementBackButton:(BOOL)button;
-(void)setLeftBarButtonItems:(id)items animated:(BOOL)animated;
-(void)setLeftBarButtonItem:(id)item animated:(BOOL)animated;
// converted property setter: -(void)setBackButtonTitle:(id)title;
-(id)rightBarButtonItems;
-(id)rightBarButtonItem;
-(id)navigationBar;
// converted property getter: -(BOOL)leftItemsSupplementBackButton;
-(id)leftBarButtonItems;
-(id)leftBarButtonItem;
// converted property getter: -(id)backButtonTitle;
-(void)commitDelayedChanges;
-(void)dealloc;
-(id)initWithNavigationItem:(id)navigationItem;
@end

