/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "NSCopying.h"
#import "iTunesStoreUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSURL, NSObject, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface SUMessage : XXUnknownSuperclass <NSCopying> {
	NSObject<OS_dispatch_queue>* _dispatchQueue;
	NSArray* _messageParts;
	NSURL* _postURL;
	NSMutableDictionary* _uploadURLs;
}
@property(copy) NSURL* postURL;
@property(copy) NSArray* messageParts;
-(id)uploadURLForMIMEType:(id)mimetype;
-(id)uploadURLForUTI:(id)uti;
-(void)setUploadURL:(id)url forUTI:(id)uti;
// declared property setter: -(void)setPostURL:(id)url;
// declared property setter: -(void)setMessageParts:(id)parts;
// declared property getter: -(id)postURL;
// declared property getter: -(id)messageParts;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithMessageParts:(id)messageParts;
-(id)init;
-(id)_initSUMessage;
@end

