/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "iTunesStoreUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

@interface SUReflectionView : XXUnknownSuperclass {
	UIImage* _image;
}
-(void)drawRect:(CGRect)rect;
-(void)setImage:(id)image;
-(void)dealloc;
@end

