/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUScriptObject.h"

@class NSArray, SUScriptURLRequest, NSString;

@interface SUScriptProtocol : SUScriptObject {
}
@property(assign) BOOL shouldShowInOverlay;
@property(readonly, assign) NSString* protocolVersion;
@property(retain) SUScriptURLRequest* overlayBackgroundURLRequest;
@property(assign) BOOL excludeFromNavigationHistory;
@property(retain) NSString* copyright;
@property(readonly, assign) NSString* clientIdentifier;
@property(retain) NSArray* allowedOrientations;
+(void)initialize;
+(id)webScriptNameForKeyName:(id)keyName;
-(id)scriptAttributeKeys;
-(id)attributeKeys;
-(id)_webThreadValueForProtocolKey:(id)protocolKey;
-(void)_setValue:(id)value forProtocolKey:(id)protocolKey;
-(void)_setProtocol:(id)protocol;
-(id)_copyProtocol;
// declared property getter: -(BOOL)shouldShowInOverlay;
// declared property setter: -(void)setShouldShowInOverlay:(BOOL)showInOverlay;
// declared property setter: -(void)setOverlayBackgroundURLRequest:(id)request;
// declared property setter: -(void)setExcludeFromNavigationHistory:(BOOL)navigationHistory;
// declared property setter: -(void)setCopyright:(id)copyright;
// declared property setter: -(void)setAllowedOrientations:(id)orientations;
// declared property getter: -(id)protocolVersion;
// declared property getter: -(id)overlayBackgroundURLRequest;
// declared property getter: -(BOOL)excludeFromNavigationHistory;
// declared property getter: -(id)copyright;
// declared property getter: -(id)clientIdentifier;
-(id)_className;
// declared property getter: -(id)allowedOrientations;
-(void)setValuesFromDictionary:(id)dictionary;
@end

