/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUActivityItemProviderDelegate.h"
#import "SUScriptObject.h"

@class WebScriptObject, SUActivityItemProvider, SUScriptFunction, NSString;

@interface SUScriptActivityItemProvider : SUScriptObject <SUActivityItemProviderDelegate> {
@private
	id _item;
	id _itemBlock;
	SUScriptFunction* _itemFunction;
	int _loadState;
	NSString* _mimeType;
	SUActivityItemProvider* _nativeProvider;
	int _previewLoadState;
}
@property(copy) NSString* status;
@property(assign) float progress;
@property(readonly, assign) NSString* MIMEType;
@property(retain) WebScriptObject* itemFunction;
@property(readonly, assign) NSString* activityType;
@property(readonly, assign) SUActivityItemProvider* nativeActivityItemProvider;
+(void)initialize;
+(id)webScriptNameForSelector:(SEL)selector;
+(id)webScriptNameForKeyName:(id)keyName;
-(id)scriptAttributeKeys;
-(id)attributeKeys;
-(id)_newPlaceholderWithMIMEType:(id)mimetype;
-(void)_finishPreviewWithImage:(id)image;
-(void)_finishItemWithItem:(id)item;
-(void)activityItemProvider:(id)provider provideItemUsingBlock:(id)block;
// declared property getter: -(id)status;
// declared property setter: -(void)setStatus:(id)status;
// declared property setter: -(void)setProgress:(float)progress;
// declared property setter: -(void)setItemFunction:(id)function;
// declared property getter: -(float)progress;
// declared property getter: -(id)MIMEType;
// declared property getter: -(id)itemFunction;
-(id)_className;
// declared property getter: -(id)activityType;
-(void)setPreviewImageWithURLString:(id)urlstring;
-(void)setItem:(id)item;
-(id)activitySupportsMIMEType:(id)type;
// declared property getter: -(id)nativeActivityItemProvider;
-(void)dealloc;
-(id)initWithMIMEType:(id)mimetype;
@end

