/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUScriptButtonNativeObject.h"
#import "iTunesStoreUI-Structs.h"


@interface SUScriptNativeUIButton : SUScriptButtonNativeObject {
}
@property(retain) id title;	// converted property
@property(assign) int tag;	// converted property
@property(assign) UIEdgeInsets imageInsets;	// converted property
@property(retain) id image;	// converted property
+(id)objectWithDefaultButtonForScriptButton:(id)scriptButton;
-(void)setupNativeObject;
-(void)disconnectButtonAction;
-(void)destroyNativeObject;
-(void)connectButtonAction;
// converted property getter: -(id)title;
// converted property getter: -(int)tag;
// converted property setter: -(void)setTitle:(id)title;
// converted property setter: -(void)setTag:(int)tag;
// converted property setter: -(void)setImageInsets:(UIEdgeInsets)insets;
// converted property setter: -(void)setImage:(id)image;
// converted property getter: -(UIEdgeInsets)imageInsets;
// converted property getter: -(id)image;
@end

