/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SUScriptModalDialogResponse : XXUnknownSuperclass {
	int _buttonIndex;
	NSString* _textFieldValue;
}
@property(retain, nonatomic) NSString* textFieldValue;	// @synthesize=_textFieldValue
@property(assign, nonatomic) int buttonIndex;	// @synthesize=_buttonIndex
// declared property setter: -(void)setTextFieldValue:(id)value;
// declared property getter: -(id)textFieldValue;
// declared property setter: -(void)setButtonIndex:(int)index;
// declared property getter: -(int)buttonIndex;
-(void)dealloc;
@end

