/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUScriptTextFieldNativeObject.h"
#import "iTunesStoreUI-Structs.h"


@interface SUScriptTextFieldNativeObjectUIBarButtonItem : SUScriptTextFieldNativeObject {
}
@property(assign) float width;	// converted property
@property(retain) id value;	// converted property
@property(retain) id placeholder;	// converted property
@property(assign) int keyboardType;	// converted property
@property(assign) int autocorrectionType;	// converted property
@property(assign) int autocapitalizationType;	// converted property
// converted property getter: -(float)width;
// converted property getter: -(id)value;
// converted property setter: -(void)setWidth:(float)width;
// converted property setter: -(void)setValue:(id)value;
-(void)setupNativeObject;
// converted property setter: -(void)setPlaceholder:(id)placeholder;
-(void)_setNativeObjectDelegate:(id)delegate;
// converted property setter: -(void)setKeyboardType:(int)type;
// converted property setter: -(void)setAutocorrectionType:(int)type;
// converted property setter: -(void)setAutocapitalizationType:(int)type;
-(BOOL)resignFirstResponder;
// converted property getter: -(id)placeholder;
-(id)_nativeObjectDelegate;
// converted property getter: -(int)keyboardType;
-(void)destroyNativeObject;
-(BOOL)becomeFirstResponder;
// converted property getter: -(int)autocorrectionType;
// converted property getter: -(int)autocapitalizationType;
-(id)_textField;
@end

