/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CPAggregateDictionary : XXUnknownSuperclass {
}
@property(readonly, assign, nonatomic, getter=isEnabled) BOOL enabled;
+(id)sharedAggregateDictionary;
// declared property getter: -(BOOL)isEnabled;
-(void)pushValue:(double)value forKey:(id)key;
-(void)setValue:(double)value forDistributionKey:(id)distributionKey;
-(void)clearDistributionKey:(id)key;
-(void)subtractValue:(long long)value forKey:(id)key;
-(void)addValue:(long long)value forKey:(id)key;
-(void)decrementKey:(id)key;
-(void)incrementKey:(id)key;
-(void)setValue:(long long)value forScalarKey:(id)scalarKey;
-(void)clearScalarKey:(id)key;
-(int)commit;
-(void)significantTimeChanged;
@end

