/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

#import "UIFoundation-Structs.h"
#import "NSGlyphStorage.h"
#import "NSATSTypesetter.h"


__attribute__((visibility("hidden")))
@interface NSSingleLineTypesetter : NSATSTypesetter <NSGlyphStorage> {
@private
	float _lineWidth;
	NSRange _currentBufferRange;
	unsigned* _glyphBuffer;
	unsigned* _inscriptionBuffer;
	BOOL* _elasticBuffer;
	struct {
		unsigned _usesScreenFonts : 1;
		unsigned _reserved : 31;
	} _slFlags;
}
+(bool)_validateAttributes:(id)attributes;
+(void)initialize;
+(id)singleLineTypesetter;
-(void)setBidiLevels:(const char*)levels forGlyphRange:(NSRange)glyphRange;
-(void)setAttachmentSize:(CGSize)size forGlyphRange:(NSRange)glyphRange;
-(void)setLocation:(CGPoint)location withAdvancements:(const float*)advancements forStartOfGlyphRange:(NSRange)glyphRange;
-(void)setDrawsOutsideLineFragment:(BOOL)fragment forGlyphRange:(NSRange)glyphRange;
-(void)setNotShownAttribute:(BOOL)attribute forGlyphRange:(NSRange)glyphRange;
-(void)deleteGlyphsInRange:(NSRange)range;
-(void)insertGlyph:(unsigned)glyph atGlyphIndex:(unsigned)glyphIndex characterIndex:(unsigned)index;
-(void)substituteGlyphsInRange:(NSRange)range withGlyphs:(unsigned*)glyphs;
-(void)setLineFragmentRect:(CGRect)rect forGlyphRange:(NSRange)glyphRange usedRect:(CGRect)rect3 baselineOffset:(float)offset;
-(id)substituteFontForFont:(id)font;
-(void)getLineFragmentRect:(CGRect*)rect usedRect:(CGRect*)rect2 remainingRect:(CGRect*)rect3 forStartingGlyphAtIndex:(unsigned)index proposedRect:(CGRect)rect5 lineSpacing:(float)spacing paragraphSpacingBefore:(float)before paragraphSpacingAfter:(float)after;
-(unsigned)getGlyphsInRange:(NSRange)range glyphs:(unsigned*)glyphs characterIndexes:(unsigned*)indexes glyphInscriptions:(unsigned*)inscriptions elasticBits:(BOOL*)bits bidiLevels:(char*)levels;
-(NSRange)glyphRangeForCharacterRange:(NSRange)characterRange actualCharacterRange:(NSRange*)range;
-(NSRange)characterRangeForGlyphRange:(NSRange)glyphRange actualGlyphRange:(NSRange*)range;
-(id)attributedString;
-(unsigned)layoutOptions;
-(void)setIntAttribute:(int)attribute value:(int)value forGlyphAtIndex:(unsigned)index;
-(void)insertGlyphs:(const unsigned*)glyphs length:(unsigned)length forStartingGlyphAtIndex:(unsigned)index characterIndex:(unsigned)index4;
-(id)createRenderingContextForCharacterRange:(NSRange)characterRange typesetterBehavior:(int)behavior usesScreenFonts:(BOOL)fonts hasStrongRight:(BOOL)right maximumWidth:(float)width;
-(id)init;
-(BOOL)_allowsEllipsisGlyphSubstitution;
-(BOOL)_usesScreenFonts;
-(void)done;
@end

