/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

#import "UIFoundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface NSTextStorage : XXUnknownSuperclass {
@private
	NSRange _editedRange;
	int _editedDelta;
	struct {
		unsigned editedMask : 8;
		unsigned  : 8;
		unsigned disabled : 16;
	} _flags;
	NSMutableArray* _layoutManagers;
	id _sideData;
}
@property(assign) id delegate;	// converted property
@property(readonly, assign) NSRange editedRange;	// converted property
@property(readonly, retain) NSMutableArray* layoutManagers;	// converted property
+(id)allocWithZone:(NSZone*)zone;
// converted property getter: -(id)delegate;
// converted property setter: -(void)setDelegate:(id)delegate;
-(void)fontSetChanged;
-(void)_notifyEdited:(unsigned)edited range:(NSRange)range changeInLength:(int)length invalidatedRange:(NSRange)range4;
-(BOOL)fixesAttributesLazily;
-(void)ensureAttributesAreFixedInRange:(NSRange)range;
-(void)invalidateAttributesInRange:(NSRange)range;
-(NSRange)_rangeByEstimatingAttributeFixingForRange:(NSRange)range;
-(void)processEditing;
-(void)edited:(unsigned)edited range:(NSRange)range changeInLength:(int)length;
-(int)changeInLength;
-(unsigned)editedMask;
// converted property getter: -(NSRange)editedRange;
-(BOOL)_isEditing;
-(void)endEditing;
-(void)beginEditing;
-(BOOL)_forceFixAttributes;
-(void)_setForceFixAttributes:(BOOL)attributes;
-(void)_unlock;
-(BOOL)_lockForWritingWithExceptionHandler:(BOOL)exceptionHandler;
-(BOOL)_lockForWriting;
-(BOOL)_lockForReading;
// converted property getter: -(id)layoutManagers;
-(void)removeLayoutManager:(id)manager;
-(void)addLayoutManager:(id)manager;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(Class)classForCoder;
-(void)finalize;
-(void)dealloc;
-(id)init;
@end

