/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

#import "NSCopying.h"
#import "UIFoundation-Structs.h"
#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSTextTab : XXUnknownSuperclass <NSCopying, NSCoding> {
@private
	struct {
		unsigned alignment : 4;
		unsigned refCount : 24;
		unsigned unused : 4;
	} _flags;
	float _location;
	id _reserved;
}
@property(readonly, assign) float location;	// converted property
+(id)allocWithZone:(NSZone*)zone;
+(void)initialize;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)accessibilityRulerMarkerTypeDescription;
-(id)accessibilityRulerMarkerType;
-(unsigned)tabStopType;
// converted property getter: -(float)location;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)retainCount;
-(oneway void)release;
-(id)retain;
-(BOOL)_isDeallocating;
-(BOOL)_tryRetain;
-(void)dealloc;
-(id)options;
-(int)alignment;
-(id)initWithTextAlignment:(int)textAlignment location:(float)location options:(id)options;
-(id)initWithType:(unsigned)type location:(float)location;
@end

