/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IMMessage, NSString, NSDate;

@interface IMChatItem : XXUnknownSuperclass {
	NSDate* _date;
	id _datum1;
	id _datum2;
	id _datum3;
	BOOL _isFromArchive;
	NSString* _guid;
}
@property(readonly, assign, nonatomic) BOOL isFromArchive;
@property(readonly, assign, nonatomic) IMMessage* message;
@property(readonly, assign, nonatomic) NSString* stringValue;
@property(readonly, assign, nonatomic) NSDate* date;	// @synthesize=_date
@property(retain, nonatomic) NSString* guid;	// @synthesize=_guid
// declared property getter: -(id)date;
// declared property setter: -(void)setGuid:(id)guid;
// declared property getter: -(id)guid;
-(int)_reverseCompareToChatItem:(id)chatItem;
-(int)_compareToChatItem:(id)chatItem;
// declared property getter: -(BOOL)isFromArchive;
-(void)_setIsFromArchive:(BOOL)archive;
// declared property getter: -(id)message;
// declared property getter: -(id)stringValue;
-(void)dealloc;
-(id)_initWithGUID:(id)guid date:(id)date datum1:(id)a1 datum2:(id)a2 datum3:(id)a3;
@end

