/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface IMHandleRegistrarInternal : XXUnknownSuperclass {
	NSMutableDictionary* _siblingsMap;
	NSMutableDictionary* _accountSiblingsMap;
	NSMutableDictionary* _existingAccountSiblingsMap;
	NSMutableDictionary* _chatSiblingsMap;
	NSMutableDictionary* _existingChatSiblingsMap;
	NSMutableArray* _allIMHandles;
	NSMutableDictionary* _candidateNamesMap;
	NSMutableDictionary* _usedUniqueNames;
	NSMutableSet* _knownConflictingNames;
	int _nameStyle;
}
-(void)dealloc;
@end

