/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ScreenReaderBrailleDriver.framework/ScreenReaderBrailleDriver
 */

#import "ScreenReaderBrailleDriver-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SCRDUSBDevice : XXUnknownSuperclass {
	IOUSBDeviceStruct300Ref* _device;
	IOUSBInterfaceStruct220Ref* _interface;
	BOOL _isOpen;
	BOOL _isConfigured;
	NSString* _privateRunLoopMode;
	IONotificationPortRef _notificationPort;
	unsigned _notification;
}
@property(readonly, assign) BOOL isOpen;	// converted property
@property(readonly, assign) BOOL isConfigured;	// converted property
-(BOOL)clearPipe:(unsigned char)pipe bothEnds:(BOOL)ends;
-(void)abortPipe:(unsigned char)pipe;
-(void)registerForDisconnectNotifications:(BOOL)disconnectNotifications;
-(BOOL)getInformationForPipe:(unsigned char)pipe direction:(char*)direction number:(char*)number transferType:(char*)type maxPacketSize:(unsigned short*)size interval:(char*)interval;
-(unsigned long)_transferData:(void*)data withSize:(unsigned long)size toPipe:(unsigned char)pipe withTimeout:(double)timeout withFunction:(/*function-pointer*/ void*)function;
-(unsigned long)readData:(void*)data withSize:(unsigned long)size fromBulkPipe:(unsigned char)bulkPipe withNoDataTimeout:(unsigned long)noDataTimeout andCompletionTimeOut:(unsigned long)anOut;
-(BOOL)readData:(void*)data withSize:(unsigned*)size fromPipe:(unsigned char)pipe;
-(unsigned long)readData:(void*)data withSize:(unsigned long)size fromPipe:(unsigned char)pipe withTimeout:(double)timeout;
-(BOOL)writeData:(void*)data withSize:(unsigned long)size toBulkPipe:(unsigned char)bulkPipe withNoDataTimeout:(unsigned long)noDataTimeout andCompletionTimeOut:(unsigned long)anOut;
-(unsigned long)writeData:(void*)data withSize:(unsigned long)size toPipe:(unsigned char)pipe withTimeout:(double)timeout;
-(BOOL)sendControlRequest:(unsigned char)request type:(unsigned char)type value:(unsigned short)value index:(unsigned short)index data:(void*)data size:(unsigned short)size sizeTransferred:(unsigned*)transferred pipe:(unsigned char)pipe timeout:(double)timeout;
-(BOOL)setAlternateInterface:(unsigned char)interface;
-(BOOL)setInterface:(unsigned char)interface;
-(BOOL)setConfiguration:(unsigned char)configuration;
-(unsigned char)numberOfConfigurations;
-(BOOL)reset;
-(long)product;
-(long)vendor;
// converted property getter: -(BOOL)isConfigured;
// converted property getter: -(BOOL)isOpen;
-(BOOL)close;
-(BOOL)openWithSeize:(BOOL)seize;
-(BOOL)open;
-(void)dealloc;
-(id)initWithIOObject:(unsigned)ioobject;
@end

