/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
 */



@protocol MBConnectionHandler
-(void)connectionWasInvalid:(id)invalid;
-(void)connectionWasInterrupted:(id)interrupted;
-(void)connection:(id)connection didReceiveMessage:(id)message;
@end

