/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "FTServices-Structs.h"
#import "FTIDSMessage.h"
#import "NSCopying.h"

@class NSData;

@interface FTFaceTimeMessage : FTIDSMessage <NSCopying> {
	NSData* _sessionToken;
}
@property(copy) NSData* sessionToken;	// @synthesize=_sessionToken
// declared property setter: -(void)setSessionToken:(id)token;
// declared property getter: -(id)sessionToken;
-(id)messageBody;
-(id)requiredKeys;
-(BOOL)isValidMessage;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

