/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "NSCopying.h"
#import "FTiMessagePeerMessage.h"
#import "FTServices-Structs.h"

@class NSData, NSString;

@interface FTiMessageTextMessage : FTiMessagePeerMessage <NSCopying> {
	NSData* _messageData;
	NSString* _encryptionType;
}
@property(copy) NSString* encryptionType;	// @synthesize=_encryptionType
@property(copy) NSData* messageData;	// @synthesize=_messageData
// declared property setter: -(void)setEncryptionType:(id)type;
// declared property getter: -(id)encryptionType;
// declared property setter: -(void)setMessageData:(id)data;
// declared property getter: -(id)messageData;
-(id)messageBody;
-(BOOL)payloadCanBeLogged;
-(id)requiredKeys;
-(int)command;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

