/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "NSCopying.h"
#import "FTServices-Structs.h"
#import "FTiMessageMessage.h"


@interface FTiMessagePendingOfflineMessageReponse : FTiMessageMessage <NSCopying> {
}
-(int)command;
-(id)copyWithZone:(NSZone*)zone;
@end

