/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "FTServices-Structs.h"
#import "FTMessage.h"
#import "NSCopying.h"

@class NSData, NSString;

@interface FTProfileMessage : FTMessage <NSCopying> {
	NSData* _pushCert;
	SecKey* _pushKey;
	SecKey* _pushPublicKey;
	NSData* _pushToken;
	NSString* _authToken;
	NSString* _profileID;
}
@property(copy, nonatomic) NSData* pushToken;	// @synthesize=_pushToken
@property(copy, nonatomic) NSData* pushCertificate;	// @synthesize=_pushCert
@property(assign, nonatomic) SecKey* pushPublicKey;	// @synthesize=_pushPublicKey
@property(assign, nonatomic) SecKey* pushPrivateKey;	// @synthesize=_pushKey
@property(copy, nonatomic) NSString* authToken;	// @synthesize=_authToken
@property(copy, nonatomic) NSString* profileID;	// @synthesize=_profileID
// declared property setter: -(void)setProfileID:(id)anId;
// declared property getter: -(id)profileID;
// declared property setter: -(void)setAuthToken:(id)token;
// declared property getter: -(id)authToken;
// declared property setter: -(void)setPushToken:(id)token;
// declared property getter: -(id)pushToken;
// declared property getter: -(SecKey*)pushPublicKey;
// declared property getter: -(SecKey*)pushPrivateKey;
// declared property setter: -(void)setPushCertificate:(id)certificate;
// declared property getter: -(id)pushCertificate;
-(void)handleResponseDictionary:(id)dictionary;
-(id)additionalMessageHeaders;
-(id)additionalMessageHeadersForOutgoingPush;
-(BOOL)hasRequiredKeys:(id*)keys;
-(int)responseCommand;
-(int)command;
-(BOOL)wantsBinaryPush;
-(BOOL)wantsCompressedBody;
-(BOOL)wantsHTTPHeaders;
-(BOOL)wantsBagKey;
// declared property setter: -(void)setPushPrivateKey:(SecKey*)key;
// declared property setter: -(void)setPushPublicKey:(SecKey*)key;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

