/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableArray, NSData, NSMutableSet;

@interface FTPushHandler : XXUnknownSuperclass {
	NSMutableSet* _topics;
	NSMutableArray* _handlers;
	BOOL _registeredForPush;
}
@property(readonly, assign, nonatomic) int connectionStatus;
@property(assign, nonatomic) BOOL registered;
@property(readonly, assign, nonatomic) NSData* pushToken;
@property(retain, nonatomic) NSArray* topics;
+(id)sharedInstance;
+(id)alloc;
-(void)removeListener:(id)listener;
-(void)addListener:(id)listener;
// declared property getter: -(int)connectionStatus;
// declared property getter: -(id)pushToken;
// declared property setter: -(void)setRegistered:(BOOL)registered;
// declared property getter: -(BOOL)registered;
-(void)removeTopic:(id)topic;
-(void)addTopic:(id)topic;
// declared property getter: -(id)topics;
-(void)updateTopics;
// declared property setter: -(void)setTopics:(id)topics;
-(void)requestKeepAlive;
-(void)dealloc;
-(id)initWithTopics:(id)topics;
-(id)init;
@end

