/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary, NSArray;

@interface FTRegion : XXUnknownSuperclass {
	NSDictionary* _dictionary;
	NSArray* _subRegions;
	FTRegion* _parentRegion;
}
@property(retain) FTRegion* _parentRegion;	// @synthesize
@property(retain) NSDictionary* _dictionary;	// @synthesize
@property(readonly, assign) NSArray* subRegions;	// @synthesize=_subRegions
@property(readonly, assign) FTRegion* parentRegion;
@property(readonly, assign) NSString* basePhoneNumber;
@property(readonly, assign) NSString* regionID;
@property(readonly, assign) NSString* label;
@property(readonly, assign) NSString* isoCode;
// declared property setter: -(void)set_parentRegion:(id)region;
// declared property getter: -(id)_parentRegion;
// declared property setter: -(void)set_dictionary:(id)dictionary;
// declared property getter: -(id)_dictionary;
-(id)description;
// declared property getter: -(id)regionID;
// declared property getter: -(id)basePhoneNumber;
// declared property getter: -(id)label;
// declared property getter: -(id)isoCode;
-(id)regionWithID:(id)anId;
// declared property getter: -(id)subRegions;
// declared property getter: -(id)parentRegion;
-(void)_setParentRegion:(id)region;
-(void)dealloc;
-(id)_initWithDictionary:(id)dictionary;
@end

