/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "NSCopying.h"
#import "FTServices-Structs.h"
#import "FTIDSMessage.h"

@class NSData, NSString;

@interface FTRecoverSignatureMessage : FTIDSMessage <NSCopying> {
	NSData* _responseSignature;
	NSString* _protocolVersion;
}
@property(copy) NSData* responseSignature;	// @synthesize=_responseSignature
@property(copy) NSString* protocolVersion;	// @synthesize=_protocolVersion
// declared property setter: -(void)setProtocolVersion:(id)version;
// declared property getter: -(id)protocolVersion;
// declared property setter: -(void)setResponseSignature:(id)signature;
// declared property getter: -(id)responseSignature;
-(void)handleResponseDictionary:(id)dictionary;
-(id)additionalMessageHeaders;
-(id)requiredKeys;
-(id)bagKey;
-(BOOL)hasRequiredKeys:(id*)keys;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

