/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface XXUnknownSuperclass (_FTServerBagAdditions)
-(id)_cacheTime;
@end

@interface XXUnknownSuperclass (_FTServerBagAdditions)
-(id)_cacheTime;
@end

@interface XXUnknownSuperclass (FTAPSOutgoingMessage_Additions)
-(id)_FTFilteredArrayForAPS;
-(id)_IDsFromURIs;
-(id)_URIsByTrimmingBindings:(id)bindings;
-(id)_URIsFromIDs;
@end

@interface XXUnknownSuperclass (FTAPSOutgoingMessage_Additions)
-(id)_FTFilteredDictionaryForAPS;
@end

@interface XXUnknownSuperclass (FaceTimeStringAdditions)
@property(readonly, assign, nonatomic) NSData* _FTDataFromHexString;
@property(readonly, assign, nonatomic) NSData* _FTDataFromBase64String;
// declared property getter: -(id)_FTDataFromHexString;
// declared property getter: -(id)_FTDataFromBase64String;
@end

@interface XXUnknownSuperclass (CompressionAdditions)
-(id)_FTCopyGzippedData;
-(id)_FTOptionallyDecompressData;
-(id)_FTDecompressData;
-(id)_FTStringFromBaseData;
@end

