/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

#import "AccountsDaemon-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ACDAuthenticationHandlerQueueManager, NSSet;

@interface ACDAuthenticationPluginManager : XXUnknownSuperclass {
@private
	ACDAuthenticationHandlerQueueManager* _handlerManager;
	NSSet* _pluginBundles;
	dispatch_queue_s* _authenticationPluginQueue;
	dispatch_semaphore_s* _authPluginSemaphore;
}
@property(readonly, assign) NSSet* pluginBundles;	// @synthesize=_pluginBundles
// declared property getter: -(id)pluginBundles;
-(void).cxx_destruct;
-(void)promptUserForCredentialsWithAccount:(id)account handler:(id)handler;
-(void)renewCredentialsForAccount:(id)account accountStore:(id)store handler:(id)handler;
-(void)verifyCredentialsForAccount:(id)account client:(id)client handler:(id)handler;
-(void)verifyCredentialsForAccount:(id)account client:(id)client saveWhenAuthorized:(BOOL)authorized handler:(id)handler;
-(id)pluginForAccountType:(id)accountType;
-(void)dealloc;
-(id)init;
@end

