/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ACDDatabase, NSManagedObjectContext, NSPersistentStoreCoordinator;

@interface ACDDatabaseMigrator : XXUnknownSuperclass {
@private
	NSManagedObjectContext* _migrationContext;
	NSPersistentStoreCoordinator* _coordinator;
	ACDDatabase* _database;
}
-(void).cxx_destruct;
-(int)_versionForModel:(id)model;
-(id)_compatibleModelForStoreAtURL:(id)url;
-(id)_setUpContextForMigration;
-(id)_fetchAllAuthorizationEntitiesForModelVersion:(int)modelVersion;
-(void)_migrateAccessAuthorizationsToTCCFromModelVersion:(int)modelVersion;
-(BOOL)run;
-(id)initForDatabase:(id)database;
@end

