/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

#import "AccountsDaemon-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface ACDPreferences : XXUnknownSuperclass {
}
+(id)sharedPreferences;
-(void)synchronize;
-(double)serverTimeoutInterval;
-(void)_setValue:(id)value forKey:(CFStringRef)key;
-(id)_valueForKey:(CFStringRef)key;
@end

