/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (YTExtensions)
-(BOOL)_yt_containsSubstring:(id)substring;
-(id)stringByRemovingLTGT;
-(id)youTubeTrimmedString;
-(id)escapedYouTubeSearchString;
-(id)newYouTubeVideoDescription;
@end

@interface XXUnknownSuperclass (YTBase64)
-(id)webSafeBase64Data;
@end

@interface XXUnknownSuperclass (YTBase64)
-(id)decodedWebSafeBase64Data;
@end

@interface XXUnknownSuperclass (Protection)
-(BOOL)writeToProtectedFile:(id)protectedFile atomically:(BOOL)atomically;
@end

