/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YTXMLHTTPRequest.h"

@class YTVideo, NSMutableString, NSMutableArray;

@interface YTCommentsRequest : YTXMLHTTPRequest {
	id _delegate;
	NSMutableArray* _comments;
	unsigned _startIndex;
	unsigned _totalResults;
	NSMutableString* _moreCommentsURLString;
	YTVideo* _video;
}
+(unsigned)commentsPerRequest;
-(void)failWithError:(id)error;
-(void)didAuthenticate:(id)authenticate;
-(void)didParseData;
-(int)parseData:(id)data;
-(void)dealloc;
-(id)initRequestingCommentsForVideo:(id)video withDelegate:(id)delegate;
-(void)requestMoreComments;
-(void)_requestCommentsFromURL:(id)url;
@end

