/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString;

@interface YTPersistentVideoList : XXUnknownSuperclass {
	NSString* _categoryName;
	NSMutableArray* _videos;
}
@property(readonly, retain) NSMutableArray* videos;	// converted property
+(id)persistPathWithCategoryName:(id)categoryName;
-(void)addVideo:(id)video;
// converted property getter: -(id)videos;
-(void)removeFromDisk;
-(void)persist;
-(void)dealloc;
-(id)initWithCategoryName:(id)categoryName;
@end

