/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSArray;

@interface PBFilterClassDescription : XXUnknownSuperclass {
	NSDictionary* _attributes;
	NSArray* _inputKeys;
}
@property(readonly, retain) NSDictionary* attributes;	// converted property
@property(readonly, retain) NSArray* inputKeys;	// converted property
+(id)classDescriptionForClass:(Class)aClass;
// converted property getter: -(id)inputKeys;
// converted property getter: -(id)attributes;
-(id)initWithClass:(Class)aClass;
@end

