/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
 */

#import "PhotoBoothEffects-Structs.h"
#import "PBSqueezeFilter.h"
#import "PBFilter.h"
#import "PBContext.h"
#import "PBTwirlFilter.h"
#import "PBStretchFilter.h"
#import "PBFilterClassDescription.h"
#import "PBLightTunnelFilter.h"
#import "PBCoreImageContext.h"
#import "PBXRayFilter.h"
#import "PBKaleidoscopeFilter.h"
#import "PBNormalFilter.h"
#import "PBMirrorFilter.h"
#import "PBThermalFilter.h"
